// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pooling4.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pooling4::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pooling4::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> max_pooling4::ap_ST_fsm_state1 = "1";
const sc_lv<4> max_pooling4::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<4> max_pooling4::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<4> max_pooling4::ap_ST_fsm_state11 = "1000";
const bool max_pooling4::ap_const_boolean_1 = true;
const sc_lv<32> max_pooling4::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pooling4::ap_const_lv32_1 = "1";
const bool max_pooling4::ap_const_boolean_0 = false;
const sc_lv<1> max_pooling4::ap_const_lv1_0 = "0";
const sc_lv<32> max_pooling4::ap_const_lv32_2 = "10";
const sc_lv<1> max_pooling4::ap_const_lv1_1 = "1";
const sc_lv<11> max_pooling4::ap_const_lv11_0 = "00000000000";
const sc_lv<5> max_pooling4::ap_const_lv5_0 = "00000";
const sc_lv<8> max_pooling4::ap_const_lv8_0 = "00000000";
const sc_lv<3> max_pooling4::ap_const_lv3_0 = "000";
const sc_lv<6> max_pooling4::ap_const_lv6_0 = "000000";
const sc_lv<4> max_pooling4::ap_const_lv4_0 = "0000";
const sc_lv<2> max_pooling4::ap_const_lv2_0 = "00";
const sc_lv<11> max_pooling4::ap_const_lv11_640 = "11001000000";
const sc_lv<11> max_pooling4::ap_const_lv11_1 = "1";
const sc_lv<8> max_pooling4::ap_const_lv8_64 = "1100100";
const sc_lv<4> max_pooling4::ap_const_lv4_4 = "100";
const sc_lv<6> max_pooling4::ap_const_lv6_14 = "10100";
const sc_lv<3> max_pooling4::ap_const_lv3_1 = "1";
const sc_lv<5> max_pooling4::ap_const_lv5_1 = "1";
const sc_lv<2> max_pooling4::ap_const_lv2_1 = "1";
const sc_lv<2> max_pooling4::ap_const_lv2_2 = "10";
const sc_lv<4> max_pooling4::ap_const_lv4_1 = "1";
const sc_lv<6> max_pooling4::ap_const_lv6_1 = "1";
const sc_lv<8> max_pooling4::ap_const_lv8_1 = "1";
const sc_lv<32> max_pooling4::ap_const_lv32_D368D4A5 = "11010011011010001101010010100101";
const sc_lv<32> max_pooling4::ap_const_lv32_17 = "10111";
const sc_lv<32> max_pooling4::ap_const_lv32_1E = "11110";
const sc_lv<8> max_pooling4::ap_const_lv8_FF = "11111111";
const sc_lv<23> max_pooling4::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> max_pooling4::ap_const_lv5_2 = "10";
const sc_lv<32> max_pooling4::ap_const_lv32_3 = "11";

max_pooling4::max_pooling4(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lenet_cnn_fcmp_32dEe_U26 = new lenet_cnn_fcmp_32dEe<1,2,32,32,1>("lenet_cnn_fcmp_32dEe_U26");
    lenet_cnn_fcmp_32dEe_U26->clk(ap_clk);
    lenet_cnn_fcmp_32dEe_U26->reset(ap_rst);
    lenet_cnn_fcmp_32dEe_U26->din0(grp_fu_231_p0);
    lenet_cnn_fcmp_32dEe_U26->din1(grp_fu_231_p1);
    lenet_cnn_fcmp_32dEe_U26->ce(ap_var_for_const0);
    lenet_cnn_fcmp_32dEe_U26->opcode(ap_var_for_const1);
    lenet_cnn_fcmp_32dEe_U26->dout(grp_fu_231_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln80_fu_261_p2);
    sensitive << ( ap_phi_mux_indvar_flatten117_phi_fu_129_p4 );

    SC_METHOD(thread_add_ln81_1_fu_694_p2);
    sensitive << ( indvar_flatten63_reg_148 );

    SC_METHOD(thread_add_ln82_1_fu_680_p2);
    sensitive << ( indvar_flatten24_reg_171 );

    SC_METHOD(thread_add_ln83_1_fu_667_p2);
    sensitive << ( indvar_flatten_reg_195 );

    SC_METHOD(thread_add_ln88_1_fu_649_p2);
    sensitive << ( zext_ln84_fu_645_p1 );
    sensitive << ( select_ln82_1_fu_524_p3 );

    SC_METHOD(thread_add_ln88_2_fu_601_p2);
    sensitive << ( select_ln81_1_fu_460_p3 );
    sensitive << ( zext_ln83_1_fu_597_p1 );

    SC_METHOD(thread_add_ln88_fu_249_p2);
    sensitive << ( shl_ln_fu_237_p3 );
    sensitive << ( zext_ln83_fu_245_p1 );

    SC_METHOD(thread_add_ln89_1_fu_619_p2);
    sensitive << ( add_ln89_fu_392_p2 );
    sensitive << ( zext_ln83_2_fu_615_p1 );

    SC_METHOD(thread_add_ln89_2_fu_792_p2);
    sensitive << ( zext_ln89_3_fu_788_p1 );
    sensitive << ( p_shl_cast_fu_774_p3 );

    SC_METHOD(thread_add_ln89_3_fu_801_p2);
    sensitive << ( add_ln89_2_fu_792_p2 );
    sensitive << ( zext_ln89_4_fu_798_p1 );

    SC_METHOD(thread_add_ln89_fu_392_p2);
    sensitive << ( zext_ln89_2_fu_388_p1 );
    sensitive << ( zext_ln89_1_fu_376_p1 );

    SC_METHOD(thread_add_ln93_1_fu_730_p2);
    sensitive << ( add_ln93_fu_721_p2 );
    sensitive << ( zext_ln81_fu_727_p1 );

    SC_METHOD(thread_add_ln93_2_fu_748_p2);
    sensitive << ( zext_ln93_1_fu_736_p1 );
    sensitive << ( p_shl1_cast_fu_740_p3 );

    SC_METHOD(thread_add_ln93_3_fu_763_p2);
    sensitive << ( add_ln93_2_fu_748_p2 );
    sensitive << ( zext_ln82_fu_759_p1 );

    SC_METHOD(thread_add_ln93_fu_721_p2);
    sensitive << ( zext_ln89_fu_707_p1 );
    sensitive << ( zext_ln93_fu_717_p1 );

    SC_METHOD(thread_and_ln5_fu_965_p2);
    sensitive << ( grp_fu_231_p2 );
    sensitive << ( or_ln5_fu_959_p2 );

    SC_METHOD(thread_and_ln81_1_fu_500_p2);
    sensitive << ( or_ln81_1_reg_1038 );
    sensitive << ( and_ln89_3_fu_425_p2 );

    SC_METHOD(thread_and_ln81_2_fu_505_p2);
    sensitive << ( or_ln81_1_reg_1038 );
    sensitive << ( and_ln89_4_fu_436_p2 );

    SC_METHOD(thread_and_ln81_3_fu_329_p2);
    sensitive << ( or_ln81_1_fu_323_p2 );
    sensitive << ( and_ln89_5_fu_293_p2 );

    SC_METHOD(thread_and_ln81_fu_488_p2);
    sensitive << ( or_ln81_1_reg_1038 );
    sensitive << ( and_ln89_2_fu_408_p2 );

    SC_METHOD(thread_and_ln82_1_fu_549_p2);
    sensitive << ( xor_ln82_fu_531_p2 );
    sensitive << ( and_ln81_1_fu_500_p2 );

    SC_METHOD(thread_and_ln82_2_fu_555_p2);
    sensitive << ( xor_ln82_fu_531_p2 );
    sensitive << ( and_ln81_2_fu_505_p2 );

    SC_METHOD(thread_and_ln82_fu_536_p2);
    sensitive << ( and_ln81_fu_488_p2 );
    sensitive << ( xor_ln82_fu_531_p2 );

    SC_METHOD(thread_and_ln89_1_fu_913_p2);
    sensitive << ( and_ln89_fu_907_p2 );
    sensitive << ( grp_fu_231_p2 );

    SC_METHOD(thread_and_ln89_2_fu_408_p2);
    sensitive << ( xor_ln89_reg_1017 );
    sensitive << ( trunc_ln83_fu_404_p1 );

    SC_METHOD(thread_and_ln89_3_fu_425_p2);
    sensitive << ( xor_ln89_reg_1017 );
    sensitive << ( icmp_ln92_fu_419_p2 );

    SC_METHOD(thread_and_ln89_4_fu_436_p2);
    sensitive << ( xor_ln89_reg_1017 );
    sensitive << ( icmp_ln84_fu_430_p2 );

    SC_METHOD(thread_and_ln89_5_fu_293_p2);
    sensitive << ( xor_ln89_fu_281_p2 );
    sensitive << ( icmp_ln83_fu_287_p2 );

    SC_METHOD(thread_and_ln89_6_fu_305_p2);
    sensitive << ( xor_ln89_fu_281_p2 );
    sensitive << ( icmp_ln82_fu_299_p2 );

    SC_METHOD(thread_and_ln89_fu_907_p2);
    sensitive << ( or_ln89_fu_883_p2 );
    sensitive << ( or_ln89_1_fu_901_p2 );

    SC_METHOD(thread_and_ln92_fu_661_p2);
    sensitive << ( select_ln83_3_fu_630_p3 );
    sensitive << ( icmp_ln92_1_fu_655_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_00001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_00001);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state9_pp0_stage1_iter3);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln80_fu_255_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_phi_mux_c_0_phi_fu_140_p4);
    sensitive << ( c_0_reg_136 );
    sensitive << ( icmp_ln80_reg_994_pp0_iter1_reg );
    sensitive << ( select_ln89_1_reg_1066 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_ap_phi_mux_h_0_phi_fu_164_p4);
    sensitive << ( h_0_reg_160 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( select_ln81_2_reg_1078 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_211_p4);
    sensitive << ( i_0_reg_207 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( select_ln83_4_reg_1106 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten117_phi_fu_129_p4);
    sensitive << ( indvar_flatten117_reg_125 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( add_ln80_reg_998 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten24_phi_fu_175_p4);
    sensitive << ( indvar_flatten24_reg_171 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( select_ln82_4_reg_1125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten63_phi_fu_152_p4);
    sensitive << ( indvar_flatten63_reg_148 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( select_ln81_5_reg_1130 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_199_p4);
    sensitive << ( indvar_flatten_reg_195 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( select_ln83_5_reg_1120 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_j_0_phi_fu_223_p4);
    sensitive << ( j_0_reg_219 );
    sensitive << ( icmp_ln80_reg_994_pp0_iter1_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( j_reg_1150 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_ap_phi_mux_w_0_phi_fu_187_p4);
    sensitive << ( w_0_reg_183 );
    sensitive << ( icmp_ln80_reg_994_pp0_iter1_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( select_ln82_2_reg_1135 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_bitcast_ln5_fu_930_p1);
    sensitive << ( max_value_1_reg_1169_pp0_iter3_reg );

    SC_METHOD(thread_bitcast_ln89_1_fu_854_p1);
    sensitive << ( input_load_reg_1162 );

    SC_METHOD(thread_bitcast_ln89_fu_837_p1);
    sensitive << ( max_value_reg_1155 );

    SC_METHOD(thread_c_fu_355_p2);
    sensitive << ( ap_phi_mux_c_0_phi_fu_140_p4 );

    SC_METHOD(thread_grp_fu_231_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( max_value_fu_828_p3 );
    sensitive << ( max_value_1_reg_1169 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_grp_fu_231_p1);
    sensitive << ( input_r_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_h_fu_311_p2);
    sensitive << ( select_ln89_fu_273_p3 );

    SC_METHOD(thread_i_fu_561_p2);
    sensitive << ( select_ln82_reg_1059 );

    SC_METHOD(thread_icmp_ln5_1_fu_953_p2);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( and_ln92_reg_1116_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( trunc_ln5_fu_943_p1 );

    SC_METHOD(thread_icmp_ln5_fu_947_p2);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( and_ln92_reg_1116_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_4_fu_933_p4 );

    SC_METHOD(thread_icmp_ln80_fu_255_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten117_phi_fu_129_p4 );

    SC_METHOD(thread_icmp_ln81_fu_267_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten63_phi_fu_152_p4 );

    SC_METHOD(thread_icmp_ln82_fu_299_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten24_phi_fu_175_p4 );

    SC_METHOD(thread_icmp_ln83_fu_287_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_199_p4 );

    SC_METHOD(thread_icmp_ln84_fu_430_p2);
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_phi_mux_j_0_phi_fu_223_p4 );

    SC_METHOD(thread_icmp_ln89_1_fu_877_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_reg_994_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( trunc_ln89_fu_850_p1 );

    SC_METHOD(thread_icmp_ln89_2_fu_889_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_reg_994_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_2_fu_857_p4 );

    SC_METHOD(thread_icmp_ln89_3_fu_895_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_reg_994_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( trunc_ln89_1_fu_867_p1 );

    SC_METHOD(thread_icmp_ln89_fu_871_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln80_reg_994_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_fu_840_p4 );

    SC_METHOD(thread_icmp_ln92_1_fu_655_p2);
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( select_ln83_fu_577_p3 );

    SC_METHOD(thread_icmp_ln92_2_fu_625_p2);
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( select_ln82_reg_1059 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_icmp_ln92_fu_419_p2);
    sensitive << ( i_0_reg_207 );
    sensitive << ( icmp_ln80_reg_994 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln89_5_fu_807_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_j_fu_812_p2);
    sensitive << ( select_ln83_reg_1089 );

    SC_METHOD(thread_max_value_1_fu_919_p3);
    sensitive << ( max_value_reg_1155 );
    sensitive << ( input_load_reg_1162 );
    sensitive << ( and_ln89_1_fu_913_p2 );

    SC_METHOD(thread_max_value_fu_828_p3);
    sensitive << ( max_value_4_fu_96 );
    sensitive << ( or_ln86_fu_823_p2 );

    SC_METHOD(thread_or_ln5_fu_959_p2);
    sensitive << ( icmp_ln5_1_fu_953_p2 );
    sensitive << ( icmp_ln5_fu_947_p2 );

    SC_METHOD(thread_or_ln81_1_fu_323_p2);
    sensitive << ( icmp_ln81_fu_267_p2 );
    sensitive << ( xor_ln81_fu_317_p2 );

    SC_METHOD(thread_or_ln81_fu_441_p2);
    sensitive << ( icmp_ln81_reg_1003 );
    sensitive << ( and_ln89_6_reg_1024 );

    SC_METHOD(thread_or_ln82_1_fu_341_p2);
    sensitive << ( icmp_ln81_fu_267_p2 );
    sensitive << ( or_ln82_fu_335_p2 );

    SC_METHOD(thread_or_ln82_fu_335_p2);
    sensitive << ( and_ln89_6_fu_305_p2 );
    sensitive << ( and_ln81_3_fu_329_p2 );

    SC_METHOD(thread_or_ln83_1_fu_571_p2);
    sensitive << ( or_ln81_fu_441_p2 );
    sensitive << ( or_ln83_fu_566_p2 );

    SC_METHOD(thread_or_ln83_fu_566_p2);
    sensitive << ( and_ln81_3_reg_1045 );
    sensitive << ( and_ln82_2_fu_555_p2 );

    SC_METHOD(thread_or_ln86_fu_823_p2);
    sensitive << ( select_ln83_1_reg_1095 );
    sensitive << ( trunc_ln84_fu_820_p1 );

    SC_METHOD(thread_or_ln89_1_fu_901_p2);
    sensitive << ( icmp_ln89_3_fu_895_p2 );
    sensitive << ( icmp_ln89_2_fu_889_p2 );

    SC_METHOD(thread_or_ln89_fu_883_p2);
    sensitive << ( icmp_ln89_1_fu_877_p2 );
    sensitive << ( icmp_ln89_fu_871_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( output_addr_reg_1140_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln5_reg_1176 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( and_ln92_reg_1116_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_p_shl1_cast_fu_740_p3);
    sensitive << ( add_ln93_1_fu_730_p2 );

    SC_METHOD(thread_p_shl_cast_fu_774_p3);
    sensitive << ( add_ln89_1_reg_1100 );

    SC_METHOD(thread_select_ln5_fu_971_p3);
    sensitive << ( max_value_1_reg_1169_pp0_iter3_reg );
    sensitive << ( and_ln5_fu_965_p2 );

    SC_METHOD(thread_select_ln81_1_fu_460_p3);
    sensitive << ( and_ln89_6_reg_1024 );
    sensitive << ( shl_ln88_mid1_fu_453_p3 );
    sensitive << ( select_ln89_2_fu_398_p3 );

    SC_METHOD(thread_select_ln81_2_fu_467_p3);
    sensitive << ( select_ln89_reg_1012 );
    sensitive << ( and_ln89_6_reg_1024 );
    sensitive << ( h_reg_1032 );

    SC_METHOD(thread_select_ln81_3_fu_480_p3);
    sensitive << ( or_ln81_fu_441_p2 );
    sensitive << ( shl_ln88_s_fu_472_p3 );

    SC_METHOD(thread_select_ln81_4_fu_493_p3);
    sensitive << ( and_ln89_6_reg_1024 );
    sensitive << ( shl_ln88_mid1_fu_453_p3 );
    sensitive << ( select_ln89_3_fu_413_p3 );

    SC_METHOD(thread_select_ln81_5_fu_700_p3);
    sensitive << ( icmp_ln81_reg_1003 );
    sensitive << ( add_ln81_1_fu_694_p2 );

    SC_METHOD(thread_select_ln81_fu_445_p3);
    sensitive << ( ap_phi_mux_w_0_phi_fu_187_p4 );
    sensitive << ( or_ln81_fu_441_p2 );

    SC_METHOD(thread_select_ln82_1_fu_524_p3);
    sensitive << ( and_ln81_3_reg_1045 );
    sensitive << ( shl_ln88_1_mid1_fu_516_p3 );
    sensitive << ( select_ln81_3_fu_480_p3 );

    SC_METHOD(thread_select_ln82_2_fu_754_p3);
    sensitive << ( and_ln81_3_reg_1045 );
    sensitive << ( select_ln81_reg_1073 );
    sensitive << ( w_reg_1084 );

    SC_METHOD(thread_select_ln82_3_fu_542_p3);
    sensitive << ( and_ln81_3_reg_1045 );
    sensitive << ( select_ln81_1_fu_460_p3 );
    sensitive << ( select_ln81_4_fu_493_p3 );

    SC_METHOD(thread_select_ln82_4_fu_686_p3);
    sensitive << ( or_ln81_fu_441_p2 );
    sensitive << ( add_ln82_1_fu_680_p2 );

    SC_METHOD(thread_select_ln82_fu_347_p3);
    sensitive << ( or_ln82_1_fu_341_p2 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_211_p4 );

    SC_METHOD(thread_select_ln83_1_fu_589_p3);
    sensitive << ( and_ln82_2_fu_555_p2 );
    sensitive << ( trunc_ln83_1_fu_585_p1 );
    sensitive << ( and_ln82_fu_536_p2 );

    SC_METHOD(thread_select_ln83_2_fu_607_p3);
    sensitive << ( and_ln82_2_fu_555_p2 );
    sensitive << ( add_ln88_2_fu_601_p2 );
    sensitive << ( select_ln82_3_fu_542_p3 );

    SC_METHOD(thread_select_ln83_3_fu_630_p3);
    sensitive << ( and_ln82_2_fu_555_p2 );
    sensitive << ( icmp_ln92_2_fu_625_p2 );
    sensitive << ( and_ln82_1_fu_549_p2 );

    SC_METHOD(thread_select_ln83_4_fu_638_p3);
    sensitive << ( select_ln82_reg_1059 );
    sensitive << ( and_ln82_2_fu_555_p2 );
    sensitive << ( i_fu_561_p2 );

    SC_METHOD(thread_select_ln83_5_fu_673_p3);
    sensitive << ( or_ln82_1_reg_1054 );
    sensitive << ( add_ln83_1_fu_667_p2 );

    SC_METHOD(thread_select_ln83_fu_577_p3);
    sensitive << ( ap_phi_mux_j_0_phi_fu_223_p4 );
    sensitive << ( or_ln83_1_fu_571_p2 );

    SC_METHOD(thread_select_ln89_1_fu_361_p3);
    sensitive << ( icmp_ln81_reg_1003 );
    sensitive << ( ap_phi_mux_c_0_phi_fu_140_p4 );
    sensitive << ( c_fu_355_p2 );

    SC_METHOD(thread_select_ln89_2_fu_398_p3);
    sensitive << ( shl_ln_reg_984 );
    sensitive << ( icmp_ln81_reg_1003 );

    SC_METHOD(thread_select_ln89_3_fu_413_p3);
    sensitive << ( add_ln88_reg_989 );
    sensitive << ( icmp_ln81_reg_1003 );

    SC_METHOD(thread_select_ln89_fu_273_p3);
    sensitive << ( icmp_ln81_fu_267_p2 );
    sensitive << ( ap_phi_mux_h_0_phi_fu_164_p4 );

    SC_METHOD(thread_shl_ln88_1_mid1_fu_516_p3);
    sensitive << ( w_fu_510_p2 );

    SC_METHOD(thread_shl_ln88_mid1_fu_453_p3);
    sensitive << ( h_reg_1032 );

    SC_METHOD(thread_shl_ln88_s_fu_472_p3);
    sensitive << ( ap_phi_mux_w_0_phi_fu_187_p4 );

    SC_METHOD(thread_shl_ln_fu_237_p3);
    sensitive << ( ap_phi_mux_h_0_phi_fu_164_p4 );

    SC_METHOD(thread_tmp_2_fu_857_p4);
    sensitive << ( bitcast_ln89_1_fu_854_p1 );

    SC_METHOD(thread_tmp_4_fu_933_p4);
    sensitive << ( bitcast_ln5_fu_930_p1 );

    SC_METHOD(thread_tmp_6_fu_368_p3);
    sensitive << ( select_ln89_1_fu_361_p3 );

    SC_METHOD(thread_tmp_7_fu_380_p3);
    sensitive << ( select_ln89_1_fu_361_p3 );

    SC_METHOD(thread_tmp_8_fu_710_p3);
    sensitive << ( select_ln89_1_reg_1066 );

    SC_METHOD(thread_tmp_9_fu_781_p3);
    sensitive << ( add_ln89_1_reg_1100 );

    SC_METHOD(thread_tmp_fu_840_p4);
    sensitive << ( bitcast_ln89_fu_837_p1 );

    SC_METHOD(thread_trunc_ln5_fu_943_p1);
    sensitive << ( bitcast_ln5_fu_930_p1 );

    SC_METHOD(thread_trunc_ln83_1_fu_585_p1);
    sensitive << ( i_fu_561_p2 );

    SC_METHOD(thread_trunc_ln83_fu_404_p1);
    sensitive << ( i_0_reg_207 );

    SC_METHOD(thread_trunc_ln84_fu_820_p1);
    sensitive << ( select_ln83_reg_1089 );

    SC_METHOD(thread_trunc_ln89_1_fu_867_p1);
    sensitive << ( bitcast_ln89_1_fu_854_p1 );

    SC_METHOD(thread_trunc_ln89_fu_850_p1);
    sensitive << ( bitcast_ln89_fu_837_p1 );

    SC_METHOD(thread_w_fu_510_p2);
    sensitive << ( select_ln81_fu_445_p3 );

    SC_METHOD(thread_xor_ln81_fu_317_p2);
    sensitive << ( icmp_ln82_fu_299_p2 );

    SC_METHOD(thread_xor_ln82_fu_531_p2);
    sensitive << ( and_ln81_3_reg_1045 );

    SC_METHOD(thread_xor_ln89_fu_281_p2);
    sensitive << ( icmp_ln81_fu_267_p2 );

    SC_METHOD(thread_zext_ln81_fu_727_p1);
    sensitive << ( select_ln81_2_reg_1078 );

    SC_METHOD(thread_zext_ln82_fu_759_p1);
    sensitive << ( select_ln82_2_fu_754_p3 );

    SC_METHOD(thread_zext_ln83_1_fu_597_p1);
    sensitive << ( i_fu_561_p2 );

    SC_METHOD(thread_zext_ln83_2_fu_615_p1);
    sensitive << ( select_ln83_2_fu_607_p3 );

    SC_METHOD(thread_zext_ln83_fu_245_p1);
    sensitive << ( ap_phi_mux_i_0_phi_fu_211_p4 );

    SC_METHOD(thread_zext_ln84_fu_645_p1);
    sensitive << ( select_ln83_fu_577_p3 );

    SC_METHOD(thread_zext_ln89_1_fu_376_p1);
    sensitive << ( tmp_6_fu_368_p3 );

    SC_METHOD(thread_zext_ln89_2_fu_388_p1);
    sensitive << ( tmp_7_fu_380_p3 );

    SC_METHOD(thread_zext_ln89_3_fu_788_p1);
    sensitive << ( tmp_9_fu_781_p3 );

    SC_METHOD(thread_zext_ln89_4_fu_798_p1);
    sensitive << ( add_ln88_1_reg_1111 );

    SC_METHOD(thread_zext_ln89_5_fu_807_p1);
    sensitive << ( add_ln89_3_fu_801_p2 );

    SC_METHOD(thread_zext_ln89_fu_707_p1);
    sensitive << ( select_ln89_1_reg_1066 );

    SC_METHOD(thread_zext_ln93_1_fu_736_p1);
    sensitive << ( add_ln93_1_fu_730_p2 );

    SC_METHOD(thread_zext_ln93_2_fu_769_p1);
    sensitive << ( add_ln93_3_fu_763_p2 );

    SC_METHOD(thread_zext_ln93_fu_717_p1);
    sensitive << ( tmp_8_fu_710_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln80_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pooling4_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten117_reg_125, "indvar_flatten117_reg_125");
    sc_trace(mVcdFile, c_0_reg_136, "c_0_reg_136");
    sc_trace(mVcdFile, indvar_flatten63_reg_148, "indvar_flatten63_reg_148");
    sc_trace(mVcdFile, h_0_reg_160, "h_0_reg_160");
    sc_trace(mVcdFile, indvar_flatten24_reg_171, "indvar_flatten24_reg_171");
    sc_trace(mVcdFile, w_0_reg_183, "w_0_reg_183");
    sc_trace(mVcdFile, indvar_flatten_reg_195, "indvar_flatten_reg_195");
    sc_trace(mVcdFile, i_0_reg_207, "i_0_reg_207");
    sc_trace(mVcdFile, j_0_reg_219, "j_0_reg_219");
    sc_trace(mVcdFile, shl_ln_fu_237_p3, "shl_ln_fu_237_p3");
    sc_trace(mVcdFile, shl_ln_reg_984, "shl_ln_reg_984");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter2, "ap_block_state6_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter3, "ap_block_state8_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter4, "ap_block_state10_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln88_fu_249_p2, "add_ln88_fu_249_p2");
    sc_trace(mVcdFile, add_ln88_reg_989, "add_ln88_reg_989");
    sc_trace(mVcdFile, icmp_ln80_fu_255_p2, "icmp_ln80_fu_255_p2");
    sc_trace(mVcdFile, icmp_ln80_reg_994, "icmp_ln80_reg_994");
    sc_trace(mVcdFile, icmp_ln80_reg_994_pp0_iter1_reg, "icmp_ln80_reg_994_pp0_iter1_reg");
    sc_trace(mVcdFile, add_ln80_fu_261_p2, "add_ln80_fu_261_p2");
    sc_trace(mVcdFile, add_ln80_reg_998, "add_ln80_reg_998");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, icmp_ln81_fu_267_p2, "icmp_ln81_fu_267_p2");
    sc_trace(mVcdFile, icmp_ln81_reg_1003, "icmp_ln81_reg_1003");
    sc_trace(mVcdFile, select_ln89_fu_273_p3, "select_ln89_fu_273_p3");
    sc_trace(mVcdFile, select_ln89_reg_1012, "select_ln89_reg_1012");
    sc_trace(mVcdFile, xor_ln89_fu_281_p2, "xor_ln89_fu_281_p2");
    sc_trace(mVcdFile, xor_ln89_reg_1017, "xor_ln89_reg_1017");
    sc_trace(mVcdFile, and_ln89_6_fu_305_p2, "and_ln89_6_fu_305_p2");
    sc_trace(mVcdFile, and_ln89_6_reg_1024, "and_ln89_6_reg_1024");
    sc_trace(mVcdFile, h_fu_311_p2, "h_fu_311_p2");
    sc_trace(mVcdFile, h_reg_1032, "h_reg_1032");
    sc_trace(mVcdFile, or_ln81_1_fu_323_p2, "or_ln81_1_fu_323_p2");
    sc_trace(mVcdFile, or_ln81_1_reg_1038, "or_ln81_1_reg_1038");
    sc_trace(mVcdFile, and_ln81_3_fu_329_p2, "and_ln81_3_fu_329_p2");
    sc_trace(mVcdFile, and_ln81_3_reg_1045, "and_ln81_3_reg_1045");
    sc_trace(mVcdFile, or_ln82_1_fu_341_p2, "or_ln82_1_fu_341_p2");
    sc_trace(mVcdFile, or_ln82_1_reg_1054, "or_ln82_1_reg_1054");
    sc_trace(mVcdFile, select_ln82_fu_347_p3, "select_ln82_fu_347_p3");
    sc_trace(mVcdFile, select_ln82_reg_1059, "select_ln82_reg_1059");
    sc_trace(mVcdFile, select_ln89_1_fu_361_p3, "select_ln89_1_fu_361_p3");
    sc_trace(mVcdFile, select_ln89_1_reg_1066, "select_ln89_1_reg_1066");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter1, "ap_block_state5_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter2, "ap_block_state7_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage1_iter3, "ap_block_state9_pp0_stage1_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, select_ln81_fu_445_p3, "select_ln81_fu_445_p3");
    sc_trace(mVcdFile, select_ln81_reg_1073, "select_ln81_reg_1073");
    sc_trace(mVcdFile, select_ln81_2_fu_467_p3, "select_ln81_2_fu_467_p3");
    sc_trace(mVcdFile, select_ln81_2_reg_1078, "select_ln81_2_reg_1078");
    sc_trace(mVcdFile, w_fu_510_p2, "w_fu_510_p2");
    sc_trace(mVcdFile, w_reg_1084, "w_reg_1084");
    sc_trace(mVcdFile, select_ln83_fu_577_p3, "select_ln83_fu_577_p3");
    sc_trace(mVcdFile, select_ln83_reg_1089, "select_ln83_reg_1089");
    sc_trace(mVcdFile, select_ln83_1_fu_589_p3, "select_ln83_1_fu_589_p3");
    sc_trace(mVcdFile, select_ln83_1_reg_1095, "select_ln83_1_reg_1095");
    sc_trace(mVcdFile, add_ln89_1_fu_619_p2, "add_ln89_1_fu_619_p2");
    sc_trace(mVcdFile, add_ln89_1_reg_1100, "add_ln89_1_reg_1100");
    sc_trace(mVcdFile, select_ln83_4_fu_638_p3, "select_ln83_4_fu_638_p3");
    sc_trace(mVcdFile, select_ln83_4_reg_1106, "select_ln83_4_reg_1106");
    sc_trace(mVcdFile, add_ln88_1_fu_649_p2, "add_ln88_1_fu_649_p2");
    sc_trace(mVcdFile, add_ln88_1_reg_1111, "add_ln88_1_reg_1111");
    sc_trace(mVcdFile, and_ln92_fu_661_p2, "and_ln92_fu_661_p2");
    sc_trace(mVcdFile, and_ln92_reg_1116, "and_ln92_reg_1116");
    sc_trace(mVcdFile, and_ln92_reg_1116_pp0_iter1_reg, "and_ln92_reg_1116_pp0_iter1_reg");
    sc_trace(mVcdFile, and_ln92_reg_1116_pp0_iter2_reg, "and_ln92_reg_1116_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln92_reg_1116_pp0_iter3_reg, "and_ln92_reg_1116_pp0_iter3_reg");
    sc_trace(mVcdFile, select_ln83_5_fu_673_p3, "select_ln83_5_fu_673_p3");
    sc_trace(mVcdFile, select_ln83_5_reg_1120, "select_ln83_5_reg_1120");
    sc_trace(mVcdFile, select_ln82_4_fu_686_p3, "select_ln82_4_fu_686_p3");
    sc_trace(mVcdFile, select_ln82_4_reg_1125, "select_ln82_4_reg_1125");
    sc_trace(mVcdFile, select_ln81_5_fu_700_p3, "select_ln81_5_fu_700_p3");
    sc_trace(mVcdFile, select_ln81_5_reg_1130, "select_ln81_5_reg_1130");
    sc_trace(mVcdFile, select_ln82_2_fu_754_p3, "select_ln82_2_fu_754_p3");
    sc_trace(mVcdFile, select_ln82_2_reg_1135, "select_ln82_2_reg_1135");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, output_addr_reg_1140, "output_addr_reg_1140");
    sc_trace(mVcdFile, output_addr_reg_1140_pp0_iter2_reg, "output_addr_reg_1140_pp0_iter2_reg");
    sc_trace(mVcdFile, output_addr_reg_1140_pp0_iter3_reg, "output_addr_reg_1140_pp0_iter3_reg");
    sc_trace(mVcdFile, j_fu_812_p2, "j_fu_812_p2");
    sc_trace(mVcdFile, j_reg_1150, "j_reg_1150");
    sc_trace(mVcdFile, max_value_fu_828_p3, "max_value_fu_828_p3");
    sc_trace(mVcdFile, max_value_reg_1155, "max_value_reg_1155");
    sc_trace(mVcdFile, input_load_reg_1162, "input_load_reg_1162");
    sc_trace(mVcdFile, max_value_1_fu_919_p3, "max_value_1_fu_919_p3");
    sc_trace(mVcdFile, max_value_1_reg_1169, "max_value_1_reg_1169");
    sc_trace(mVcdFile, max_value_1_reg_1169_pp0_iter3_reg, "max_value_1_reg_1169_pp0_iter3_reg");
    sc_trace(mVcdFile, select_ln5_fu_971_p3, "select_ln5_fu_971_p3");
    sc_trace(mVcdFile, select_ln5_reg_1176, "select_ln5_reg_1176");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten117_phi_fu_129_p4, "ap_phi_mux_indvar_flatten117_phi_fu_129_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_c_0_phi_fu_140_p4, "ap_phi_mux_c_0_phi_fu_140_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten63_phi_fu_152_p4, "ap_phi_mux_indvar_flatten63_phi_fu_152_p4");
    sc_trace(mVcdFile, ap_phi_mux_h_0_phi_fu_164_p4, "ap_phi_mux_h_0_phi_fu_164_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten24_phi_fu_175_p4, "ap_phi_mux_indvar_flatten24_phi_fu_175_p4");
    sc_trace(mVcdFile, ap_phi_mux_w_0_phi_fu_187_p4, "ap_phi_mux_w_0_phi_fu_187_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_199_p4, "ap_phi_mux_indvar_flatten_phi_fu_199_p4");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_211_p4, "ap_phi_mux_i_0_phi_fu_211_p4");
    sc_trace(mVcdFile, ap_phi_mux_j_0_phi_fu_223_p4, "ap_phi_mux_j_0_phi_fu_223_p4");
    sc_trace(mVcdFile, zext_ln93_2_fu_769_p1, "zext_ln93_2_fu_769_p1");
    sc_trace(mVcdFile, zext_ln89_5_fu_807_p1, "zext_ln89_5_fu_807_p1");
    sc_trace(mVcdFile, max_value_4_fu_96, "max_value_4_fu_96");
    sc_trace(mVcdFile, grp_fu_231_p0, "grp_fu_231_p0");
    sc_trace(mVcdFile, grp_fu_231_p1, "grp_fu_231_p1");
    sc_trace(mVcdFile, zext_ln83_fu_245_p1, "zext_ln83_fu_245_p1");
    sc_trace(mVcdFile, icmp_ln83_fu_287_p2, "icmp_ln83_fu_287_p2");
    sc_trace(mVcdFile, icmp_ln82_fu_299_p2, "icmp_ln82_fu_299_p2");
    sc_trace(mVcdFile, xor_ln81_fu_317_p2, "xor_ln81_fu_317_p2");
    sc_trace(mVcdFile, and_ln89_5_fu_293_p2, "and_ln89_5_fu_293_p2");
    sc_trace(mVcdFile, or_ln82_fu_335_p2, "or_ln82_fu_335_p2");
    sc_trace(mVcdFile, c_fu_355_p2, "c_fu_355_p2");
    sc_trace(mVcdFile, tmp_6_fu_368_p3, "tmp_6_fu_368_p3");
    sc_trace(mVcdFile, tmp_7_fu_380_p3, "tmp_7_fu_380_p3");
    sc_trace(mVcdFile, zext_ln89_2_fu_388_p1, "zext_ln89_2_fu_388_p1");
    sc_trace(mVcdFile, zext_ln89_1_fu_376_p1, "zext_ln89_1_fu_376_p1");
    sc_trace(mVcdFile, trunc_ln83_fu_404_p1, "trunc_ln83_fu_404_p1");
    sc_trace(mVcdFile, icmp_ln92_fu_419_p2, "icmp_ln92_fu_419_p2");
    sc_trace(mVcdFile, icmp_ln84_fu_430_p2, "icmp_ln84_fu_430_p2");
    sc_trace(mVcdFile, or_ln81_fu_441_p2, "or_ln81_fu_441_p2");
    sc_trace(mVcdFile, shl_ln88_mid1_fu_453_p3, "shl_ln88_mid1_fu_453_p3");
    sc_trace(mVcdFile, select_ln89_2_fu_398_p3, "select_ln89_2_fu_398_p3");
    sc_trace(mVcdFile, shl_ln88_s_fu_472_p3, "shl_ln88_s_fu_472_p3");
    sc_trace(mVcdFile, and_ln89_2_fu_408_p2, "and_ln89_2_fu_408_p2");
    sc_trace(mVcdFile, select_ln89_3_fu_413_p3, "select_ln89_3_fu_413_p3");
    sc_trace(mVcdFile, and_ln89_3_fu_425_p2, "and_ln89_3_fu_425_p2");
    sc_trace(mVcdFile, and_ln89_4_fu_436_p2, "and_ln89_4_fu_436_p2");
    sc_trace(mVcdFile, shl_ln88_1_mid1_fu_516_p3, "shl_ln88_1_mid1_fu_516_p3");
    sc_trace(mVcdFile, select_ln81_3_fu_480_p3, "select_ln81_3_fu_480_p3");
    sc_trace(mVcdFile, and_ln81_fu_488_p2, "and_ln81_fu_488_p2");
    sc_trace(mVcdFile, xor_ln82_fu_531_p2, "xor_ln82_fu_531_p2");
    sc_trace(mVcdFile, select_ln81_1_fu_460_p3, "select_ln81_1_fu_460_p3");
    sc_trace(mVcdFile, select_ln81_4_fu_493_p3, "select_ln81_4_fu_493_p3");
    sc_trace(mVcdFile, and_ln81_1_fu_500_p2, "and_ln81_1_fu_500_p2");
    sc_trace(mVcdFile, and_ln81_2_fu_505_p2, "and_ln81_2_fu_505_p2");
    sc_trace(mVcdFile, and_ln82_2_fu_555_p2, "and_ln82_2_fu_555_p2");
    sc_trace(mVcdFile, or_ln83_fu_566_p2, "or_ln83_fu_566_p2");
    sc_trace(mVcdFile, or_ln83_1_fu_571_p2, "or_ln83_1_fu_571_p2");
    sc_trace(mVcdFile, i_fu_561_p2, "i_fu_561_p2");
    sc_trace(mVcdFile, trunc_ln83_1_fu_585_p1, "trunc_ln83_1_fu_585_p1");
    sc_trace(mVcdFile, and_ln82_fu_536_p2, "and_ln82_fu_536_p2");
    sc_trace(mVcdFile, zext_ln83_1_fu_597_p1, "zext_ln83_1_fu_597_p1");
    sc_trace(mVcdFile, add_ln88_2_fu_601_p2, "add_ln88_2_fu_601_p2");
    sc_trace(mVcdFile, select_ln82_3_fu_542_p3, "select_ln82_3_fu_542_p3");
    sc_trace(mVcdFile, select_ln83_2_fu_607_p3, "select_ln83_2_fu_607_p3");
    sc_trace(mVcdFile, add_ln89_fu_392_p2, "add_ln89_fu_392_p2");
    sc_trace(mVcdFile, zext_ln83_2_fu_615_p1, "zext_ln83_2_fu_615_p1");
    sc_trace(mVcdFile, icmp_ln92_2_fu_625_p2, "icmp_ln92_2_fu_625_p2");
    sc_trace(mVcdFile, and_ln82_1_fu_549_p2, "and_ln82_1_fu_549_p2");
    sc_trace(mVcdFile, zext_ln84_fu_645_p1, "zext_ln84_fu_645_p1");
    sc_trace(mVcdFile, select_ln82_1_fu_524_p3, "select_ln82_1_fu_524_p3");
    sc_trace(mVcdFile, select_ln83_3_fu_630_p3, "select_ln83_3_fu_630_p3");
    sc_trace(mVcdFile, icmp_ln92_1_fu_655_p2, "icmp_ln92_1_fu_655_p2");
    sc_trace(mVcdFile, add_ln83_1_fu_667_p2, "add_ln83_1_fu_667_p2");
    sc_trace(mVcdFile, add_ln82_1_fu_680_p2, "add_ln82_1_fu_680_p2");
    sc_trace(mVcdFile, add_ln81_1_fu_694_p2, "add_ln81_1_fu_694_p2");
    sc_trace(mVcdFile, tmp_8_fu_710_p3, "tmp_8_fu_710_p3");
    sc_trace(mVcdFile, zext_ln89_fu_707_p1, "zext_ln89_fu_707_p1");
    sc_trace(mVcdFile, zext_ln93_fu_717_p1, "zext_ln93_fu_717_p1");
    sc_trace(mVcdFile, add_ln93_fu_721_p2, "add_ln93_fu_721_p2");
    sc_trace(mVcdFile, zext_ln81_fu_727_p1, "zext_ln81_fu_727_p1");
    sc_trace(mVcdFile, add_ln93_1_fu_730_p2, "add_ln93_1_fu_730_p2");
    sc_trace(mVcdFile, zext_ln93_1_fu_736_p1, "zext_ln93_1_fu_736_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_740_p3, "p_shl1_cast_fu_740_p3");
    sc_trace(mVcdFile, add_ln93_2_fu_748_p2, "add_ln93_2_fu_748_p2");
    sc_trace(mVcdFile, zext_ln82_fu_759_p1, "zext_ln82_fu_759_p1");
    sc_trace(mVcdFile, add_ln93_3_fu_763_p2, "add_ln93_3_fu_763_p2");
    sc_trace(mVcdFile, tmp_9_fu_781_p3, "tmp_9_fu_781_p3");
    sc_trace(mVcdFile, zext_ln89_3_fu_788_p1, "zext_ln89_3_fu_788_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_774_p3, "p_shl_cast_fu_774_p3");
    sc_trace(mVcdFile, add_ln89_2_fu_792_p2, "add_ln89_2_fu_792_p2");
    sc_trace(mVcdFile, zext_ln89_4_fu_798_p1, "zext_ln89_4_fu_798_p1");
    sc_trace(mVcdFile, add_ln89_3_fu_801_p2, "add_ln89_3_fu_801_p2");
    sc_trace(mVcdFile, trunc_ln84_fu_820_p1, "trunc_ln84_fu_820_p1");
    sc_trace(mVcdFile, or_ln86_fu_823_p2, "or_ln86_fu_823_p2");
    sc_trace(mVcdFile, bitcast_ln89_fu_837_p1, "bitcast_ln89_fu_837_p1");
    sc_trace(mVcdFile, bitcast_ln89_1_fu_854_p1, "bitcast_ln89_1_fu_854_p1");
    sc_trace(mVcdFile, tmp_fu_840_p4, "tmp_fu_840_p4");
    sc_trace(mVcdFile, trunc_ln89_fu_850_p1, "trunc_ln89_fu_850_p1");
    sc_trace(mVcdFile, icmp_ln89_1_fu_877_p2, "icmp_ln89_1_fu_877_p2");
    sc_trace(mVcdFile, icmp_ln89_fu_871_p2, "icmp_ln89_fu_871_p2");
    sc_trace(mVcdFile, tmp_2_fu_857_p4, "tmp_2_fu_857_p4");
    sc_trace(mVcdFile, trunc_ln89_1_fu_867_p1, "trunc_ln89_1_fu_867_p1");
    sc_trace(mVcdFile, icmp_ln89_3_fu_895_p2, "icmp_ln89_3_fu_895_p2");
    sc_trace(mVcdFile, icmp_ln89_2_fu_889_p2, "icmp_ln89_2_fu_889_p2");
    sc_trace(mVcdFile, or_ln89_fu_883_p2, "or_ln89_fu_883_p2");
    sc_trace(mVcdFile, or_ln89_1_fu_901_p2, "or_ln89_1_fu_901_p2");
    sc_trace(mVcdFile, and_ln89_fu_907_p2, "and_ln89_fu_907_p2");
    sc_trace(mVcdFile, grp_fu_231_p2, "grp_fu_231_p2");
    sc_trace(mVcdFile, and_ln89_1_fu_913_p2, "and_ln89_1_fu_913_p2");
    sc_trace(mVcdFile, bitcast_ln5_fu_930_p1, "bitcast_ln5_fu_930_p1");
    sc_trace(mVcdFile, tmp_4_fu_933_p4, "tmp_4_fu_933_p4");
    sc_trace(mVcdFile, trunc_ln5_fu_943_p1, "trunc_ln5_fu_943_p1");
    sc_trace(mVcdFile, icmp_ln5_1_fu_953_p2, "icmp_ln5_1_fu_953_p2");
    sc_trace(mVcdFile, icmp_ln5_fu_947_p2, "icmp_ln5_fu_947_p2");
    sc_trace(mVcdFile, or_ln5_fu_959_p2, "or_ln5_fu_959_p2");
    sc_trace(mVcdFile, and_ln5_fu_965_p2, "and_ln5_fu_965_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_00001, "ap_block_pp0_stage1_00001");
    sc_trace(mVcdFile, ap_block_pp0_stage0_00001, "ap_block_pp0_stage0_00001");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

max_pooling4::~max_pooling4() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete lenet_cnn_fcmp_32dEe_U26;
}

void max_pooling4::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void max_pooling4::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv5_2;
}

void max_pooling4::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        c_0_reg_136 = select_ln89_1_reg_1066.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_0_reg_136 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        h_0_reg_160 = select_ln81_2_reg_1078.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        h_0_reg_160 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_0_reg_207 = select_ln83_4_reg_1106.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_207 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten117_reg_125 = add_ln80_reg_998.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten117_reg_125 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten24_reg_171 = select_ln82_4_reg_1125.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten24_reg_171 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten63_reg_148 = select_ln81_5_reg_1130.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten63_reg_148 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_195 = select_ln83_5_reg_1120.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_195 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        j_0_reg_219 = j_reg_1150.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_reg_219 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        w_0_reg_183 = select_ln82_2_reg_1135.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        w_0_reg_183 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        add_ln80_reg_998 = add_ln80_fu_261_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0))) {
        add_ln88_1_reg_1111 = add_ln88_1_fu_649_p2.read();
        add_ln89_1_reg_1100 = add_ln89_1_fu_619_p2.read();
        and_ln92_reg_1116 = and_ln92_fu_661_p2.read();
        select_ln81_reg_1073 = select_ln81_fu_445_p3.read();
        select_ln83_1_reg_1095 = select_ln83_1_fu_589_p3.read();
        select_ln83_reg_1089 = select_ln83_fu_577_p3.read();
        w_reg_1084 = w_fu_510_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln88_reg_989 = add_ln88_fu_249_p2.read();
        icmp_ln80_reg_994 = icmp_ln80_fu_255_p2.read();
        icmp_ln80_reg_994_pp0_iter1_reg = icmp_ln80_reg_994.read();
        max_value_1_reg_1169_pp0_iter3_reg = max_value_1_reg_1169.read();
        output_addr_reg_1140_pp0_iter2_reg = output_addr_reg_1140.read();
        output_addr_reg_1140_pp0_iter3_reg = output_addr_reg_1140_pp0_iter2_reg.read();
        shl_ln_reg_984 = shl_ln_fu_237_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_fu_255_p2.read(), ap_const_lv1_0))) {
        and_ln81_3_reg_1045 = and_ln81_3_fu_329_p2.read();
        and_ln89_6_reg_1024 = and_ln89_6_fu_305_p2.read();
        h_reg_1032 = h_fu_311_p2.read();
        icmp_ln81_reg_1003 = icmp_ln81_fu_267_p2.read();
        or_ln81_1_reg_1038 = or_ln81_1_fu_323_p2.read();
        or_ln82_1_reg_1054 = or_ln82_1_fu_341_p2.read();
        select_ln82_reg_1059 = select_ln82_fu_347_p3.read();
        select_ln89_reg_1012 = select_ln89_fu_273_p3.read();
        xor_ln89_reg_1017 = xor_ln89_fu_281_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        and_ln92_reg_1116_pp0_iter1_reg = and_ln92_reg_1116.read();
        and_ln92_reg_1116_pp0_iter2_reg = and_ln92_reg_1116_pp0_iter1_reg.read();
        and_ln92_reg_1116_pp0_iter3_reg = and_ln92_reg_1116_pp0_iter2_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        input_load_reg_1162 = input_r_q0.read();
        max_value_reg_1155 = max_value_fu_828_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        j_reg_1150 = j_fu_812_p2.read();
        select_ln82_2_reg_1135 = select_ln82_2_fu_754_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        max_value_1_reg_1169 = max_value_1_fu_919_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        max_value_4_fu_96 = max_value_1_fu_919_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0))) {
        output_addr_reg_1140 =  (sc_lv<9>) (zext_ln93_2_fu_769_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(and_ln92_reg_1116_pp0_iter2_reg.read(), ap_const_lv1_1))) {
        select_ln5_reg_1176 = select_ln5_fu_971_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0))) {
        select_ln81_2_reg_1078 = select_ln81_2_fu_467_p3.read();
        select_ln81_5_reg_1130 = select_ln81_5_fu_700_p3.read();
        select_ln82_4_reg_1125 = select_ln82_4_fu_686_p3.read();
        select_ln83_4_reg_1106 = select_ln83_4_fu_638_p3.read();
        select_ln83_5_reg_1120 = select_ln83_5_fu_673_p3.read();
        select_ln89_1_reg_1066 = select_ln89_1_fu_361_p3.read();
    }
}

void max_pooling4::thread_add_ln80_fu_261_p2() {
    add_ln80_fu_261_p2 = (!ap_phi_mux_indvar_flatten117_phi_fu_129_p4.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(ap_phi_mux_indvar_flatten117_phi_fu_129_p4.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void max_pooling4::thread_add_ln81_1_fu_694_p2() {
    add_ln81_1_fu_694_p2 = (!indvar_flatten63_reg_148.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(indvar_flatten63_reg_148.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void max_pooling4::thread_add_ln82_1_fu_680_p2() {
    add_ln82_1_fu_680_p2 = (!indvar_flatten24_reg_171.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten24_reg_171.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void max_pooling4::thread_add_ln83_1_fu_667_p2() {
    add_ln83_1_fu_667_p2 = (!indvar_flatten_reg_195.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(indvar_flatten_reg_195.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void max_pooling4::thread_add_ln88_1_fu_649_p2() {
    add_ln88_1_fu_649_p2 = (!zext_ln84_fu_645_p1.read().is_01() || !select_ln82_1_fu_524_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln84_fu_645_p1.read()) + sc_biguint<4>(select_ln82_1_fu_524_p3.read()));
}

void max_pooling4::thread_add_ln88_2_fu_601_p2() {
    add_ln88_2_fu_601_p2 = (!zext_ln83_1_fu_597_p1.read().is_01() || !select_ln81_1_fu_460_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln83_1_fu_597_p1.read()) + sc_biguint<4>(select_ln81_1_fu_460_p3.read()));
}

void max_pooling4::thread_add_ln88_fu_249_p2() {
    add_ln88_fu_249_p2 = (!shl_ln_fu_237_p3.read().is_01() || !zext_ln83_fu_245_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(shl_ln_fu_237_p3.read()) + sc_biguint<4>(zext_ln83_fu_245_p1.read()));
}

void max_pooling4::thread_add_ln89_1_fu_619_p2() {
    add_ln89_1_fu_619_p2 = (!add_ln89_fu_392_p2.read().is_01() || !zext_ln83_2_fu_615_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(add_ln89_fu_392_p2.read()) + sc_biguint<9>(zext_ln83_2_fu_615_p1.read()));
}

void max_pooling4::thread_add_ln89_2_fu_792_p2() {
    add_ln89_2_fu_792_p2 = (!zext_ln89_3_fu_788_p1.read().is_01() || !p_shl_cast_fu_774_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln89_3_fu_788_p1.read()) + sc_biguint<12>(p_shl_cast_fu_774_p3.read()));
}

void max_pooling4::thread_add_ln89_3_fu_801_p2() {
    add_ln89_3_fu_801_p2 = (!add_ln89_2_fu_792_p2.read().is_01() || !zext_ln89_4_fu_798_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(add_ln89_2_fu_792_p2.read()) + sc_biguint<12>(zext_ln89_4_fu_798_p1.read()));
}

void max_pooling4::thread_add_ln89_fu_392_p2() {
    add_ln89_fu_392_p2 = (!zext_ln89_2_fu_388_p1.read().is_01() || !zext_ln89_1_fu_376_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln89_2_fu_388_p1.read()) + sc_biguint<9>(zext_ln89_1_fu_376_p1.read()));
}

void max_pooling4::thread_add_ln93_1_fu_730_p2() {
    add_ln93_1_fu_730_p2 = (!add_ln93_fu_721_p2.read().is_01() || !zext_ln81_fu_727_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln93_fu_721_p2.read()) + sc_biguint<8>(zext_ln81_fu_727_p1.read()));
}

void max_pooling4::thread_add_ln93_2_fu_748_p2() {
    add_ln93_2_fu_748_p2 = (!zext_ln93_1_fu_736_p1.read().is_01() || !p_shl1_cast_fu_740_p3.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln93_1_fu_736_p1.read()) + sc_biguint<10>(p_shl1_cast_fu_740_p3.read()));
}

void max_pooling4::thread_add_ln93_3_fu_763_p2() {
    add_ln93_3_fu_763_p2 = (!add_ln93_2_fu_748_p2.read().is_01() || !zext_ln82_fu_759_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln93_2_fu_748_p2.read()) + sc_biguint<10>(zext_ln82_fu_759_p1.read()));
}

void max_pooling4::thread_add_ln93_fu_721_p2() {
    add_ln93_fu_721_p2 = (!zext_ln89_fu_707_p1.read().is_01() || !zext_ln93_fu_717_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln89_fu_707_p1.read()) + sc_biguint<8>(zext_ln93_fu_717_p1.read()));
}

void max_pooling4::thread_and_ln5_fu_965_p2() {
    and_ln5_fu_965_p2 = (or_ln5_fu_959_p2.read() & grp_fu_231_p2.read());
}

void max_pooling4::thread_and_ln81_1_fu_500_p2() {
    and_ln81_1_fu_500_p2 = (and_ln89_3_fu_425_p2.read() & or_ln81_1_reg_1038.read());
}

void max_pooling4::thread_and_ln81_2_fu_505_p2() {
    and_ln81_2_fu_505_p2 = (and_ln89_4_fu_436_p2.read() & or_ln81_1_reg_1038.read());
}

void max_pooling4::thread_and_ln81_3_fu_329_p2() {
    and_ln81_3_fu_329_p2 = (and_ln89_5_fu_293_p2.read() & or_ln81_1_fu_323_p2.read());
}

void max_pooling4::thread_and_ln81_fu_488_p2() {
    and_ln81_fu_488_p2 = (and_ln89_2_fu_408_p2.read() & or_ln81_1_reg_1038.read());
}

void max_pooling4::thread_and_ln82_1_fu_549_p2() {
    and_ln82_1_fu_549_p2 = (and_ln81_1_fu_500_p2.read() & xor_ln82_fu_531_p2.read());
}

void max_pooling4::thread_and_ln82_2_fu_555_p2() {
    and_ln82_2_fu_555_p2 = (and_ln81_2_fu_505_p2.read() & xor_ln82_fu_531_p2.read());
}

void max_pooling4::thread_and_ln82_fu_536_p2() {
    and_ln82_fu_536_p2 = (and_ln81_fu_488_p2.read() & xor_ln82_fu_531_p2.read());
}

void max_pooling4::thread_and_ln89_1_fu_913_p2() {
    and_ln89_1_fu_913_p2 = (and_ln89_fu_907_p2.read() & grp_fu_231_p2.read());
}

void max_pooling4::thread_and_ln89_2_fu_408_p2() {
    and_ln89_2_fu_408_p2 = (trunc_ln83_fu_404_p1.read() & xor_ln89_reg_1017.read());
}

void max_pooling4::thread_and_ln89_3_fu_425_p2() {
    and_ln89_3_fu_425_p2 = (icmp_ln92_fu_419_p2.read() & xor_ln89_reg_1017.read());
}

void max_pooling4::thread_and_ln89_4_fu_436_p2() {
    and_ln89_4_fu_436_p2 = (icmp_ln84_fu_430_p2.read() & xor_ln89_reg_1017.read());
}

void max_pooling4::thread_and_ln89_5_fu_293_p2() {
    and_ln89_5_fu_293_p2 = (icmp_ln83_fu_287_p2.read() & xor_ln89_fu_281_p2.read());
}

void max_pooling4::thread_and_ln89_6_fu_305_p2() {
    and_ln89_6_fu_305_p2 = (icmp_ln82_fu_299_p2.read() & xor_ln89_fu_281_p2.read());
}

void max_pooling4::thread_and_ln89_fu_907_p2() {
    and_ln89_fu_907_p2 = (or_ln89_fu_883_p2.read() & or_ln89_1_fu_901_p2.read());
}

void max_pooling4::thread_and_ln92_fu_661_p2() {
    and_ln92_fu_661_p2 = (select_ln83_3_fu_630_p3.read() & icmp_ln92_1_fu_655_p2.read());
}

void max_pooling4::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void max_pooling4::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void max_pooling4::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pooling4::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[3];
}

void max_pooling4::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_pp0_stage0_00001() {
    ap_block_pp0_stage0_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_pp0_stage1_00001() {
    ap_block_pp0_stage1_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state10_pp0_stage0_iter4() {
    ap_block_state10_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state5_pp0_stage1_iter1() {
    ap_block_state5_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state6_pp0_stage0_iter2() {
    ap_block_state6_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state7_pp0_stage1_iter2() {
    ap_block_state7_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state8_pp0_stage0_iter3() {
    ap_block_state8_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_block_state9_pp0_stage1_iter3() {
    ap_block_state9_pp0_stage1_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling4::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln80_fu_255_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void max_pooling4::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void max_pooling4::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void max_pooling4::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pooling4::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void max_pooling4::thread_ap_phi_mux_c_0_phi_fu_140_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        ap_phi_mux_c_0_phi_fu_140_p4 = select_ln89_1_reg_1066.read();
    } else {
        ap_phi_mux_c_0_phi_fu_140_p4 = c_0_reg_136.read();
    }
}

void max_pooling4::thread_ap_phi_mux_h_0_phi_fu_164_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_h_0_phi_fu_164_p4 = select_ln81_2_reg_1078.read();
    } else {
        ap_phi_mux_h_0_phi_fu_164_p4 = h_0_reg_160.read();
    }
}

void max_pooling4::thread_ap_phi_mux_i_0_phi_fu_211_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_0_phi_fu_211_p4 = select_ln83_4_reg_1106.read();
    } else {
        ap_phi_mux_i_0_phi_fu_211_p4 = i_0_reg_207.read();
    }
}

void max_pooling4::thread_ap_phi_mux_indvar_flatten117_phi_fu_129_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten117_phi_fu_129_p4 = add_ln80_reg_998.read();
    } else {
        ap_phi_mux_indvar_flatten117_phi_fu_129_p4 = indvar_flatten117_reg_125.read();
    }
}

void max_pooling4::thread_ap_phi_mux_indvar_flatten24_phi_fu_175_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten24_phi_fu_175_p4 = select_ln82_4_reg_1125.read();
    } else {
        ap_phi_mux_indvar_flatten24_phi_fu_175_p4 = indvar_flatten24_reg_171.read();
    }
}

void max_pooling4::thread_ap_phi_mux_indvar_flatten63_phi_fu_152_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten63_phi_fu_152_p4 = select_ln81_5_reg_1130.read();
    } else {
        ap_phi_mux_indvar_flatten63_phi_fu_152_p4 = indvar_flatten63_reg_148.read();
    }
}

void max_pooling4::thread_ap_phi_mux_indvar_flatten_phi_fu_199_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_199_p4 = select_ln83_5_reg_1120.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_199_p4 = indvar_flatten_reg_195.read();
    }
}

void max_pooling4::thread_ap_phi_mux_j_0_phi_fu_223_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_0_phi_fu_223_p4 = j_reg_1150.read();
    } else {
        ap_phi_mux_j_0_phi_fu_223_p4 = j_0_reg_219.read();
    }
}

void max_pooling4::thread_ap_phi_mux_w_0_phi_fu_187_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln80_reg_994_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        ap_phi_mux_w_0_phi_fu_187_p4 = select_ln82_2_reg_1135.read();
    } else {
        ap_phi_mux_w_0_phi_fu_187_p4 = w_0_reg_183.read();
    }
}

void max_pooling4::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pooling4::thread_bitcast_ln5_fu_930_p1() {
    bitcast_ln5_fu_930_p1 = max_value_1_reg_1169_pp0_iter3_reg.read();
}

void max_pooling4::thread_bitcast_ln89_1_fu_854_p1() {
    bitcast_ln89_1_fu_854_p1 = input_load_reg_1162.read();
}

void max_pooling4::thread_bitcast_ln89_fu_837_p1() {
    bitcast_ln89_fu_837_p1 = max_value_reg_1155.read();
}

void max_pooling4::thread_c_fu_355_p2() {
    c_fu_355_p2 = (!ap_const_lv5_1.is_01() || !ap_phi_mux_c_0_phi_fu_140_p4.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1) + sc_biguint<5>(ap_phi_mux_c_0_phi_fu_140_p4.read()));
}

void max_pooling4::thread_grp_fu_231_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        grp_fu_231_p0 = max_value_1_reg_1169.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_231_p0 = max_value_fu_828_p3.read();
    } else {
        grp_fu_231_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void max_pooling4::thread_grp_fu_231_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        grp_fu_231_p1 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_231_p1 = input_r_q0.read();
    } else {
        grp_fu_231_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void max_pooling4::thread_h_fu_311_p2() {
    h_fu_311_p2 = (!ap_const_lv3_1.is_01() || !select_ln89_fu_273_p3.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(select_ln89_fu_273_p3.read()));
}

void max_pooling4::thread_i_fu_561_p2() {
    i_fu_561_p2 = (!ap_const_lv2_1.is_01() || !select_ln82_reg_1059.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(select_ln82_reg_1059.read()));
}

void max_pooling4::thread_icmp_ln5_1_fu_953_p2() {
    icmp_ln5_1_fu_953_p2 = (!trunc_ln5_fu_943_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln5_fu_943_p1.read() == ap_const_lv23_0);
}

void max_pooling4::thread_icmp_ln5_fu_947_p2() {
    icmp_ln5_fu_947_p2 = (!tmp_4_fu_933_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_933_p4.read() != ap_const_lv8_FF);
}

void max_pooling4::thread_icmp_ln80_fu_255_p2() {
    icmp_ln80_fu_255_p2 = (!ap_phi_mux_indvar_flatten117_phi_fu_129_p4.read().is_01() || !ap_const_lv11_640.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten117_phi_fu_129_p4.read() == ap_const_lv11_640);
}

void max_pooling4::thread_icmp_ln81_fu_267_p2() {
    icmp_ln81_fu_267_p2 = (!ap_phi_mux_indvar_flatten63_phi_fu_152_p4.read().is_01() || !ap_const_lv8_64.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten63_phi_fu_152_p4.read() == ap_const_lv8_64);
}

void max_pooling4::thread_icmp_ln82_fu_299_p2() {
    icmp_ln82_fu_299_p2 = (!ap_phi_mux_indvar_flatten24_phi_fu_175_p4.read().is_01() || !ap_const_lv6_14.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten24_phi_fu_175_p4.read() == ap_const_lv6_14);
}

void max_pooling4::thread_icmp_ln83_fu_287_p2() {
    icmp_ln83_fu_287_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_199_p4.read().is_01() || !ap_const_lv4_4.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_199_p4.read() == ap_const_lv4_4);
}

void max_pooling4::thread_icmp_ln84_fu_430_p2() {
    icmp_ln84_fu_430_p2 = (!ap_phi_mux_j_0_phi_fu_223_p4.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_j_0_phi_fu_223_p4.read() == ap_const_lv2_2);
}

void max_pooling4::thread_icmp_ln89_1_fu_877_p2() {
    icmp_ln89_1_fu_877_p2 = (!trunc_ln89_fu_850_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln89_fu_850_p1.read() == ap_const_lv23_0);
}

void max_pooling4::thread_icmp_ln89_2_fu_889_p2() {
    icmp_ln89_2_fu_889_p2 = (!tmp_2_fu_857_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_857_p4.read() != ap_const_lv8_FF);
}

void max_pooling4::thread_icmp_ln89_3_fu_895_p2() {
    icmp_ln89_3_fu_895_p2 = (!trunc_ln89_1_fu_867_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln89_1_fu_867_p1.read() == ap_const_lv23_0);
}

void max_pooling4::thread_icmp_ln89_fu_871_p2() {
    icmp_ln89_fu_871_p2 = (!tmp_fu_840_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_840_p4.read() != ap_const_lv8_FF);
}

void max_pooling4::thread_icmp_ln92_1_fu_655_p2() {
    icmp_ln92_1_fu_655_p2 = (!select_ln83_fu_577_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(select_ln83_fu_577_p3.read() == ap_const_lv2_1);
}

void max_pooling4::thread_icmp_ln92_2_fu_625_p2() {
    icmp_ln92_2_fu_625_p2 = (!select_ln82_reg_1059.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(select_ln82_reg_1059.read() == ap_const_lv2_0);
}

void max_pooling4::thread_icmp_ln92_fu_419_p2() {
    icmp_ln92_fu_419_p2 = (!i_0_reg_207.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_207.read() == ap_const_lv2_1);
}

void max_pooling4::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<11>) (zext_ln89_5_fu_807_p1.read());
}

void max_pooling4::thread_input_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void max_pooling4::thread_j_fu_812_p2() {
    j_fu_812_p2 = (!select_ln83_reg_1089.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(select_ln83_reg_1089.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void max_pooling4::thread_max_value_1_fu_919_p3() {
    max_value_1_fu_919_p3 = (!and_ln89_1_fu_913_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln89_1_fu_913_p2.read()[0].to_bool())? max_value_reg_1155.read(): input_load_reg_1162.read());
}

void max_pooling4::thread_max_value_fu_828_p3() {
    max_value_fu_828_p3 = (!or_ln86_fu_823_p2.read()[0].is_01())? sc_lv<32>(): ((or_ln86_fu_823_p2.read()[0].to_bool())? max_value_4_fu_96.read(): ap_const_lv32_D368D4A5);
}

void max_pooling4::thread_or_ln5_fu_959_p2() {
    or_ln5_fu_959_p2 = (icmp_ln5_1_fu_953_p2.read() | icmp_ln5_fu_947_p2.read());
}

void max_pooling4::thread_or_ln81_1_fu_323_p2() {
    or_ln81_1_fu_323_p2 = (icmp_ln81_fu_267_p2.read() | xor_ln81_fu_317_p2.read());
}

void max_pooling4::thread_or_ln81_fu_441_p2() {
    or_ln81_fu_441_p2 = (and_ln89_6_reg_1024.read() | icmp_ln81_reg_1003.read());
}

void max_pooling4::thread_or_ln82_1_fu_341_p2() {
    or_ln82_1_fu_341_p2 = (or_ln82_fu_335_p2.read() | icmp_ln81_fu_267_p2.read());
}

void max_pooling4::thread_or_ln82_fu_335_p2() {
    or_ln82_fu_335_p2 = (and_ln81_3_fu_329_p2.read() | and_ln89_6_fu_305_p2.read());
}

void max_pooling4::thread_or_ln83_1_fu_571_p2() {
    or_ln83_1_fu_571_p2 = (or_ln83_fu_566_p2.read() | or_ln81_fu_441_p2.read());
}

void max_pooling4::thread_or_ln83_fu_566_p2() {
    or_ln83_fu_566_p2 = (and_ln82_2_fu_555_p2.read() | and_ln81_3_reg_1045.read());
}

void max_pooling4::thread_or_ln86_fu_823_p2() {
    or_ln86_fu_823_p2 = (trunc_ln84_fu_820_p1.read() | select_ln83_1_reg_1095.read());
}

void max_pooling4::thread_or_ln89_1_fu_901_p2() {
    or_ln89_1_fu_901_p2 = (icmp_ln89_3_fu_895_p2.read() | icmp_ln89_2_fu_889_p2.read());
}

void max_pooling4::thread_or_ln89_fu_883_p2() {
    or_ln89_fu_883_p2 = (icmp_ln89_1_fu_877_p2.read() | icmp_ln89_fu_871_p2.read());
}

void max_pooling4::thread_output_r_address0() {
    output_r_address0 = output_addr_reg_1140_pp0_iter3_reg.read();
}

void max_pooling4::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void max_pooling4::thread_output_r_d0() {
    output_r_d0 = select_ln5_reg_1176.read();
}

void max_pooling4::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(and_ln92_reg_1116_pp0_iter3_reg.read(), ap_const_lv1_1))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void max_pooling4::thread_p_shl1_cast_fu_740_p3() {
    p_shl1_cast_fu_740_p3 = esl_concat<8,2>(add_ln93_1_fu_730_p2.read(), ap_const_lv2_0);
}

void max_pooling4::thread_p_shl_cast_fu_774_p3() {
    p_shl_cast_fu_774_p3 = esl_concat<9,3>(add_ln89_1_reg_1100.read(), ap_const_lv3_0);
}

void max_pooling4::thread_select_ln5_fu_971_p3() {
    select_ln5_fu_971_p3 = (!and_ln5_fu_965_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln5_fu_965_p2.read()[0].to_bool())? max_value_1_reg_1169_pp0_iter3_reg.read(): ap_const_lv32_0);
}

void max_pooling4::thread_select_ln81_1_fu_460_p3() {
    select_ln81_1_fu_460_p3 = (!and_ln89_6_reg_1024.read()[0].is_01())? sc_lv<4>(): ((and_ln89_6_reg_1024.read()[0].to_bool())? shl_ln88_mid1_fu_453_p3.read(): select_ln89_2_fu_398_p3.read());
}

void max_pooling4::thread_select_ln81_2_fu_467_p3() {
    select_ln81_2_fu_467_p3 = (!and_ln89_6_reg_1024.read()[0].is_01())? sc_lv<3>(): ((and_ln89_6_reg_1024.read()[0].to_bool())? h_reg_1032.read(): select_ln89_reg_1012.read());
}

void max_pooling4::thread_select_ln81_3_fu_480_p3() {
    select_ln81_3_fu_480_p3 = (!or_ln81_fu_441_p2.read()[0].is_01())? sc_lv<4>(): ((or_ln81_fu_441_p2.read()[0].to_bool())? ap_const_lv4_0: shl_ln88_s_fu_472_p3.read());
}

void max_pooling4::thread_select_ln81_4_fu_493_p3() {
    select_ln81_4_fu_493_p3 = (!and_ln89_6_reg_1024.read()[0].is_01())? sc_lv<4>(): ((and_ln89_6_reg_1024.read()[0].to_bool())? shl_ln88_mid1_fu_453_p3.read(): select_ln89_3_fu_413_p3.read());
}

void max_pooling4::thread_select_ln81_5_fu_700_p3() {
    select_ln81_5_fu_700_p3 = (!icmp_ln81_reg_1003.read()[0].is_01())? sc_lv<8>(): ((icmp_ln81_reg_1003.read()[0].to_bool())? ap_const_lv8_1: add_ln81_1_fu_694_p2.read());
}

void max_pooling4::thread_select_ln81_fu_445_p3() {
    select_ln81_fu_445_p3 = (!or_ln81_fu_441_p2.read()[0].is_01())? sc_lv<3>(): ((or_ln81_fu_441_p2.read()[0].to_bool())? ap_const_lv3_0: ap_phi_mux_w_0_phi_fu_187_p4.read());
}

void max_pooling4::thread_select_ln82_1_fu_524_p3() {
    select_ln82_1_fu_524_p3 = (!and_ln81_3_reg_1045.read()[0].is_01())? sc_lv<4>(): ((and_ln81_3_reg_1045.read()[0].to_bool())? shl_ln88_1_mid1_fu_516_p3.read(): select_ln81_3_fu_480_p3.read());
}

void max_pooling4::thread_select_ln82_2_fu_754_p3() {
    select_ln82_2_fu_754_p3 = (!and_ln81_3_reg_1045.read()[0].is_01())? sc_lv<3>(): ((and_ln81_3_reg_1045.read()[0].to_bool())? w_reg_1084.read(): select_ln81_reg_1073.read());
}

void max_pooling4::thread_select_ln82_3_fu_542_p3() {
    select_ln82_3_fu_542_p3 = (!and_ln81_3_reg_1045.read()[0].is_01())? sc_lv<4>(): ((and_ln81_3_reg_1045.read()[0].to_bool())? select_ln81_1_fu_460_p3.read(): select_ln81_4_fu_493_p3.read());
}

void max_pooling4::thread_select_ln82_4_fu_686_p3() {
    select_ln82_4_fu_686_p3 = (!or_ln81_fu_441_p2.read()[0].is_01())? sc_lv<6>(): ((or_ln81_fu_441_p2.read()[0].to_bool())? ap_const_lv6_1: add_ln82_1_fu_680_p2.read());
}

void max_pooling4::thread_select_ln82_fu_347_p3() {
    select_ln82_fu_347_p3 = (!or_ln82_1_fu_341_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln82_1_fu_341_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_i_0_phi_fu_211_p4.read());
}

void max_pooling4::thread_select_ln83_1_fu_589_p3() {
    select_ln83_1_fu_589_p3 = (!and_ln82_2_fu_555_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln82_2_fu_555_p2.read()[0].to_bool())? trunc_ln83_1_fu_585_p1.read(): and_ln82_fu_536_p2.read());
}

void max_pooling4::thread_select_ln83_2_fu_607_p3() {
    select_ln83_2_fu_607_p3 = (!and_ln82_2_fu_555_p2.read()[0].is_01())? sc_lv<4>(): ((and_ln82_2_fu_555_p2.read()[0].to_bool())? add_ln88_2_fu_601_p2.read(): select_ln82_3_fu_542_p3.read());
}

void max_pooling4::thread_select_ln83_3_fu_630_p3() {
    select_ln83_3_fu_630_p3 = (!and_ln82_2_fu_555_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln82_2_fu_555_p2.read()[0].to_bool())? icmp_ln92_2_fu_625_p2.read(): and_ln82_1_fu_549_p2.read());
}

void max_pooling4::thread_select_ln83_4_fu_638_p3() {
    select_ln83_4_fu_638_p3 = (!and_ln82_2_fu_555_p2.read()[0].is_01())? sc_lv<2>(): ((and_ln82_2_fu_555_p2.read()[0].to_bool())? i_fu_561_p2.read(): select_ln82_reg_1059.read());
}

void max_pooling4::thread_select_ln83_5_fu_673_p3() {
    select_ln83_5_fu_673_p3 = (!or_ln82_1_reg_1054.read()[0].is_01())? sc_lv<4>(): ((or_ln82_1_reg_1054.read()[0].to_bool())? ap_const_lv4_1: add_ln83_1_fu_667_p2.read());
}

void max_pooling4::thread_select_ln83_fu_577_p3() {
    select_ln83_fu_577_p3 = (!or_ln83_1_fu_571_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln83_1_fu_571_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_j_0_phi_fu_223_p4.read());
}

void max_pooling4::thread_select_ln89_1_fu_361_p3() {
    select_ln89_1_fu_361_p3 = (!icmp_ln81_reg_1003.read()[0].is_01())? sc_lv<5>(): ((icmp_ln81_reg_1003.read()[0].to_bool())? c_fu_355_p2.read(): ap_phi_mux_c_0_phi_fu_140_p4.read());
}

void max_pooling4::thread_select_ln89_2_fu_398_p3() {
    select_ln89_2_fu_398_p3 = (!icmp_ln81_reg_1003.read()[0].is_01())? sc_lv<4>(): ((icmp_ln81_reg_1003.read()[0].to_bool())? ap_const_lv4_0: shl_ln_reg_984.read());
}

void max_pooling4::thread_select_ln89_3_fu_413_p3() {
    select_ln89_3_fu_413_p3 = (!icmp_ln81_reg_1003.read()[0].is_01())? sc_lv<4>(): ((icmp_ln81_reg_1003.read()[0].to_bool())? ap_const_lv4_0: add_ln88_reg_989.read());
}

void max_pooling4::thread_select_ln89_fu_273_p3() {
    select_ln89_fu_273_p3 = (!icmp_ln81_fu_267_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln81_fu_267_p2.read()[0].to_bool())? ap_const_lv3_0: ap_phi_mux_h_0_phi_fu_164_p4.read());
}

void max_pooling4::thread_shl_ln88_1_mid1_fu_516_p3() {
    shl_ln88_1_mid1_fu_516_p3 = esl_concat<3,1>(w_fu_510_p2.read(), ap_const_lv1_0);
}

void max_pooling4::thread_shl_ln88_mid1_fu_453_p3() {
    shl_ln88_mid1_fu_453_p3 = esl_concat<3,1>(h_reg_1032.read(), ap_const_lv1_0);
}

void max_pooling4::thread_shl_ln88_s_fu_472_p3() {
    shl_ln88_s_fu_472_p3 = esl_concat<3,1>(ap_phi_mux_w_0_phi_fu_187_p4.read(), ap_const_lv1_0);
}

void max_pooling4::thread_shl_ln_fu_237_p3() {
    shl_ln_fu_237_p3 = esl_concat<3,1>(ap_phi_mux_h_0_phi_fu_164_p4.read(), ap_const_lv1_0);
}

void max_pooling4::thread_tmp_2_fu_857_p4() {
    tmp_2_fu_857_p4 = bitcast_ln89_1_fu_854_p1.read().range(30, 23);
}

void max_pooling4::thread_tmp_4_fu_933_p4() {
    tmp_4_fu_933_p4 = bitcast_ln5_fu_930_p1.read().range(30, 23);
}

void max_pooling4::thread_tmp_6_fu_368_p3() {
    tmp_6_fu_368_p3 = esl_concat<5,3>(select_ln89_1_fu_361_p3.read(), ap_const_lv3_0);
}

void max_pooling4::thread_tmp_7_fu_380_p3() {
    tmp_7_fu_380_p3 = esl_concat<5,1>(select_ln89_1_fu_361_p3.read(), ap_const_lv1_0);
}

void max_pooling4::thread_tmp_8_fu_710_p3() {
    tmp_8_fu_710_p3 = esl_concat<5,2>(select_ln89_1_reg_1066.read(), ap_const_lv2_0);
}

void max_pooling4::thread_tmp_9_fu_781_p3() {
    tmp_9_fu_781_p3 = esl_concat<9,1>(add_ln89_1_reg_1100.read(), ap_const_lv1_0);
}

void max_pooling4::thread_tmp_fu_840_p4() {
    tmp_fu_840_p4 = bitcast_ln89_fu_837_p1.read().range(30, 23);
}

void max_pooling4::thread_trunc_ln5_fu_943_p1() {
    trunc_ln5_fu_943_p1 = bitcast_ln5_fu_930_p1.read().range(23-1, 0);
}

void max_pooling4::thread_trunc_ln83_1_fu_585_p1() {
    trunc_ln83_1_fu_585_p1 = i_fu_561_p2.read().range(1-1, 0);
}

void max_pooling4::thread_trunc_ln83_fu_404_p1() {
    trunc_ln83_fu_404_p1 = i_0_reg_207.read().range(1-1, 0);
}

void max_pooling4::thread_trunc_ln84_fu_820_p1() {
    trunc_ln84_fu_820_p1 = select_ln83_reg_1089.read().range(1-1, 0);
}

void max_pooling4::thread_trunc_ln89_1_fu_867_p1() {
    trunc_ln89_1_fu_867_p1 = bitcast_ln89_1_fu_854_p1.read().range(23-1, 0);
}

void max_pooling4::thread_trunc_ln89_fu_850_p1() {
    trunc_ln89_fu_850_p1 = bitcast_ln89_fu_837_p1.read().range(23-1, 0);
}

void max_pooling4::thread_w_fu_510_p2() {
    w_fu_510_p2 = (!ap_const_lv3_1.is_01() || !select_ln81_fu_445_p3.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(select_ln81_fu_445_p3.read()));
}

void max_pooling4::thread_xor_ln81_fu_317_p2() {
    xor_ln81_fu_317_p2 = (icmp_ln82_fu_299_p2.read() ^ ap_const_lv1_1);
}

void max_pooling4::thread_xor_ln82_fu_531_p2() {
    xor_ln82_fu_531_p2 = (and_ln81_3_reg_1045.read() ^ ap_const_lv1_1);
}

void max_pooling4::thread_xor_ln89_fu_281_p2() {
    xor_ln89_fu_281_p2 = (icmp_ln81_fu_267_p2.read() ^ ap_const_lv1_1);
}

void max_pooling4::thread_zext_ln81_fu_727_p1() {
    zext_ln81_fu_727_p1 = esl_zext<8,3>(select_ln81_2_reg_1078.read());
}

void max_pooling4::thread_zext_ln82_fu_759_p1() {
    zext_ln82_fu_759_p1 = esl_zext<10,3>(select_ln82_2_fu_754_p3.read());
}

void max_pooling4::thread_zext_ln83_1_fu_597_p1() {
    zext_ln83_1_fu_597_p1 = esl_zext<4,2>(i_fu_561_p2.read());
}

void max_pooling4::thread_zext_ln83_2_fu_615_p1() {
    zext_ln83_2_fu_615_p1 = esl_zext<9,4>(select_ln83_2_fu_607_p3.read());
}

void max_pooling4::thread_zext_ln83_fu_245_p1() {
    zext_ln83_fu_245_p1 = esl_zext<4,2>(ap_phi_mux_i_0_phi_fu_211_p4.read());
}

void max_pooling4::thread_zext_ln84_fu_645_p1() {
    zext_ln84_fu_645_p1 = esl_zext<4,2>(select_ln83_fu_577_p3.read());
}

void max_pooling4::thread_zext_ln89_1_fu_376_p1() {
    zext_ln89_1_fu_376_p1 = esl_zext<9,8>(tmp_6_fu_368_p3.read());
}

void max_pooling4::thread_zext_ln89_2_fu_388_p1() {
    zext_ln89_2_fu_388_p1 = esl_zext<9,6>(tmp_7_fu_380_p3.read());
}

void max_pooling4::thread_zext_ln89_3_fu_788_p1() {
    zext_ln89_3_fu_788_p1 = esl_zext<12,10>(tmp_9_fu_781_p3.read());
}

void max_pooling4::thread_zext_ln89_4_fu_798_p1() {
    zext_ln89_4_fu_798_p1 = esl_zext<12,4>(add_ln88_1_reg_1111.read());
}

void max_pooling4::thread_zext_ln89_5_fu_807_p1() {
    zext_ln89_5_fu_807_p1 = esl_zext<64,12>(add_ln89_3_fu_801_p2.read());
}

void max_pooling4::thread_zext_ln89_fu_707_p1() {
    zext_ln89_fu_707_p1 = esl_zext<8,5>(select_ln89_1_reg_1066.read());
}

void max_pooling4::thread_zext_ln93_1_fu_736_p1() {
    zext_ln93_1_fu_736_p1 = esl_zext<10,8>(add_ln93_1_fu_730_p2.read());
}

void max_pooling4::thread_zext_ln93_2_fu_769_p1() {
    zext_ln93_2_fu_769_p1 = esl_zext<64,10>(add_ln93_3_fu_763_p2.read());
}

void max_pooling4::thread_zext_ln93_fu_717_p1() {
    zext_ln93_fu_717_p1 = esl_zext<8,7>(tmp_8_fu_710_p3.read());
}

void max_pooling4::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln80_fu_255_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln80_fu_255_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

