// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pooling2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pooling2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pooling2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> max_pooling2::ap_ST_fsm_state1 = "1";
const sc_lv<4> max_pooling2::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<4> max_pooling2::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<4> max_pooling2::ap_ST_fsm_state11 = "1000";
const bool max_pooling2::ap_const_boolean_1 = true;
const sc_lv<32> max_pooling2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pooling2::ap_const_lv32_1 = "1";
const bool max_pooling2::ap_const_boolean_0 = false;
const sc_lv<1> max_pooling2::ap_const_lv1_0 = "0";
const sc_lv<32> max_pooling2::ap_const_lv32_2 = "10";
const sc_lv<1> max_pooling2::ap_const_lv1_1 = "1";
const sc_lv<13> max_pooling2::ap_const_lv13_0 = "0000000000000";
const sc_lv<3> max_pooling2::ap_const_lv3_0 = "000";
const sc_lv<10> max_pooling2::ap_const_lv10_0 = "0000000000";
const sc_lv<4> max_pooling2::ap_const_lv4_0 = "0000";
const sc_lv<7> max_pooling2::ap_const_lv7_0 = "0000000";
const sc_lv<2> max_pooling2::ap_const_lv2_0 = "00";
const sc_lv<13> max_pooling2::ap_const_lv13_1260 = "1001001100000";
const sc_lv<13> max_pooling2::ap_const_lv13_1 = "1";
const sc_lv<3> max_pooling2::ap_const_lv3_1 = "1";
const sc_lv<10> max_pooling2::ap_const_lv10_310 = "1100010000";
const sc_lv<2> max_pooling2::ap_const_lv2_1 = "1";
const sc_lv<2> max_pooling2::ap_const_lv2_2 = "10";
const sc_lv<4> max_pooling2::ap_const_lv4_4 = "100";
const sc_lv<7> max_pooling2::ap_const_lv7_38 = "111000";
const sc_lv<4> max_pooling2::ap_const_lv4_1 = "1";
const sc_lv<5> max_pooling2::ap_const_lv5_0 = "00000";
const sc_lv<7> max_pooling2::ap_const_lv7_1 = "1";
const sc_lv<10> max_pooling2::ap_const_lv10_1 = "1";
const sc_lv<32> max_pooling2::ap_const_lv32_D368D4A5 = "11010011011010001101010010100101";
const sc_lv<32> max_pooling2::ap_const_lv32_17 = "10111";
const sc_lv<32> max_pooling2::ap_const_lv32_1E = "11110";
const sc_lv<8> max_pooling2::ap_const_lv8_FF = "11111111";
const sc_lv<23> max_pooling2::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> max_pooling2::ap_const_lv5_2 = "10";
const sc_lv<32> max_pooling2::ap_const_lv32_3 = "11";

max_pooling2::max_pooling2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lenet_cnn_fcmp_32dEe_U12 = new lenet_cnn_fcmp_32dEe<1,2,32,32,1>("lenet_cnn_fcmp_32dEe_U12");
    lenet_cnn_fcmp_32dEe_U12->clk(ap_clk);
    lenet_cnn_fcmp_32dEe_U12->reset(ap_rst);
    lenet_cnn_fcmp_32dEe_U12->din0(grp_fu_231_p0);
    lenet_cnn_fcmp_32dEe_U12->din1(grp_fu_231_p1);
    lenet_cnn_fcmp_32dEe_U12->ce(ap_var_for_const0);
    lenet_cnn_fcmp_32dEe_U12->opcode(ap_var_for_const1);
    lenet_cnn_fcmp_32dEe_U12->dout(grp_fu_231_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln32_fu_261_p2);
    sensitive << ( ap_phi_mux_indvar_flatten117_phi_fu_131_p4 );

    SC_METHOD(thread_add_ln33_1_fu_746_p2);
    sensitive << ( indvar_flatten63_reg_150 );

    SC_METHOD(thread_add_ln34_1_fu_733_p2);
    sensitive << ( indvar_flatten24_reg_173 );

    SC_METHOD(thread_add_ln35_1_fu_720_p2);
    sensitive << ( indvar_flatten_reg_197 );

    SC_METHOD(thread_add_ln40_1_fu_699_p2);
    sensitive << ( zext_ln36_fu_696_p1 );
    sensitive << ( select_ln34_1_fu_621_p3 );

    SC_METHOD(thread_add_ln40_2_fu_638_p2);
    sensitive << ( select_ln33_1_fu_573_p3 );
    sensitive << ( zext_ln35_1_fu_635_p1 );

    SC_METHOD(thread_add_ln40_fu_249_p2);
    sensitive << ( shl_ln_fu_237_p3 );
    sensitive << ( zext_ln35_fu_245_p1 );

    SC_METHOD(thread_add_ln41_1_fu_709_p2);
    sensitive << ( sub_ln41_1_fu_685_p2 );
    sensitive << ( zext_ln41_2_fu_705_p1 );

    SC_METHOD(thread_add_ln41_fu_655_p2);
    sensitive << ( sext_ln41_fu_543_p1 );
    sensitive << ( zext_ln35_2_fu_651_p1 );

    SC_METHOD(thread_add_ln45_1_fu_839_p2);
    sensitive << ( sub_ln45_1_fu_824_p2 );
    sensitive << ( zext_ln34_fu_835_p1 );

    SC_METHOD(thread_add_ln45_fu_794_p2);
    sensitive << ( sext_ln45_fu_787_p1 );
    sensitive << ( zext_ln33_fu_791_p1 );

    SC_METHOD(thread_and_ln33_1_fu_381_p2);
    sensitive << ( or_ln33_1_fu_369_p2 );
    sensitive << ( and_ln41_3_fu_309_p2 );

    SC_METHOD(thread_and_ln33_2_fu_387_p2);
    sensitive << ( or_ln33_1_fu_369_p2 );
    sensitive << ( and_ln41_4_fu_321_p2 );

    SC_METHOD(thread_and_ln33_3_fu_393_p2);
    sensitive << ( or_ln33_1_fu_369_p2 );
    sensitive << ( and_ln41_5_fu_333_p2 );

    SC_METHOD(thread_and_ln33_fu_375_p2);
    sensitive << ( and_ln41_2_fu_297_p2 );
    sensitive << ( or_ln33_1_fu_369_p2 );

    SC_METHOD(thread_and_ln34_1_fu_431_p2);
    sensitive << ( xor_ln34_fu_419_p2 );
    sensitive << ( and_ln33_1_fu_381_p2 );

    SC_METHOD(thread_and_ln34_2_fu_437_p2);
    sensitive << ( xor_ln34_fu_419_p2 );
    sensitive << ( and_ln33_2_fu_387_p2 );

    SC_METHOD(thread_and_ln34_fu_425_p2);
    sensitive << ( and_ln33_fu_375_p2 );
    sensitive << ( xor_ln34_fu_419_p2 );

    SC_METHOD(thread_and_ln41_1_fu_950_p2);
    sensitive << ( and_ln41_fu_944_p2 );
    sensitive << ( grp_fu_231_p2 );

    SC_METHOD(thread_and_ln41_2_fu_297_p2);
    sensitive << ( trunc_ln35_fu_293_p1 );
    sensitive << ( xor_ln41_fu_287_p2 );

    SC_METHOD(thread_and_ln41_3_fu_309_p2);
    sensitive << ( xor_ln41_fu_287_p2 );
    sensitive << ( icmp_ln44_fu_303_p2 );

    SC_METHOD(thread_and_ln41_4_fu_321_p2);
    sensitive << ( xor_ln41_fu_287_p2 );
    sensitive << ( icmp_ln36_fu_315_p2 );

    SC_METHOD(thread_and_ln41_5_fu_333_p2);
    sensitive << ( xor_ln41_fu_287_p2 );
    sensitive << ( icmp_ln35_fu_327_p2 );

    SC_METHOD(thread_and_ln41_6_fu_345_p2);
    sensitive << ( xor_ln41_fu_287_p2 );
    sensitive << ( icmp_ln34_fu_339_p2 );

    SC_METHOD(thread_and_ln41_fu_944_p2);
    sensitive << ( or_ln41_fu_920_p2 );
    sensitive << ( or_ln41_1_fu_938_p2 );

    SC_METHOD(thread_and_ln44_fu_501_p2);
    sensitive << ( select_ln35_3_fu_487_p3 );
    sensitive << ( icmp_ln44_1_fu_495_p2 );

    SC_METHOD(thread_and_ln5_fu_1002_p2);
    sensitive << ( grp_fu_231_p2 );
    sensitive << ( or_ln5_fu_996_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_00001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_00001);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state9_pp0_stage1_iter3);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln32_fu_255_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_phi_mux_c_0_phi_fu_142_p4);
    sensitive << ( c_0_reg_138 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( select_ln41_1_reg_1123 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_h_0_phi_fu_166_p4);
    sensitive << ( h_0_reg_162 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( select_ln33_2_reg_1135 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_213_p4);
    sensitive << ( i_0_reg_209 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( select_ln35_4_reg_1146 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten117_phi_fu_131_p4);
    sensitive << ( indvar_flatten117_reg_127 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( add_ln32_reg_1035 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten24_phi_fu_177_p4);
    sensitive << ( indvar_flatten24_reg_173 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( select_ln34_4_reg_1166 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten63_phi_fu_154_p4);
    sensitive << ( indvar_flatten63_reg_150 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( select_ln33_5_reg_1171 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_201_p4);
    sensitive << ( indvar_flatten_reg_197 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( select_ln35_5_reg_1161 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_j_0_phi_fu_224_p4);
    sensitive << ( j_0_reg_220 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_reg_1031 );
    sensitive << ( j_reg_1156 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_w_0_phi_fu_189_p4);
    sensitive << ( w_0_reg_185 );
    sensitive << ( icmp_ln32_reg_1031_pp0_iter1_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( select_ln34_2_reg_1176 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_bitcast_ln41_1_fu_891_p1);
    sensitive << ( input_load_reg_1198 );

    SC_METHOD(thread_bitcast_ln41_fu_874_p1);
    sensitive << ( max_value_reg_1191 );

    SC_METHOD(thread_bitcast_ln5_fu_967_p1);
    sensitive << ( max_value_2_reg_1205_pp0_iter3_reg );

    SC_METHOD(thread_c_fu_267_p2);
    sensitive << ( ap_phi_mux_c_0_phi_fu_142_p4 );

    SC_METHOD(thread_grp_fu_231_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( max_value_fu_865_p3 );
    sensitive << ( max_value_2_reg_1205 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_grp_fu_231_p1);
    sensitive << ( input_r_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_h_fu_351_p2);
    sensitive << ( select_ln41_fu_279_p3 );

    SC_METHOD(thread_i_fu_443_p2);
    sensitive << ( select_ln34_fu_411_p3 );

    SC_METHOD(thread_icmp_ln32_fu_255_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten117_phi_fu_131_p4 );

    SC_METHOD(thread_icmp_ln33_fu_273_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten63_phi_fu_154_p4 );

    SC_METHOD(thread_icmp_ln34_fu_339_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten24_phi_fu_177_p4 );

    SC_METHOD(thread_icmp_ln35_fu_327_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_201_p4 );

    SC_METHOD(thread_icmp_ln36_fu_315_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_j_0_phi_fu_224_p4 );

    SC_METHOD(thread_icmp_ln41_1_fu_914_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_reg_1031_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( trunc_ln41_1_fu_887_p1 );

    SC_METHOD(thread_icmp_ln41_2_fu_926_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_reg_1031_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_6_fu_894_p4 );

    SC_METHOD(thread_icmp_ln41_3_fu_932_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_reg_1031_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( trunc_ln41_2_fu_904_p1 );

    SC_METHOD(thread_icmp_ln41_fu_908_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_reg_1031_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_fu_877_p4 );

    SC_METHOD(thread_icmp_ln44_1_fu_495_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( select_ln35_fu_461_p3 );

    SC_METHOD(thread_icmp_ln44_2_fu_481_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( select_ln34_fu_411_p3 );

    SC_METHOD(thread_icmp_ln44_fu_303_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_213_p4 );

    SC_METHOD(thread_icmp_ln5_2_fu_990_p2);
    sensitive << ( and_ln44_reg_1119_pp0_iter3_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( trunc_ln5_fu_980_p1 );

    SC_METHOD(thread_icmp_ln5_fu_984_p2);
    sensitive << ( and_ln44_reg_1119_pp0_iter3_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_8_fu_970_p4 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln41_3_fu_850_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_j_fu_715_p2);
    sensitive << ( select_ln35_reg_1107 );

    SC_METHOD(thread_max_value_2_fu_956_p3);
    sensitive << ( max_value_reg_1191 );
    sensitive << ( input_load_reg_1198 );
    sensitive << ( and_ln41_1_fu_950_p2 );

    SC_METHOD(thread_max_value_fu_865_p3);
    sensitive << ( max_value_4_fu_98 );
    sensitive << ( or_ln38_fu_860_p2 );

    SC_METHOD(thread_or_ln33_1_fu_369_p2);
    sensitive << ( icmp_ln33_fu_273_p2 );
    sensitive << ( xor_ln33_fu_363_p2 );

    SC_METHOD(thread_or_ln33_fu_357_p2);
    sensitive << ( icmp_ln33_fu_273_p2 );
    sensitive << ( and_ln41_6_fu_345_p2 );

    SC_METHOD(thread_or_ln34_1_fu_405_p2);
    sensitive << ( icmp_ln33_fu_273_p2 );
    sensitive << ( or_ln34_fu_399_p2 );

    SC_METHOD(thread_or_ln34_fu_399_p2);
    sensitive << ( and_ln41_6_fu_345_p2 );
    sensitive << ( and_ln33_3_fu_393_p2 );

    SC_METHOD(thread_or_ln35_1_fu_455_p2);
    sensitive << ( or_ln33_fu_357_p2 );
    sensitive << ( or_ln35_fu_449_p2 );

    SC_METHOD(thread_or_ln35_fu_449_p2);
    sensitive << ( and_ln33_3_fu_393_p2 );
    sensitive << ( and_ln34_2_fu_437_p2 );

    SC_METHOD(thread_or_ln38_fu_860_p2);
    sensitive << ( select_ln35_1_reg_1114_pp0_iter1_reg );
    sensitive << ( trunc_ln36_fu_857_p1 );

    SC_METHOD(thread_or_ln41_1_fu_938_p2);
    sensitive << ( icmp_ln41_3_fu_932_p2 );
    sensitive << ( icmp_ln41_2_fu_926_p2 );

    SC_METHOD(thread_or_ln41_fu_920_p2);
    sensitive << ( icmp_ln41_1_fu_914_p2 );
    sensitive << ( icmp_ln41_fu_908_p2 );

    SC_METHOD(thread_or_ln5_fu_996_p2);
    sensitive << ( icmp_ln5_2_fu_990_p2 );
    sensitive << ( icmp_ln5_fu_984_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( output_addr_reg_1181_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln5_reg_1212 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( and_ln44_reg_1119_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_p_shl3_cast_fu_804_p3);
    sensitive << ( trunc_ln45_fu_800_p1 );

    SC_METHOD(thread_p_shl_cast_fu_665_p3);
    sensitive << ( trunc_ln41_fu_661_p1 );

    SC_METHOD(thread_select_ln33_1_fu_573_p3);
    sensitive << ( and_ln41_6_reg_1058 );
    sensitive << ( shl_ln40_mid1_fu_566_p3 );
    sensitive << ( select_ln41_2_fu_547_p3 );

    SC_METHOD(thread_select_ln33_2_fu_580_p3);
    sensitive << ( select_ln41_reg_1053 );
    sensitive << ( and_ln41_6_reg_1058 );
    sensitive << ( h_reg_1065 );

    SC_METHOD(thread_select_ln33_3_fu_593_p3);
    sensitive << ( or_ln33_reg_1071 );
    sensitive << ( shl_ln40_s_fu_585_p3 );

    SC_METHOD(thread_select_ln33_4_fu_600_p3);
    sensitive << ( and_ln41_6_reg_1058 );
    sensitive << ( shl_ln40_mid1_fu_566_p3 );
    sensitive << ( select_ln41_3_fu_553_p3 );

    SC_METHOD(thread_select_ln33_5_fu_752_p3);
    sensitive << ( icmp_ln33_reg_1045 );
    sensitive << ( add_ln33_1_fu_746_p2 );

    SC_METHOD(thread_select_ln33_fu_559_p3);
    sensitive << ( or_ln33_reg_1071 );
    sensitive << ( ap_phi_mux_w_0_phi_fu_189_p4 );

    SC_METHOD(thread_select_ln34_1_fu_621_p3);
    sensitive << ( and_ln33_3_reg_1078 );
    sensitive << ( shl_ln40_1_mid1_fu_613_p3 );
    sensitive << ( select_ln33_3_fu_593_p3 );

    SC_METHOD(thread_select_ln34_2_fu_830_p3);
    sensitive << ( and_ln33_3_reg_1078 );
    sensitive << ( select_ln33_reg_1130 );
    sensitive << ( w_reg_1141 );

    SC_METHOD(thread_select_ln34_3_fu_628_p3);
    sensitive << ( and_ln33_3_reg_1078 );
    sensitive << ( select_ln33_1_fu_573_p3 );
    sensitive << ( select_ln33_4_fu_600_p3 );

    SC_METHOD(thread_select_ln34_4_fu_739_p3);
    sensitive << ( or_ln33_reg_1071 );
    sensitive << ( add_ln34_1_fu_733_p2 );

    SC_METHOD(thread_select_ln34_fu_411_p3);
    sensitive << ( or_ln34_1_fu_405_p2 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_213_p4 );

    SC_METHOD(thread_select_ln35_1_fu_473_p3);
    sensitive << ( and_ln34_2_fu_437_p2 );
    sensitive << ( trunc_ln35_1_fu_469_p1 );
    sensitive << ( and_ln34_fu_425_p2 );

    SC_METHOD(thread_select_ln35_2_fu_644_p3);
    sensitive << ( and_ln34_2_reg_1095 );
    sensitive << ( add_ln40_2_fu_638_p2 );
    sensitive << ( select_ln34_3_fu_628_p3 );

    SC_METHOD(thread_select_ln35_3_fu_487_p3);
    sensitive << ( and_ln34_2_fu_437_p2 );
    sensitive << ( icmp_ln44_2_fu_481_p2 );
    sensitive << ( and_ln34_1_fu_431_p2 );

    SC_METHOD(thread_select_ln35_4_fu_691_p3);
    sensitive << ( select_ln34_reg_1090 );
    sensitive << ( and_ln34_2_reg_1095 );
    sensitive << ( i_reg_1101 );

    SC_METHOD(thread_select_ln35_5_fu_726_p3);
    sensitive << ( or_ln34_1_reg_1085 );
    sensitive << ( add_ln35_1_fu_720_p2 );

    SC_METHOD(thread_select_ln35_fu_461_p3);
    sensitive << ( ap_phi_mux_j_0_phi_fu_224_p4 );
    sensitive << ( or_ln35_1_fu_455_p2 );

    SC_METHOD(thread_select_ln41_1_fu_507_p3);
    sensitive << ( c_0_reg_138 );
    sensitive << ( c_reg_1040 );
    sensitive << ( icmp_ln33_reg_1045 );

    SC_METHOD(thread_select_ln41_2_fu_547_p3);
    sensitive << ( shl_ln_reg_1021 );
    sensitive << ( icmp_ln33_reg_1045 );

    SC_METHOD(thread_select_ln41_3_fu_553_p3);
    sensitive << ( add_ln40_reg_1026 );
    sensitive << ( icmp_ln33_reg_1045 );

    SC_METHOD(thread_select_ln41_fu_279_p3);
    sensitive << ( icmp_ln33_fu_273_p2 );
    sensitive << ( ap_phi_mux_h_0_phi_fu_166_p4 );

    SC_METHOD(thread_select_ln5_fu_1008_p3);
    sensitive << ( max_value_2_reg_1205_pp0_iter3_reg );
    sensitive << ( and_ln5_fu_1002_p2 );

    SC_METHOD(thread_sext_ln41_1_fu_681_p1);
    sensitive << ( tmp_11_fu_673_p3 );

    SC_METHOD(thread_sext_ln41_fu_543_p1);
    sensitive << ( sub_ln41_fu_537_p2 );

    SC_METHOD(thread_sext_ln45_1_fu_820_p1);
    sensitive << ( tmp_10_fu_812_p3 );

    SC_METHOD(thread_sext_ln45_fu_787_p1);
    sensitive << ( sub_ln45_fu_781_p2 );

    SC_METHOD(thread_shl_ln40_1_mid1_fu_613_p3);
    sensitive << ( w_fu_607_p2 );

    SC_METHOD(thread_shl_ln40_mid1_fu_566_p3);
    sensitive << ( h_reg_1065 );

    SC_METHOD(thread_shl_ln40_s_fu_585_p3);
    sensitive << ( ap_phi_mux_w_0_phi_fu_189_p4 );

    SC_METHOD(thread_shl_ln_fu_237_p3);
    sensitive << ( ap_phi_mux_h_0_phi_fu_166_p4 );

    SC_METHOD(thread_sub_ln41_1_fu_685_p2);
    sensitive << ( p_shl_cast_fu_665_p3 );
    sensitive << ( sext_ln41_1_fu_681_p1 );

    SC_METHOD(thread_sub_ln41_fu_537_p2);
    sensitive << ( zext_ln41_fu_521_p1 );
    sensitive << ( zext_ln41_1_fu_533_p1 );

    SC_METHOD(thread_sub_ln45_1_fu_824_p2);
    sensitive << ( p_shl3_cast_fu_804_p3 );
    sensitive << ( sext_ln45_1_fu_820_p1 );

    SC_METHOD(thread_sub_ln45_fu_781_p2);
    sensitive << ( zext_ln45_fu_766_p1 );
    sensitive << ( zext_ln45_1_fu_777_p1 );

    SC_METHOD(thread_tmp_10_fu_812_p3);
    sensitive << ( add_ln45_fu_794_p2 );

    SC_METHOD(thread_tmp_11_fu_673_p3);
    sensitive << ( add_ln41_fu_655_p2 );

    SC_METHOD(thread_tmp_1_fu_525_p3);
    sensitive << ( select_ln41_1_fu_507_p3 );

    SC_METHOD(thread_tmp_3_fu_759_p3);
    sensitive << ( select_ln41_1_reg_1123 );

    SC_METHOD(thread_tmp_4_fu_770_p3);
    sensitive << ( select_ln41_1_reg_1123 );

    SC_METHOD(thread_tmp_6_fu_894_p4);
    sensitive << ( bitcast_ln41_1_fu_891_p1 );

    SC_METHOD(thread_tmp_8_fu_970_p4);
    sensitive << ( bitcast_ln5_fu_967_p1 );

    SC_METHOD(thread_tmp_fu_877_p4);
    sensitive << ( bitcast_ln41_fu_874_p1 );

    SC_METHOD(thread_tmp_s_fu_513_p3);
    sensitive << ( select_ln41_1_fu_507_p3 );

    SC_METHOD(thread_trunc_ln35_1_fu_469_p1);
    sensitive << ( i_fu_443_p2 );

    SC_METHOD(thread_trunc_ln35_fu_293_p1);
    sensitive << ( ap_phi_mux_i_0_phi_fu_213_p4 );

    SC_METHOD(thread_trunc_ln36_fu_857_p1);
    sensitive << ( select_ln35_reg_1107_pp0_iter1_reg );

    SC_METHOD(thread_trunc_ln41_1_fu_887_p1);
    sensitive << ( bitcast_ln41_fu_874_p1 );

    SC_METHOD(thread_trunc_ln41_2_fu_904_p1);
    sensitive << ( bitcast_ln41_1_fu_891_p1 );

    SC_METHOD(thread_trunc_ln41_fu_661_p1);
    sensitive << ( add_ln41_fu_655_p2 );

    SC_METHOD(thread_trunc_ln45_fu_800_p1);
    sensitive << ( add_ln45_fu_794_p2 );

    SC_METHOD(thread_trunc_ln5_fu_980_p1);
    sensitive << ( bitcast_ln5_fu_967_p1 );

    SC_METHOD(thread_w_fu_607_p2);
    sensitive << ( select_ln33_fu_559_p3 );

    SC_METHOD(thread_xor_ln33_fu_363_p2);
    sensitive << ( icmp_ln34_fu_339_p2 );

    SC_METHOD(thread_xor_ln34_fu_419_p2);
    sensitive << ( and_ln33_3_fu_393_p2 );

    SC_METHOD(thread_xor_ln41_fu_287_p2);
    sensitive << ( icmp_ln33_fu_273_p2 );

    SC_METHOD(thread_zext_ln33_fu_791_p1);
    sensitive << ( select_ln33_2_reg_1135 );

    SC_METHOD(thread_zext_ln34_fu_835_p1);
    sensitive << ( select_ln34_2_fu_830_p3 );

    SC_METHOD(thread_zext_ln35_1_fu_635_p1);
    sensitive << ( i_reg_1101 );

    SC_METHOD(thread_zext_ln35_2_fu_651_p1);
    sensitive << ( select_ln35_2_fu_644_p3 );

    SC_METHOD(thread_zext_ln35_fu_245_p1);
    sensitive << ( ap_phi_mux_i_0_phi_fu_213_p4 );

    SC_METHOD(thread_zext_ln36_fu_696_p1);
    sensitive << ( select_ln35_reg_1107 );

    SC_METHOD(thread_zext_ln41_1_fu_533_p1);
    sensitive << ( tmp_1_fu_525_p3 );

    SC_METHOD(thread_zext_ln41_2_fu_705_p1);
    sensitive << ( add_ln40_1_fu_699_p2 );

    SC_METHOD(thread_zext_ln41_3_fu_850_p1);
    sensitive << ( add_ln41_1_reg_1151 );

    SC_METHOD(thread_zext_ln41_fu_521_p1);
    sensitive << ( tmp_s_fu_513_p3 );

    SC_METHOD(thread_zext_ln45_1_fu_777_p1);
    sensitive << ( tmp_4_fu_770_p3 );

    SC_METHOD(thread_zext_ln45_2_fu_845_p1);
    sensitive << ( add_ln45_1_fu_839_p2 );

    SC_METHOD(thread_zext_ln45_fu_766_p1);
    sensitive << ( tmp_3_fu_759_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln32_fu_255_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pooling2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten117_reg_127, "indvar_flatten117_reg_127");
    sc_trace(mVcdFile, c_0_reg_138, "c_0_reg_138");
    sc_trace(mVcdFile, indvar_flatten63_reg_150, "indvar_flatten63_reg_150");
    sc_trace(mVcdFile, h_0_reg_162, "h_0_reg_162");
    sc_trace(mVcdFile, indvar_flatten24_reg_173, "indvar_flatten24_reg_173");
    sc_trace(mVcdFile, w_0_reg_185, "w_0_reg_185");
    sc_trace(mVcdFile, indvar_flatten_reg_197, "indvar_flatten_reg_197");
    sc_trace(mVcdFile, i_0_reg_209, "i_0_reg_209");
    sc_trace(mVcdFile, j_0_reg_220, "j_0_reg_220");
    sc_trace(mVcdFile, shl_ln_fu_237_p3, "shl_ln_fu_237_p3");
    sc_trace(mVcdFile, shl_ln_reg_1021, "shl_ln_reg_1021");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter2, "ap_block_state6_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter3, "ap_block_state8_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter4, "ap_block_state10_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln40_fu_249_p2, "add_ln40_fu_249_p2");
    sc_trace(mVcdFile, add_ln40_reg_1026, "add_ln40_reg_1026");
    sc_trace(mVcdFile, icmp_ln32_fu_255_p2, "icmp_ln32_fu_255_p2");
    sc_trace(mVcdFile, icmp_ln32_reg_1031, "icmp_ln32_reg_1031");
    sc_trace(mVcdFile, icmp_ln32_reg_1031_pp0_iter1_reg, "icmp_ln32_reg_1031_pp0_iter1_reg");
    sc_trace(mVcdFile, add_ln32_fu_261_p2, "add_ln32_fu_261_p2");
    sc_trace(mVcdFile, add_ln32_reg_1035, "add_ln32_reg_1035");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, c_fu_267_p2, "c_fu_267_p2");
    sc_trace(mVcdFile, c_reg_1040, "c_reg_1040");
    sc_trace(mVcdFile, icmp_ln33_fu_273_p2, "icmp_ln33_fu_273_p2");
    sc_trace(mVcdFile, icmp_ln33_reg_1045, "icmp_ln33_reg_1045");
    sc_trace(mVcdFile, select_ln41_fu_279_p3, "select_ln41_fu_279_p3");
    sc_trace(mVcdFile, select_ln41_reg_1053, "select_ln41_reg_1053");
    sc_trace(mVcdFile, and_ln41_6_fu_345_p2, "and_ln41_6_fu_345_p2");
    sc_trace(mVcdFile, and_ln41_6_reg_1058, "and_ln41_6_reg_1058");
    sc_trace(mVcdFile, h_fu_351_p2, "h_fu_351_p2");
    sc_trace(mVcdFile, h_reg_1065, "h_reg_1065");
    sc_trace(mVcdFile, or_ln33_fu_357_p2, "or_ln33_fu_357_p2");
    sc_trace(mVcdFile, or_ln33_reg_1071, "or_ln33_reg_1071");
    sc_trace(mVcdFile, and_ln33_3_fu_393_p2, "and_ln33_3_fu_393_p2");
    sc_trace(mVcdFile, and_ln33_3_reg_1078, "and_ln33_3_reg_1078");
    sc_trace(mVcdFile, or_ln34_1_fu_405_p2, "or_ln34_1_fu_405_p2");
    sc_trace(mVcdFile, or_ln34_1_reg_1085, "or_ln34_1_reg_1085");
    sc_trace(mVcdFile, select_ln34_fu_411_p3, "select_ln34_fu_411_p3");
    sc_trace(mVcdFile, select_ln34_reg_1090, "select_ln34_reg_1090");
    sc_trace(mVcdFile, and_ln34_2_fu_437_p2, "and_ln34_2_fu_437_p2");
    sc_trace(mVcdFile, and_ln34_2_reg_1095, "and_ln34_2_reg_1095");
    sc_trace(mVcdFile, i_fu_443_p2, "i_fu_443_p2");
    sc_trace(mVcdFile, i_reg_1101, "i_reg_1101");
    sc_trace(mVcdFile, select_ln35_fu_461_p3, "select_ln35_fu_461_p3");
    sc_trace(mVcdFile, select_ln35_reg_1107, "select_ln35_reg_1107");
    sc_trace(mVcdFile, select_ln35_reg_1107_pp0_iter1_reg, "select_ln35_reg_1107_pp0_iter1_reg");
    sc_trace(mVcdFile, select_ln35_1_fu_473_p3, "select_ln35_1_fu_473_p3");
    sc_trace(mVcdFile, select_ln35_1_reg_1114, "select_ln35_1_reg_1114");
    sc_trace(mVcdFile, select_ln35_1_reg_1114_pp0_iter1_reg, "select_ln35_1_reg_1114_pp0_iter1_reg");
    sc_trace(mVcdFile, and_ln44_fu_501_p2, "and_ln44_fu_501_p2");
    sc_trace(mVcdFile, and_ln44_reg_1119, "and_ln44_reg_1119");
    sc_trace(mVcdFile, and_ln44_reg_1119_pp0_iter1_reg, "and_ln44_reg_1119_pp0_iter1_reg");
    sc_trace(mVcdFile, and_ln44_reg_1119_pp0_iter2_reg, "and_ln44_reg_1119_pp0_iter2_reg");
    sc_trace(mVcdFile, and_ln44_reg_1119_pp0_iter3_reg, "and_ln44_reg_1119_pp0_iter3_reg");
    sc_trace(mVcdFile, select_ln41_1_fu_507_p3, "select_ln41_1_fu_507_p3");
    sc_trace(mVcdFile, select_ln41_1_reg_1123, "select_ln41_1_reg_1123");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter1, "ap_block_state5_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter2, "ap_block_state7_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage1_iter3, "ap_block_state9_pp0_stage1_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, select_ln33_fu_559_p3, "select_ln33_fu_559_p3");
    sc_trace(mVcdFile, select_ln33_reg_1130, "select_ln33_reg_1130");
    sc_trace(mVcdFile, select_ln33_2_fu_580_p3, "select_ln33_2_fu_580_p3");
    sc_trace(mVcdFile, select_ln33_2_reg_1135, "select_ln33_2_reg_1135");
    sc_trace(mVcdFile, w_fu_607_p2, "w_fu_607_p2");
    sc_trace(mVcdFile, w_reg_1141, "w_reg_1141");
    sc_trace(mVcdFile, select_ln35_4_fu_691_p3, "select_ln35_4_fu_691_p3");
    sc_trace(mVcdFile, select_ln35_4_reg_1146, "select_ln35_4_reg_1146");
    sc_trace(mVcdFile, add_ln41_1_fu_709_p2, "add_ln41_1_fu_709_p2");
    sc_trace(mVcdFile, add_ln41_1_reg_1151, "add_ln41_1_reg_1151");
    sc_trace(mVcdFile, j_fu_715_p2, "j_fu_715_p2");
    sc_trace(mVcdFile, j_reg_1156, "j_reg_1156");
    sc_trace(mVcdFile, select_ln35_5_fu_726_p3, "select_ln35_5_fu_726_p3");
    sc_trace(mVcdFile, select_ln35_5_reg_1161, "select_ln35_5_reg_1161");
    sc_trace(mVcdFile, select_ln34_4_fu_739_p3, "select_ln34_4_fu_739_p3");
    sc_trace(mVcdFile, select_ln34_4_reg_1166, "select_ln34_4_reg_1166");
    sc_trace(mVcdFile, select_ln33_5_fu_752_p3, "select_ln33_5_fu_752_p3");
    sc_trace(mVcdFile, select_ln33_5_reg_1171, "select_ln33_5_reg_1171");
    sc_trace(mVcdFile, select_ln34_2_fu_830_p3, "select_ln34_2_fu_830_p3");
    sc_trace(mVcdFile, select_ln34_2_reg_1176, "select_ln34_2_reg_1176");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, output_addr_reg_1181, "output_addr_reg_1181");
    sc_trace(mVcdFile, output_addr_reg_1181_pp0_iter2_reg, "output_addr_reg_1181_pp0_iter2_reg");
    sc_trace(mVcdFile, output_addr_reg_1181_pp0_iter3_reg, "output_addr_reg_1181_pp0_iter3_reg");
    sc_trace(mVcdFile, max_value_fu_865_p3, "max_value_fu_865_p3");
    sc_trace(mVcdFile, max_value_reg_1191, "max_value_reg_1191");
    sc_trace(mVcdFile, input_load_reg_1198, "input_load_reg_1198");
    sc_trace(mVcdFile, max_value_2_fu_956_p3, "max_value_2_fu_956_p3");
    sc_trace(mVcdFile, max_value_2_reg_1205, "max_value_2_reg_1205");
    sc_trace(mVcdFile, max_value_2_reg_1205_pp0_iter3_reg, "max_value_2_reg_1205_pp0_iter3_reg");
    sc_trace(mVcdFile, select_ln5_fu_1008_p3, "select_ln5_fu_1008_p3");
    sc_trace(mVcdFile, select_ln5_reg_1212, "select_ln5_reg_1212");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten117_phi_fu_131_p4, "ap_phi_mux_indvar_flatten117_phi_fu_131_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_c_0_phi_fu_142_p4, "ap_phi_mux_c_0_phi_fu_142_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten63_phi_fu_154_p4, "ap_phi_mux_indvar_flatten63_phi_fu_154_p4");
    sc_trace(mVcdFile, ap_phi_mux_h_0_phi_fu_166_p4, "ap_phi_mux_h_0_phi_fu_166_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten24_phi_fu_177_p4, "ap_phi_mux_indvar_flatten24_phi_fu_177_p4");
    sc_trace(mVcdFile, ap_phi_mux_w_0_phi_fu_189_p4, "ap_phi_mux_w_0_phi_fu_189_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_201_p4, "ap_phi_mux_indvar_flatten_phi_fu_201_p4");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_213_p4, "ap_phi_mux_i_0_phi_fu_213_p4");
    sc_trace(mVcdFile, ap_phi_mux_j_0_phi_fu_224_p4, "ap_phi_mux_j_0_phi_fu_224_p4");
    sc_trace(mVcdFile, zext_ln45_2_fu_845_p1, "zext_ln45_2_fu_845_p1");
    sc_trace(mVcdFile, zext_ln41_3_fu_850_p1, "zext_ln41_3_fu_850_p1");
    sc_trace(mVcdFile, max_value_4_fu_98, "max_value_4_fu_98");
    sc_trace(mVcdFile, grp_fu_231_p0, "grp_fu_231_p0");
    sc_trace(mVcdFile, grp_fu_231_p1, "grp_fu_231_p1");
    sc_trace(mVcdFile, zext_ln35_fu_245_p1, "zext_ln35_fu_245_p1");
    sc_trace(mVcdFile, trunc_ln35_fu_293_p1, "trunc_ln35_fu_293_p1");
    sc_trace(mVcdFile, xor_ln41_fu_287_p2, "xor_ln41_fu_287_p2");
    sc_trace(mVcdFile, icmp_ln44_fu_303_p2, "icmp_ln44_fu_303_p2");
    sc_trace(mVcdFile, icmp_ln36_fu_315_p2, "icmp_ln36_fu_315_p2");
    sc_trace(mVcdFile, icmp_ln35_fu_327_p2, "icmp_ln35_fu_327_p2");
    sc_trace(mVcdFile, icmp_ln34_fu_339_p2, "icmp_ln34_fu_339_p2");
    sc_trace(mVcdFile, xor_ln33_fu_363_p2, "xor_ln33_fu_363_p2");
    sc_trace(mVcdFile, and_ln41_2_fu_297_p2, "and_ln41_2_fu_297_p2");
    sc_trace(mVcdFile, or_ln33_1_fu_369_p2, "or_ln33_1_fu_369_p2");
    sc_trace(mVcdFile, and_ln41_3_fu_309_p2, "and_ln41_3_fu_309_p2");
    sc_trace(mVcdFile, and_ln41_4_fu_321_p2, "and_ln41_4_fu_321_p2");
    sc_trace(mVcdFile, and_ln41_5_fu_333_p2, "and_ln41_5_fu_333_p2");
    sc_trace(mVcdFile, or_ln34_fu_399_p2, "or_ln34_fu_399_p2");
    sc_trace(mVcdFile, and_ln33_fu_375_p2, "and_ln33_fu_375_p2");
    sc_trace(mVcdFile, xor_ln34_fu_419_p2, "xor_ln34_fu_419_p2");
    sc_trace(mVcdFile, and_ln33_1_fu_381_p2, "and_ln33_1_fu_381_p2");
    sc_trace(mVcdFile, and_ln33_2_fu_387_p2, "and_ln33_2_fu_387_p2");
    sc_trace(mVcdFile, or_ln35_fu_449_p2, "or_ln35_fu_449_p2");
    sc_trace(mVcdFile, or_ln35_1_fu_455_p2, "or_ln35_1_fu_455_p2");
    sc_trace(mVcdFile, trunc_ln35_1_fu_469_p1, "trunc_ln35_1_fu_469_p1");
    sc_trace(mVcdFile, and_ln34_fu_425_p2, "and_ln34_fu_425_p2");
    sc_trace(mVcdFile, icmp_ln44_2_fu_481_p2, "icmp_ln44_2_fu_481_p2");
    sc_trace(mVcdFile, and_ln34_1_fu_431_p2, "and_ln34_1_fu_431_p2");
    sc_trace(mVcdFile, select_ln35_3_fu_487_p3, "select_ln35_3_fu_487_p3");
    sc_trace(mVcdFile, icmp_ln44_1_fu_495_p2, "icmp_ln44_1_fu_495_p2");
    sc_trace(mVcdFile, tmp_s_fu_513_p3, "tmp_s_fu_513_p3");
    sc_trace(mVcdFile, tmp_1_fu_525_p3, "tmp_1_fu_525_p3");
    sc_trace(mVcdFile, zext_ln41_fu_521_p1, "zext_ln41_fu_521_p1");
    sc_trace(mVcdFile, zext_ln41_1_fu_533_p1, "zext_ln41_1_fu_533_p1");
    sc_trace(mVcdFile, sub_ln41_fu_537_p2, "sub_ln41_fu_537_p2");
    sc_trace(mVcdFile, shl_ln40_mid1_fu_566_p3, "shl_ln40_mid1_fu_566_p3");
    sc_trace(mVcdFile, select_ln41_2_fu_547_p3, "select_ln41_2_fu_547_p3");
    sc_trace(mVcdFile, shl_ln40_s_fu_585_p3, "shl_ln40_s_fu_585_p3");
    sc_trace(mVcdFile, select_ln41_3_fu_553_p3, "select_ln41_3_fu_553_p3");
    sc_trace(mVcdFile, shl_ln40_1_mid1_fu_613_p3, "shl_ln40_1_mid1_fu_613_p3");
    sc_trace(mVcdFile, select_ln33_3_fu_593_p3, "select_ln33_3_fu_593_p3");
    sc_trace(mVcdFile, select_ln33_1_fu_573_p3, "select_ln33_1_fu_573_p3");
    sc_trace(mVcdFile, select_ln33_4_fu_600_p3, "select_ln33_4_fu_600_p3");
    sc_trace(mVcdFile, zext_ln35_1_fu_635_p1, "zext_ln35_1_fu_635_p1");
    sc_trace(mVcdFile, add_ln40_2_fu_638_p2, "add_ln40_2_fu_638_p2");
    sc_trace(mVcdFile, select_ln34_3_fu_628_p3, "select_ln34_3_fu_628_p3");
    sc_trace(mVcdFile, select_ln35_2_fu_644_p3, "select_ln35_2_fu_644_p3");
    sc_trace(mVcdFile, sext_ln41_fu_543_p1, "sext_ln41_fu_543_p1");
    sc_trace(mVcdFile, zext_ln35_2_fu_651_p1, "zext_ln35_2_fu_651_p1");
    sc_trace(mVcdFile, add_ln41_fu_655_p2, "add_ln41_fu_655_p2");
    sc_trace(mVcdFile, trunc_ln41_fu_661_p1, "trunc_ln41_fu_661_p1");
    sc_trace(mVcdFile, tmp_11_fu_673_p3, "tmp_11_fu_673_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_665_p3, "p_shl_cast_fu_665_p3");
    sc_trace(mVcdFile, sext_ln41_1_fu_681_p1, "sext_ln41_1_fu_681_p1");
    sc_trace(mVcdFile, zext_ln36_fu_696_p1, "zext_ln36_fu_696_p1");
    sc_trace(mVcdFile, select_ln34_1_fu_621_p3, "select_ln34_1_fu_621_p3");
    sc_trace(mVcdFile, add_ln40_1_fu_699_p2, "add_ln40_1_fu_699_p2");
    sc_trace(mVcdFile, sub_ln41_1_fu_685_p2, "sub_ln41_1_fu_685_p2");
    sc_trace(mVcdFile, zext_ln41_2_fu_705_p1, "zext_ln41_2_fu_705_p1");
    sc_trace(mVcdFile, add_ln35_1_fu_720_p2, "add_ln35_1_fu_720_p2");
    sc_trace(mVcdFile, add_ln34_1_fu_733_p2, "add_ln34_1_fu_733_p2");
    sc_trace(mVcdFile, add_ln33_1_fu_746_p2, "add_ln33_1_fu_746_p2");
    sc_trace(mVcdFile, tmp_3_fu_759_p3, "tmp_3_fu_759_p3");
    sc_trace(mVcdFile, tmp_4_fu_770_p3, "tmp_4_fu_770_p3");
    sc_trace(mVcdFile, zext_ln45_fu_766_p1, "zext_ln45_fu_766_p1");
    sc_trace(mVcdFile, zext_ln45_1_fu_777_p1, "zext_ln45_1_fu_777_p1");
    sc_trace(mVcdFile, sub_ln45_fu_781_p2, "sub_ln45_fu_781_p2");
    sc_trace(mVcdFile, sext_ln45_fu_787_p1, "sext_ln45_fu_787_p1");
    sc_trace(mVcdFile, zext_ln33_fu_791_p1, "zext_ln33_fu_791_p1");
    sc_trace(mVcdFile, add_ln45_fu_794_p2, "add_ln45_fu_794_p2");
    sc_trace(mVcdFile, trunc_ln45_fu_800_p1, "trunc_ln45_fu_800_p1");
    sc_trace(mVcdFile, tmp_10_fu_812_p3, "tmp_10_fu_812_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_804_p3, "p_shl3_cast_fu_804_p3");
    sc_trace(mVcdFile, sext_ln45_1_fu_820_p1, "sext_ln45_1_fu_820_p1");
    sc_trace(mVcdFile, sub_ln45_1_fu_824_p2, "sub_ln45_1_fu_824_p2");
    sc_trace(mVcdFile, zext_ln34_fu_835_p1, "zext_ln34_fu_835_p1");
    sc_trace(mVcdFile, add_ln45_1_fu_839_p2, "add_ln45_1_fu_839_p2");
    sc_trace(mVcdFile, trunc_ln36_fu_857_p1, "trunc_ln36_fu_857_p1");
    sc_trace(mVcdFile, or_ln38_fu_860_p2, "or_ln38_fu_860_p2");
    sc_trace(mVcdFile, bitcast_ln41_fu_874_p1, "bitcast_ln41_fu_874_p1");
    sc_trace(mVcdFile, bitcast_ln41_1_fu_891_p1, "bitcast_ln41_1_fu_891_p1");
    sc_trace(mVcdFile, tmp_fu_877_p4, "tmp_fu_877_p4");
    sc_trace(mVcdFile, trunc_ln41_1_fu_887_p1, "trunc_ln41_1_fu_887_p1");
    sc_trace(mVcdFile, icmp_ln41_1_fu_914_p2, "icmp_ln41_1_fu_914_p2");
    sc_trace(mVcdFile, icmp_ln41_fu_908_p2, "icmp_ln41_fu_908_p2");
    sc_trace(mVcdFile, tmp_6_fu_894_p4, "tmp_6_fu_894_p4");
    sc_trace(mVcdFile, trunc_ln41_2_fu_904_p1, "trunc_ln41_2_fu_904_p1");
    sc_trace(mVcdFile, icmp_ln41_3_fu_932_p2, "icmp_ln41_3_fu_932_p2");
    sc_trace(mVcdFile, icmp_ln41_2_fu_926_p2, "icmp_ln41_2_fu_926_p2");
    sc_trace(mVcdFile, or_ln41_fu_920_p2, "or_ln41_fu_920_p2");
    sc_trace(mVcdFile, or_ln41_1_fu_938_p2, "or_ln41_1_fu_938_p2");
    sc_trace(mVcdFile, and_ln41_fu_944_p2, "and_ln41_fu_944_p2");
    sc_trace(mVcdFile, grp_fu_231_p2, "grp_fu_231_p2");
    sc_trace(mVcdFile, and_ln41_1_fu_950_p2, "and_ln41_1_fu_950_p2");
    sc_trace(mVcdFile, bitcast_ln5_fu_967_p1, "bitcast_ln5_fu_967_p1");
    sc_trace(mVcdFile, tmp_8_fu_970_p4, "tmp_8_fu_970_p4");
    sc_trace(mVcdFile, trunc_ln5_fu_980_p1, "trunc_ln5_fu_980_p1");
    sc_trace(mVcdFile, icmp_ln5_2_fu_990_p2, "icmp_ln5_2_fu_990_p2");
    sc_trace(mVcdFile, icmp_ln5_fu_984_p2, "icmp_ln5_fu_984_p2");
    sc_trace(mVcdFile, or_ln5_fu_996_p2, "or_ln5_fu_996_p2");
    sc_trace(mVcdFile, and_ln5_fu_1002_p2, "and_ln5_fu_1002_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_00001, "ap_block_pp0_stage1_00001");
    sc_trace(mVcdFile, ap_block_pp0_stage0_00001, "ap_block_pp0_stage0_00001");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

max_pooling2::~max_pooling2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete lenet_cnn_fcmp_32dEe_U12;
}

void max_pooling2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void max_pooling2::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv5_2;
}

void max_pooling2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        c_0_reg_138 = select_ln41_1_reg_1123.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_0_reg_138 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        h_0_reg_162 = select_ln33_2_reg_1135.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        h_0_reg_162 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_0_reg_209 = select_ln35_4_reg_1146.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_209 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten117_reg_127 = add_ln32_reg_1035.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten117_reg_127 = ap_const_lv13_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten24_reg_173 = select_ln34_4_reg_1166.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten24_reg_173 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten63_reg_150 = select_ln33_5_reg_1171.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten63_reg_150 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_197 = select_ln35_5_reg_1161.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_197 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        j_0_reg_220 = j_reg_1156.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_reg_220 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        w_0_reg_185 = select_ln34_2_reg_1176.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        w_0_reg_185 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        add_ln32_reg_1035 = add_ln32_fu_261_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        add_ln40_reg_1026 = add_ln40_fu_249_p2.read();
        and_ln44_reg_1119_pp0_iter1_reg = and_ln44_reg_1119.read();
        and_ln44_reg_1119_pp0_iter2_reg = and_ln44_reg_1119_pp0_iter1_reg.read();
        and_ln44_reg_1119_pp0_iter3_reg = and_ln44_reg_1119_pp0_iter2_reg.read();
        icmp_ln32_reg_1031 = icmp_ln32_fu_255_p2.read();
        icmp_ln32_reg_1031_pp0_iter1_reg = icmp_ln32_reg_1031.read();
        max_value_2_reg_1205_pp0_iter3_reg = max_value_2_reg_1205.read();
        output_addr_reg_1181_pp0_iter2_reg = output_addr_reg_1181.read();
        output_addr_reg_1181_pp0_iter3_reg = output_addr_reg_1181_pp0_iter2_reg.read();
        select_ln35_1_reg_1114_pp0_iter1_reg = select_ln35_1_reg_1114.read();
        select_ln35_reg_1107_pp0_iter1_reg = select_ln35_reg_1107.read();
        shl_ln_reg_1021 = shl_ln_fu_237_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0))) {
        add_ln41_1_reg_1151 = add_ln41_1_fu_709_p2.read();
        select_ln33_reg_1130 = select_ln33_fu_559_p3.read();
        w_reg_1141 = w_fu_607_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_fu_255_p2.read(), ap_const_lv1_0))) {
        and_ln33_3_reg_1078 = and_ln33_3_fu_393_p2.read();
        and_ln34_2_reg_1095 = and_ln34_2_fu_437_p2.read();
        and_ln41_6_reg_1058 = and_ln41_6_fu_345_p2.read();
        and_ln44_reg_1119 = and_ln44_fu_501_p2.read();
        c_reg_1040 = c_fu_267_p2.read();
        h_reg_1065 = h_fu_351_p2.read();
        i_reg_1101 = i_fu_443_p2.read();
        icmp_ln33_reg_1045 = icmp_ln33_fu_273_p2.read();
        or_ln33_reg_1071 = or_ln33_fu_357_p2.read();
        or_ln34_1_reg_1085 = or_ln34_1_fu_405_p2.read();
        select_ln34_reg_1090 = select_ln34_fu_411_p3.read();
        select_ln35_1_reg_1114 = select_ln35_1_fu_473_p3.read();
        select_ln35_reg_1107 = select_ln35_fu_461_p3.read();
        select_ln41_reg_1053 = select_ln41_fu_279_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_reg_1031_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        input_load_reg_1198 = input_r_q0.read();
        max_value_reg_1191 = max_value_fu_865_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0))) {
        j_reg_1156 = j_fu_715_p2.read();
        select_ln33_2_reg_1135 = select_ln33_2_fu_580_p3.read();
        select_ln33_5_reg_1171 = select_ln33_5_fu_752_p3.read();
        select_ln34_4_reg_1166 = select_ln34_4_fu_739_p3.read();
        select_ln35_4_reg_1146 = select_ln35_4_fu_691_p3.read();
        select_ln35_5_reg_1161 = select_ln35_5_fu_726_p3.read();
        select_ln41_1_reg_1123 = select_ln41_1_fu_507_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_reg_1031_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        max_value_2_reg_1205 = max_value_2_fu_956_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_reg_1031_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        max_value_4_fu_98 = max_value_2_fu_956_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0))) {
        output_addr_reg_1181 =  (sc_lv<11>) (zext_ln45_2_fu_845_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        select_ln34_2_reg_1176 = select_ln34_2_fu_830_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(and_ln44_reg_1119_pp0_iter3_reg.read(), ap_const_lv1_1))) {
        select_ln5_reg_1212 = select_ln5_fu_1008_p3.read();
    }
}

void max_pooling2::thread_add_ln32_fu_261_p2() {
    add_ln32_fu_261_p2 = (!ap_phi_mux_indvar_flatten117_phi_fu_131_p4.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(ap_phi_mux_indvar_flatten117_phi_fu_131_p4.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void max_pooling2::thread_add_ln33_1_fu_746_p2() {
    add_ln33_1_fu_746_p2 = (!indvar_flatten63_reg_150.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(indvar_flatten63_reg_150.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void max_pooling2::thread_add_ln34_1_fu_733_p2() {
    add_ln34_1_fu_733_p2 = (!indvar_flatten24_reg_173.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten24_reg_173.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void max_pooling2::thread_add_ln35_1_fu_720_p2() {
    add_ln35_1_fu_720_p2 = (!indvar_flatten_reg_197.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(indvar_flatten_reg_197.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void max_pooling2::thread_add_ln40_1_fu_699_p2() {
    add_ln40_1_fu_699_p2 = (!zext_ln36_fu_696_p1.read().is_01() || !select_ln34_1_fu_621_p3.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln36_fu_696_p1.read()) + sc_biguint<5>(select_ln34_1_fu_621_p3.read()));
}

void max_pooling2::thread_add_ln40_2_fu_638_p2() {
    add_ln40_2_fu_638_p2 = (!zext_ln35_1_fu_635_p1.read().is_01() || !select_ln33_1_fu_573_p3.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln35_1_fu_635_p1.read()) + sc_biguint<5>(select_ln33_1_fu_573_p3.read()));
}

void max_pooling2::thread_add_ln40_fu_249_p2() {
    add_ln40_fu_249_p2 = (!shl_ln_fu_237_p3.read().is_01() || !zext_ln35_fu_245_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(shl_ln_fu_237_p3.read()) + sc_biguint<5>(zext_ln35_fu_245_p1.read()));
}

void max_pooling2::thread_add_ln41_1_fu_709_p2() {
    add_ln41_1_fu_709_p2 = (!sub_ln41_1_fu_685_p2.read().is_01() || !zext_ln41_2_fu_705_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(sub_ln41_1_fu_685_p2.read()) + sc_biguint<14>(zext_ln41_2_fu_705_p1.read()));
}

void max_pooling2::thread_add_ln41_fu_655_p2() {
    add_ln41_fu_655_p2 = (!sext_ln41_fu_543_p1.read().is_01() || !zext_ln35_2_fu_651_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(sext_ln41_fu_543_p1.read()) + sc_biguint<10>(zext_ln35_2_fu_651_p1.read()));
}

void max_pooling2::thread_add_ln45_1_fu_839_p2() {
    add_ln45_1_fu_839_p2 = (!sub_ln45_1_fu_824_p2.read().is_01() || !zext_ln34_fu_835_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(sub_ln45_1_fu_824_p2.read()) + sc_biguint<12>(zext_ln34_fu_835_p1.read()));
}

void max_pooling2::thread_add_ln45_fu_794_p2() {
    add_ln45_fu_794_p2 = (!sext_ln45_fu_787_p1.read().is_01() || !zext_ln33_fu_791_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(sext_ln45_fu_787_p1.read()) + sc_biguint<9>(zext_ln33_fu_791_p1.read()));
}

void max_pooling2::thread_and_ln33_1_fu_381_p2() {
    and_ln33_1_fu_381_p2 = (and_ln41_3_fu_309_p2.read() & or_ln33_1_fu_369_p2.read());
}

void max_pooling2::thread_and_ln33_2_fu_387_p2() {
    and_ln33_2_fu_387_p2 = (and_ln41_4_fu_321_p2.read() & or_ln33_1_fu_369_p2.read());
}

void max_pooling2::thread_and_ln33_3_fu_393_p2() {
    and_ln33_3_fu_393_p2 = (and_ln41_5_fu_333_p2.read() & or_ln33_1_fu_369_p2.read());
}

void max_pooling2::thread_and_ln33_fu_375_p2() {
    and_ln33_fu_375_p2 = (and_ln41_2_fu_297_p2.read() & or_ln33_1_fu_369_p2.read());
}

void max_pooling2::thread_and_ln34_1_fu_431_p2() {
    and_ln34_1_fu_431_p2 = (and_ln33_1_fu_381_p2.read() & xor_ln34_fu_419_p2.read());
}

void max_pooling2::thread_and_ln34_2_fu_437_p2() {
    and_ln34_2_fu_437_p2 = (and_ln33_2_fu_387_p2.read() & xor_ln34_fu_419_p2.read());
}

void max_pooling2::thread_and_ln34_fu_425_p2() {
    and_ln34_fu_425_p2 = (and_ln33_fu_375_p2.read() & xor_ln34_fu_419_p2.read());
}

void max_pooling2::thread_and_ln41_1_fu_950_p2() {
    and_ln41_1_fu_950_p2 = (and_ln41_fu_944_p2.read() & grp_fu_231_p2.read());
}

void max_pooling2::thread_and_ln41_2_fu_297_p2() {
    and_ln41_2_fu_297_p2 = (trunc_ln35_fu_293_p1.read() & xor_ln41_fu_287_p2.read());
}

void max_pooling2::thread_and_ln41_3_fu_309_p2() {
    and_ln41_3_fu_309_p2 = (icmp_ln44_fu_303_p2.read() & xor_ln41_fu_287_p2.read());
}

void max_pooling2::thread_and_ln41_4_fu_321_p2() {
    and_ln41_4_fu_321_p2 = (icmp_ln36_fu_315_p2.read() & xor_ln41_fu_287_p2.read());
}

void max_pooling2::thread_and_ln41_5_fu_333_p2() {
    and_ln41_5_fu_333_p2 = (icmp_ln35_fu_327_p2.read() & xor_ln41_fu_287_p2.read());
}

void max_pooling2::thread_and_ln41_6_fu_345_p2() {
    and_ln41_6_fu_345_p2 = (icmp_ln34_fu_339_p2.read() & xor_ln41_fu_287_p2.read());
}

void max_pooling2::thread_and_ln41_fu_944_p2() {
    and_ln41_fu_944_p2 = (or_ln41_fu_920_p2.read() & or_ln41_1_fu_938_p2.read());
}

void max_pooling2::thread_and_ln44_fu_501_p2() {
    and_ln44_fu_501_p2 = (select_ln35_3_fu_487_p3.read() & icmp_ln44_1_fu_495_p2.read());
}

void max_pooling2::thread_and_ln5_fu_1002_p2() {
    and_ln5_fu_1002_p2 = (or_ln5_fu_996_p2.read() & grp_fu_231_p2.read());
}

void max_pooling2::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void max_pooling2::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void max_pooling2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pooling2::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[3];
}

void max_pooling2::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_pp0_stage0_00001() {
    ap_block_pp0_stage0_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_pp0_stage1_00001() {
    ap_block_pp0_stage1_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state10_pp0_stage0_iter4() {
    ap_block_state10_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state5_pp0_stage1_iter1() {
    ap_block_state5_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state6_pp0_stage0_iter2() {
    ap_block_state6_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state7_pp0_stage1_iter2() {
    ap_block_state7_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state8_pp0_stage0_iter3() {
    ap_block_state8_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_block_state9_pp0_stage1_iter3() {
    ap_block_state9_pp0_stage1_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pooling2::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln32_fu_255_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void max_pooling2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void max_pooling2::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void max_pooling2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pooling2::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void max_pooling2::thread_ap_phi_mux_c_0_phi_fu_142_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_c_0_phi_fu_142_p4 = select_ln41_1_reg_1123.read();
    } else {
        ap_phi_mux_c_0_phi_fu_142_p4 = c_0_reg_138.read();
    }
}

void max_pooling2::thread_ap_phi_mux_h_0_phi_fu_166_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_h_0_phi_fu_166_p4 = select_ln33_2_reg_1135.read();
    } else {
        ap_phi_mux_h_0_phi_fu_166_p4 = h_0_reg_162.read();
    }
}

void max_pooling2::thread_ap_phi_mux_i_0_phi_fu_213_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_0_phi_fu_213_p4 = select_ln35_4_reg_1146.read();
    } else {
        ap_phi_mux_i_0_phi_fu_213_p4 = i_0_reg_209.read();
    }
}

void max_pooling2::thread_ap_phi_mux_indvar_flatten117_phi_fu_131_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten117_phi_fu_131_p4 = add_ln32_reg_1035.read();
    } else {
        ap_phi_mux_indvar_flatten117_phi_fu_131_p4 = indvar_flatten117_reg_127.read();
    }
}

void max_pooling2::thread_ap_phi_mux_indvar_flatten24_phi_fu_177_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten24_phi_fu_177_p4 = select_ln34_4_reg_1166.read();
    } else {
        ap_phi_mux_indvar_flatten24_phi_fu_177_p4 = indvar_flatten24_reg_173.read();
    }
}

void max_pooling2::thread_ap_phi_mux_indvar_flatten63_phi_fu_154_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten63_phi_fu_154_p4 = select_ln33_5_reg_1171.read();
    } else {
        ap_phi_mux_indvar_flatten63_phi_fu_154_p4 = indvar_flatten63_reg_150.read();
    }
}

void max_pooling2::thread_ap_phi_mux_indvar_flatten_phi_fu_201_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_201_p4 = select_ln35_5_reg_1161.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_201_p4 = indvar_flatten_reg_197.read();
    }
}

void max_pooling2::thread_ap_phi_mux_j_0_phi_fu_224_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_0_phi_fu_224_p4 = j_reg_1156.read();
    } else {
        ap_phi_mux_j_0_phi_fu_224_p4 = j_0_reg_220.read();
    }
}

void max_pooling2::thread_ap_phi_mux_w_0_phi_fu_189_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_reg_1031_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        ap_phi_mux_w_0_phi_fu_189_p4 = select_ln34_2_reg_1176.read();
    } else {
        ap_phi_mux_w_0_phi_fu_189_p4 = w_0_reg_185.read();
    }
}

void max_pooling2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pooling2::thread_bitcast_ln41_1_fu_891_p1() {
    bitcast_ln41_1_fu_891_p1 = input_load_reg_1198.read();
}

void max_pooling2::thread_bitcast_ln41_fu_874_p1() {
    bitcast_ln41_fu_874_p1 = max_value_reg_1191.read();
}

void max_pooling2::thread_bitcast_ln5_fu_967_p1() {
    bitcast_ln5_fu_967_p1 = max_value_2_reg_1205_pp0_iter3_reg.read();
}

void max_pooling2::thread_c_fu_267_p2() {
    c_fu_267_p2 = (!ap_const_lv3_1.is_01() || !ap_phi_mux_c_0_phi_fu_142_p4.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(ap_phi_mux_c_0_phi_fu_142_p4.read()));
}

void max_pooling2::thread_grp_fu_231_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        grp_fu_231_p0 = max_value_2_reg_1205.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_231_p0 = max_value_fu_865_p3.read();
    } else {
        grp_fu_231_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void max_pooling2::thread_grp_fu_231_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        grp_fu_231_p1 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_231_p1 = input_r_q0.read();
    } else {
        grp_fu_231_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void max_pooling2::thread_h_fu_351_p2() {
    h_fu_351_p2 = (!ap_const_lv4_1.is_01() || !select_ln41_fu_279_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(select_ln41_fu_279_p3.read()));
}

void max_pooling2::thread_i_fu_443_p2() {
    i_fu_443_p2 = (!ap_const_lv2_1.is_01() || !select_ln34_fu_411_p3.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(select_ln34_fu_411_p3.read()));
}

void max_pooling2::thread_icmp_ln32_fu_255_p2() {
    icmp_ln32_fu_255_p2 = (!ap_phi_mux_indvar_flatten117_phi_fu_131_p4.read().is_01() || !ap_const_lv13_1260.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten117_phi_fu_131_p4.read() == ap_const_lv13_1260);
}

void max_pooling2::thread_icmp_ln33_fu_273_p2() {
    icmp_ln33_fu_273_p2 = (!ap_phi_mux_indvar_flatten63_phi_fu_154_p4.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten63_phi_fu_154_p4.read() == ap_const_lv10_310);
}

void max_pooling2::thread_icmp_ln34_fu_339_p2() {
    icmp_ln34_fu_339_p2 = (!ap_phi_mux_indvar_flatten24_phi_fu_177_p4.read().is_01() || !ap_const_lv7_38.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten24_phi_fu_177_p4.read() == ap_const_lv7_38);
}

void max_pooling2::thread_icmp_ln35_fu_327_p2() {
    icmp_ln35_fu_327_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_201_p4.read().is_01() || !ap_const_lv4_4.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_201_p4.read() == ap_const_lv4_4);
}

void max_pooling2::thread_icmp_ln36_fu_315_p2() {
    icmp_ln36_fu_315_p2 = (!ap_phi_mux_j_0_phi_fu_224_p4.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_j_0_phi_fu_224_p4.read() == ap_const_lv2_2);
}

void max_pooling2::thread_icmp_ln41_1_fu_914_p2() {
    icmp_ln41_1_fu_914_p2 = (!trunc_ln41_1_fu_887_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln41_1_fu_887_p1.read() == ap_const_lv23_0);
}

void max_pooling2::thread_icmp_ln41_2_fu_926_p2() {
    icmp_ln41_2_fu_926_p2 = (!tmp_6_fu_894_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_6_fu_894_p4.read() != ap_const_lv8_FF);
}

void max_pooling2::thread_icmp_ln41_3_fu_932_p2() {
    icmp_ln41_3_fu_932_p2 = (!trunc_ln41_2_fu_904_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln41_2_fu_904_p1.read() == ap_const_lv23_0);
}

void max_pooling2::thread_icmp_ln41_fu_908_p2() {
    icmp_ln41_fu_908_p2 = (!tmp_fu_877_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_877_p4.read() != ap_const_lv8_FF);
}

void max_pooling2::thread_icmp_ln44_1_fu_495_p2() {
    icmp_ln44_1_fu_495_p2 = (!select_ln35_fu_461_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(select_ln35_fu_461_p3.read() == ap_const_lv2_1);
}

void max_pooling2::thread_icmp_ln44_2_fu_481_p2() {
    icmp_ln44_2_fu_481_p2 = (!select_ln34_fu_411_p3.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(select_ln34_fu_411_p3.read() == ap_const_lv2_0);
}

void max_pooling2::thread_icmp_ln44_fu_303_p2() {
    icmp_ln44_fu_303_p2 = (!ap_phi_mux_i_0_phi_fu_213_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_0_phi_fu_213_p4.read() == ap_const_lv2_1);
}

void max_pooling2::thread_icmp_ln5_2_fu_990_p2() {
    icmp_ln5_2_fu_990_p2 = (!trunc_ln5_fu_980_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln5_fu_980_p1.read() == ap_const_lv23_0);
}

void max_pooling2::thread_icmp_ln5_fu_984_p2() {
    icmp_ln5_fu_984_p2 = (!tmp_8_fu_970_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_8_fu_970_p4.read() != ap_const_lv8_FF);
}

void max_pooling2::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<13>) (zext_ln41_3_fu_850_p1.read());
}

void max_pooling2::thread_input_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void max_pooling2::thread_j_fu_715_p2() {
    j_fu_715_p2 = (!select_ln35_reg_1107.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(select_ln35_reg_1107.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void max_pooling2::thread_max_value_2_fu_956_p3() {
    max_value_2_fu_956_p3 = (!and_ln41_1_fu_950_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln41_1_fu_950_p2.read()[0].to_bool())? max_value_reg_1191.read(): input_load_reg_1198.read());
}

void max_pooling2::thread_max_value_fu_865_p3() {
    max_value_fu_865_p3 = (!or_ln38_fu_860_p2.read()[0].is_01())? sc_lv<32>(): ((or_ln38_fu_860_p2.read()[0].to_bool())? max_value_4_fu_98.read(): ap_const_lv32_D368D4A5);
}

void max_pooling2::thread_or_ln33_1_fu_369_p2() {
    or_ln33_1_fu_369_p2 = (icmp_ln33_fu_273_p2.read() | xor_ln33_fu_363_p2.read());
}

void max_pooling2::thread_or_ln33_fu_357_p2() {
    or_ln33_fu_357_p2 = (and_ln41_6_fu_345_p2.read() | icmp_ln33_fu_273_p2.read());
}

void max_pooling2::thread_or_ln34_1_fu_405_p2() {
    or_ln34_1_fu_405_p2 = (or_ln34_fu_399_p2.read() | icmp_ln33_fu_273_p2.read());
}

void max_pooling2::thread_or_ln34_fu_399_p2() {
    or_ln34_fu_399_p2 = (and_ln33_3_fu_393_p2.read() | and_ln41_6_fu_345_p2.read());
}

void max_pooling2::thread_or_ln35_1_fu_455_p2() {
    or_ln35_1_fu_455_p2 = (or_ln35_fu_449_p2.read() | or_ln33_fu_357_p2.read());
}

void max_pooling2::thread_or_ln35_fu_449_p2() {
    or_ln35_fu_449_p2 = (and_ln34_2_fu_437_p2.read() | and_ln33_3_fu_393_p2.read());
}

void max_pooling2::thread_or_ln38_fu_860_p2() {
    or_ln38_fu_860_p2 = (trunc_ln36_fu_857_p1.read() | select_ln35_1_reg_1114_pp0_iter1_reg.read());
}

void max_pooling2::thread_or_ln41_1_fu_938_p2() {
    or_ln41_1_fu_938_p2 = (icmp_ln41_3_fu_932_p2.read() | icmp_ln41_2_fu_926_p2.read());
}

void max_pooling2::thread_or_ln41_fu_920_p2() {
    or_ln41_fu_920_p2 = (icmp_ln41_1_fu_914_p2.read() | icmp_ln41_fu_908_p2.read());
}

void max_pooling2::thread_or_ln5_fu_996_p2() {
    or_ln5_fu_996_p2 = (icmp_ln5_2_fu_990_p2.read() | icmp_ln5_fu_984_p2.read());
}

void max_pooling2::thread_output_r_address0() {
    output_r_address0 = output_addr_reg_1181_pp0_iter3_reg.read();
}

void max_pooling2::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void max_pooling2::thread_output_r_d0() {
    output_r_d0 = select_ln5_reg_1212.read();
}

void max_pooling2::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(and_ln44_reg_1119_pp0_iter3_reg.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void max_pooling2::thread_p_shl3_cast_fu_804_p3() {
    p_shl3_cast_fu_804_p3 = esl_concat<8,4>(trunc_ln45_fu_800_p1.read(), ap_const_lv4_0);
}

void max_pooling2::thread_p_shl_cast_fu_665_p3() {
    p_shl_cast_fu_665_p3 = esl_concat<9,5>(trunc_ln41_fu_661_p1.read(), ap_const_lv5_0);
}

void max_pooling2::thread_select_ln33_1_fu_573_p3() {
    select_ln33_1_fu_573_p3 = (!and_ln41_6_reg_1058.read()[0].is_01())? sc_lv<5>(): ((and_ln41_6_reg_1058.read()[0].to_bool())? shl_ln40_mid1_fu_566_p3.read(): select_ln41_2_fu_547_p3.read());
}

void max_pooling2::thread_select_ln33_2_fu_580_p3() {
    select_ln33_2_fu_580_p3 = (!and_ln41_6_reg_1058.read()[0].is_01())? sc_lv<4>(): ((and_ln41_6_reg_1058.read()[0].to_bool())? h_reg_1065.read(): select_ln41_reg_1053.read());
}

void max_pooling2::thread_select_ln33_3_fu_593_p3() {
    select_ln33_3_fu_593_p3 = (!or_ln33_reg_1071.read()[0].is_01())? sc_lv<5>(): ((or_ln33_reg_1071.read()[0].to_bool())? ap_const_lv5_0: shl_ln40_s_fu_585_p3.read());
}

void max_pooling2::thread_select_ln33_4_fu_600_p3() {
    select_ln33_4_fu_600_p3 = (!and_ln41_6_reg_1058.read()[0].is_01())? sc_lv<5>(): ((and_ln41_6_reg_1058.read()[0].to_bool())? shl_ln40_mid1_fu_566_p3.read(): select_ln41_3_fu_553_p3.read());
}

void max_pooling2::thread_select_ln33_5_fu_752_p3() {
    select_ln33_5_fu_752_p3 = (!icmp_ln33_reg_1045.read()[0].is_01())? sc_lv<10>(): ((icmp_ln33_reg_1045.read()[0].to_bool())? ap_const_lv10_1: add_ln33_1_fu_746_p2.read());
}

void max_pooling2::thread_select_ln33_fu_559_p3() {
    select_ln33_fu_559_p3 = (!or_ln33_reg_1071.read()[0].is_01())? sc_lv<4>(): ((or_ln33_reg_1071.read()[0].to_bool())? ap_const_lv4_0: ap_phi_mux_w_0_phi_fu_189_p4.read());
}

void max_pooling2::thread_select_ln34_1_fu_621_p3() {
    select_ln34_1_fu_621_p3 = (!and_ln33_3_reg_1078.read()[0].is_01())? sc_lv<5>(): ((and_ln33_3_reg_1078.read()[0].to_bool())? shl_ln40_1_mid1_fu_613_p3.read(): select_ln33_3_fu_593_p3.read());
}

void max_pooling2::thread_select_ln34_2_fu_830_p3() {
    select_ln34_2_fu_830_p3 = (!and_ln33_3_reg_1078.read()[0].is_01())? sc_lv<4>(): ((and_ln33_3_reg_1078.read()[0].to_bool())? w_reg_1141.read(): select_ln33_reg_1130.read());
}

void max_pooling2::thread_select_ln34_3_fu_628_p3() {
    select_ln34_3_fu_628_p3 = (!and_ln33_3_reg_1078.read()[0].is_01())? sc_lv<5>(): ((and_ln33_3_reg_1078.read()[0].to_bool())? select_ln33_1_fu_573_p3.read(): select_ln33_4_fu_600_p3.read());
}

void max_pooling2::thread_select_ln34_4_fu_739_p3() {
    select_ln34_4_fu_739_p3 = (!or_ln33_reg_1071.read()[0].is_01())? sc_lv<7>(): ((or_ln33_reg_1071.read()[0].to_bool())? ap_const_lv7_1: add_ln34_1_fu_733_p2.read());
}

void max_pooling2::thread_select_ln34_fu_411_p3() {
    select_ln34_fu_411_p3 = (!or_ln34_1_fu_405_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln34_1_fu_405_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_i_0_phi_fu_213_p4.read());
}

void max_pooling2::thread_select_ln35_1_fu_473_p3() {
    select_ln35_1_fu_473_p3 = (!and_ln34_2_fu_437_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln34_2_fu_437_p2.read()[0].to_bool())? trunc_ln35_1_fu_469_p1.read(): and_ln34_fu_425_p2.read());
}

void max_pooling2::thread_select_ln35_2_fu_644_p3() {
    select_ln35_2_fu_644_p3 = (!and_ln34_2_reg_1095.read()[0].is_01())? sc_lv<5>(): ((and_ln34_2_reg_1095.read()[0].to_bool())? add_ln40_2_fu_638_p2.read(): select_ln34_3_fu_628_p3.read());
}

void max_pooling2::thread_select_ln35_3_fu_487_p3() {
    select_ln35_3_fu_487_p3 = (!and_ln34_2_fu_437_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln34_2_fu_437_p2.read()[0].to_bool())? icmp_ln44_2_fu_481_p2.read(): and_ln34_1_fu_431_p2.read());
}

void max_pooling2::thread_select_ln35_4_fu_691_p3() {
    select_ln35_4_fu_691_p3 = (!and_ln34_2_reg_1095.read()[0].is_01())? sc_lv<2>(): ((and_ln34_2_reg_1095.read()[0].to_bool())? i_reg_1101.read(): select_ln34_reg_1090.read());
}

void max_pooling2::thread_select_ln35_5_fu_726_p3() {
    select_ln35_5_fu_726_p3 = (!or_ln34_1_reg_1085.read()[0].is_01())? sc_lv<4>(): ((or_ln34_1_reg_1085.read()[0].to_bool())? ap_const_lv4_1: add_ln35_1_fu_720_p2.read());
}

void max_pooling2::thread_select_ln35_fu_461_p3() {
    select_ln35_fu_461_p3 = (!or_ln35_1_fu_455_p2.read()[0].is_01())? sc_lv<2>(): ((or_ln35_1_fu_455_p2.read()[0].to_bool())? ap_const_lv2_0: ap_phi_mux_j_0_phi_fu_224_p4.read());
}

void max_pooling2::thread_select_ln41_1_fu_507_p3() {
    select_ln41_1_fu_507_p3 = (!icmp_ln33_reg_1045.read()[0].is_01())? sc_lv<3>(): ((icmp_ln33_reg_1045.read()[0].to_bool())? c_reg_1040.read(): c_0_reg_138.read());
}

void max_pooling2::thread_select_ln41_2_fu_547_p3() {
    select_ln41_2_fu_547_p3 = (!icmp_ln33_reg_1045.read()[0].is_01())? sc_lv<5>(): ((icmp_ln33_reg_1045.read()[0].to_bool())? ap_const_lv5_0: shl_ln_reg_1021.read());
}

void max_pooling2::thread_select_ln41_3_fu_553_p3() {
    select_ln41_3_fu_553_p3 = (!icmp_ln33_reg_1045.read()[0].is_01())? sc_lv<5>(): ((icmp_ln33_reg_1045.read()[0].to_bool())? ap_const_lv5_0: add_ln40_reg_1026.read());
}

void max_pooling2::thread_select_ln41_fu_279_p3() {
    select_ln41_fu_279_p3 = (!icmp_ln33_fu_273_p2.read()[0].is_01())? sc_lv<4>(): ((icmp_ln33_fu_273_p2.read()[0].to_bool())? ap_const_lv4_0: ap_phi_mux_h_0_phi_fu_166_p4.read());
}

void max_pooling2::thread_select_ln5_fu_1008_p3() {
    select_ln5_fu_1008_p3 = (!and_ln5_fu_1002_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln5_fu_1002_p2.read()[0].to_bool())? max_value_2_reg_1205_pp0_iter3_reg.read(): ap_const_lv32_0);
}

void max_pooling2::thread_sext_ln41_1_fu_681_p1() {
    sext_ln41_1_fu_681_p1 = esl_sext<14,12>(tmp_11_fu_673_p3.read());
}

void max_pooling2::thread_sext_ln41_fu_543_p1() {
    sext_ln41_fu_543_p1 = esl_sext<10,9>(sub_ln41_fu_537_p2.read());
}

void max_pooling2::thread_sext_ln45_1_fu_820_p1() {
    sext_ln45_1_fu_820_p1 = esl_sext<12,10>(tmp_10_fu_812_p3.read());
}

void max_pooling2::thread_sext_ln45_fu_787_p1() {
    sext_ln45_fu_787_p1 = esl_sext<9,8>(sub_ln45_fu_781_p2.read());
}

void max_pooling2::thread_shl_ln40_1_mid1_fu_613_p3() {
    shl_ln40_1_mid1_fu_613_p3 = esl_concat<4,1>(w_fu_607_p2.read(), ap_const_lv1_0);
}

void max_pooling2::thread_shl_ln40_mid1_fu_566_p3() {
    shl_ln40_mid1_fu_566_p3 = esl_concat<4,1>(h_reg_1065.read(), ap_const_lv1_0);
}

void max_pooling2::thread_shl_ln40_s_fu_585_p3() {
    shl_ln40_s_fu_585_p3 = esl_concat<4,1>(ap_phi_mux_w_0_phi_fu_189_p4.read(), ap_const_lv1_0);
}

void max_pooling2::thread_shl_ln_fu_237_p3() {
    shl_ln_fu_237_p3 = esl_concat<4,1>(ap_phi_mux_h_0_phi_fu_166_p4.read(), ap_const_lv1_0);
}

void max_pooling2::thread_sub_ln41_1_fu_685_p2() {
    sub_ln41_1_fu_685_p2 = (!p_shl_cast_fu_665_p3.read().is_01() || !sext_ln41_1_fu_681_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl_cast_fu_665_p3.read()) - sc_bigint<14>(sext_ln41_1_fu_681_p1.read()));
}

void max_pooling2::thread_sub_ln41_fu_537_p2() {
    sub_ln41_fu_537_p2 = (!zext_ln41_fu_521_p1.read().is_01() || !zext_ln41_1_fu_533_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln41_fu_521_p1.read()) - sc_biguint<9>(zext_ln41_1_fu_533_p1.read()));
}

void max_pooling2::thread_sub_ln45_1_fu_824_p2() {
    sub_ln45_1_fu_824_p2 = (!p_shl3_cast_fu_804_p3.read().is_01() || !sext_ln45_1_fu_820_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl3_cast_fu_804_p3.read()) - sc_bigint<12>(sext_ln45_1_fu_820_p1.read()));
}

void max_pooling2::thread_sub_ln45_fu_781_p2() {
    sub_ln45_fu_781_p2 = (!zext_ln45_fu_766_p1.read().is_01() || !zext_ln45_1_fu_777_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln45_fu_766_p1.read()) - sc_biguint<8>(zext_ln45_1_fu_777_p1.read()));
}

void max_pooling2::thread_tmp_10_fu_812_p3() {
    tmp_10_fu_812_p3 = esl_concat<9,1>(add_ln45_fu_794_p2.read(), ap_const_lv1_0);
}

void max_pooling2::thread_tmp_11_fu_673_p3() {
    tmp_11_fu_673_p3 = esl_concat<10,2>(add_ln41_fu_655_p2.read(), ap_const_lv2_0);
}

void max_pooling2::thread_tmp_1_fu_525_p3() {
    tmp_1_fu_525_p3 = esl_concat<3,2>(select_ln41_1_fu_507_p3.read(), ap_const_lv2_0);
}

void max_pooling2::thread_tmp_3_fu_759_p3() {
    tmp_3_fu_759_p3 = esl_concat<3,4>(select_ln41_1_reg_1123.read(), ap_const_lv4_0);
}

void max_pooling2::thread_tmp_4_fu_770_p3() {
    tmp_4_fu_770_p3 = esl_concat<3,1>(select_ln41_1_reg_1123.read(), ap_const_lv1_0);
}

void max_pooling2::thread_tmp_6_fu_894_p4() {
    tmp_6_fu_894_p4 = bitcast_ln41_1_fu_891_p1.read().range(30, 23);
}

void max_pooling2::thread_tmp_8_fu_970_p4() {
    tmp_8_fu_970_p4 = bitcast_ln5_fu_967_p1.read().range(30, 23);
}

void max_pooling2::thread_tmp_fu_877_p4() {
    tmp_fu_877_p4 = bitcast_ln41_fu_874_p1.read().range(30, 23);
}

void max_pooling2::thread_tmp_s_fu_513_p3() {
    tmp_s_fu_513_p3 = esl_concat<3,5>(select_ln41_1_fu_507_p3.read(), ap_const_lv5_0);
}

void max_pooling2::thread_trunc_ln35_1_fu_469_p1() {
    trunc_ln35_1_fu_469_p1 = i_fu_443_p2.read().range(1-1, 0);
}

void max_pooling2::thread_trunc_ln35_fu_293_p1() {
    trunc_ln35_fu_293_p1 = ap_phi_mux_i_0_phi_fu_213_p4.read().range(1-1, 0);
}

void max_pooling2::thread_trunc_ln36_fu_857_p1() {
    trunc_ln36_fu_857_p1 = select_ln35_reg_1107_pp0_iter1_reg.read().range(1-1, 0);
}

void max_pooling2::thread_trunc_ln41_1_fu_887_p1() {
    trunc_ln41_1_fu_887_p1 = bitcast_ln41_fu_874_p1.read().range(23-1, 0);
}

void max_pooling2::thread_trunc_ln41_2_fu_904_p1() {
    trunc_ln41_2_fu_904_p1 = bitcast_ln41_1_fu_891_p1.read().range(23-1, 0);
}

void max_pooling2::thread_trunc_ln41_fu_661_p1() {
    trunc_ln41_fu_661_p1 = add_ln41_fu_655_p2.read().range(9-1, 0);
}

void max_pooling2::thread_trunc_ln45_fu_800_p1() {
    trunc_ln45_fu_800_p1 = add_ln45_fu_794_p2.read().range(8-1, 0);
}

void max_pooling2::thread_trunc_ln5_fu_980_p1() {
    trunc_ln5_fu_980_p1 = bitcast_ln5_fu_967_p1.read().range(23-1, 0);
}

void max_pooling2::thread_w_fu_607_p2() {
    w_fu_607_p2 = (!ap_const_lv4_1.is_01() || !select_ln33_fu_559_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(select_ln33_fu_559_p3.read()));
}

void max_pooling2::thread_xor_ln33_fu_363_p2() {
    xor_ln33_fu_363_p2 = (icmp_ln34_fu_339_p2.read() ^ ap_const_lv1_1);
}

void max_pooling2::thread_xor_ln34_fu_419_p2() {
    xor_ln34_fu_419_p2 = (and_ln33_3_fu_393_p2.read() ^ ap_const_lv1_1);
}

void max_pooling2::thread_xor_ln41_fu_287_p2() {
    xor_ln41_fu_287_p2 = (icmp_ln33_fu_273_p2.read() ^ ap_const_lv1_1);
}

void max_pooling2::thread_zext_ln33_fu_791_p1() {
    zext_ln33_fu_791_p1 = esl_zext<9,4>(select_ln33_2_reg_1135.read());
}

void max_pooling2::thread_zext_ln34_fu_835_p1() {
    zext_ln34_fu_835_p1 = esl_zext<12,4>(select_ln34_2_fu_830_p3.read());
}

void max_pooling2::thread_zext_ln35_1_fu_635_p1() {
    zext_ln35_1_fu_635_p1 = esl_zext<5,2>(i_reg_1101.read());
}

void max_pooling2::thread_zext_ln35_2_fu_651_p1() {
    zext_ln35_2_fu_651_p1 = esl_zext<10,5>(select_ln35_2_fu_644_p3.read());
}

void max_pooling2::thread_zext_ln35_fu_245_p1() {
    zext_ln35_fu_245_p1 = esl_zext<5,2>(ap_phi_mux_i_0_phi_fu_213_p4.read());
}

void max_pooling2::thread_zext_ln36_fu_696_p1() {
    zext_ln36_fu_696_p1 = esl_zext<5,2>(select_ln35_reg_1107.read());
}

void max_pooling2::thread_zext_ln41_1_fu_533_p1() {
    zext_ln41_1_fu_533_p1 = esl_zext<9,5>(tmp_1_fu_525_p3.read());
}

void max_pooling2::thread_zext_ln41_2_fu_705_p1() {
    zext_ln41_2_fu_705_p1 = esl_zext<14,5>(add_ln40_1_fu_699_p2.read());
}

void max_pooling2::thread_zext_ln41_3_fu_850_p1() {
    zext_ln41_3_fu_850_p1 = esl_zext<64,14>(add_ln41_1_reg_1151.read());
}

void max_pooling2::thread_zext_ln41_fu_521_p1() {
    zext_ln41_fu_521_p1 = esl_zext<9,8>(tmp_s_fu_513_p3.read());
}

void max_pooling2::thread_zext_ln45_1_fu_777_p1() {
    zext_ln45_1_fu_777_p1 = esl_zext<8,4>(tmp_4_fu_770_p3.read());
}

void max_pooling2::thread_zext_ln45_2_fu_845_p1() {
    zext_ln45_2_fu_845_p1 = esl_zext<64,12>(add_ln45_1_fu_839_p2.read());
}

void max_pooling2::thread_zext_ln45_fu_766_p1() {
    zext_ln45_fu_766_p1 = esl_zext<8,7>(tmp_3_fu_759_p3.read());
}

void max_pooling2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln32_fu_255_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln32_fu_255_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

