-- (c) Copyright 1995-2024 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
-- DO NOT MODIFY THIS FILE.

-- IP VLNV: xilinx.com:hls:lenet_cnn:1.0
-- IP Revision: 2113500255

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY mnist_bd_lenet_cnn_0_0 IS
  PORT (
    s_axi_CTL_AWADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
    s_axi_CTL_AWVALID : IN STD_LOGIC;
    s_axi_CTL_AWREADY : OUT STD_LOGIC;
    s_axi_CTL_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_axi_CTL_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_axi_CTL_WVALID : IN STD_LOGIC;
    s_axi_CTL_WREADY : OUT STD_LOGIC;
    s_axi_CTL_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    s_axi_CTL_BVALID : OUT STD_LOGIC;
    s_axi_CTL_BREADY : IN STD_LOGIC;
    s_axi_CTL_ARADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
    s_axi_CTL_ARVALID : IN STD_LOGIC;
    s_axi_CTL_ARREADY : OUT STD_LOGIC;
    s_axi_CTL_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_axi_CTL_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    s_axi_CTL_RVALID : OUT STD_LOGIC;
    s_axi_CTL_RREADY : IN STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_DATA_IMAGE_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_IMAGE_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_IMAGE_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_IMAGE_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_IMAGE_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_IMAGE_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_IMAGE_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_IMAGE_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_IMAGE_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_IMAGE_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_IMAGE_AWREADY : IN STD_LOGIC;
    m_axi_DATA_IMAGE_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_IMAGE_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_IMAGE_WLAST : OUT STD_LOGIC;
    m_axi_DATA_IMAGE_WVALID : OUT STD_LOGIC;
    m_axi_DATA_IMAGE_WREADY : IN STD_LOGIC;
    m_axi_DATA_IMAGE_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_IMAGE_BVALID : IN STD_LOGIC;
    m_axi_DATA_IMAGE_BREADY : OUT STD_LOGIC;
    m_axi_DATA_IMAGE_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_IMAGE_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_IMAGE_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_IMAGE_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_IMAGE_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_IMAGE_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_IMAGE_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_IMAGE_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_IMAGE_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_IMAGE_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_IMAGE_ARREADY : IN STD_LOGIC;
    m_axi_DATA_IMAGE_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_IMAGE_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_IMAGE_RLAST : IN STD_LOGIC;
    m_axi_DATA_IMAGE_RVALID : IN STD_LOGIC;
    m_axi_DATA_IMAGE_RREADY : OUT STD_LOGIC;
    m_axi_DATA_PARAMETERS_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_PARAMETERS_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_PARAMETERS_AWREADY : IN STD_LOGIC;
    m_axi_DATA_PARAMETERS_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_PARAMETERS_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_PARAMETERS_WLAST : OUT STD_LOGIC;
    m_axi_DATA_PARAMETERS_WVALID : OUT STD_LOGIC;
    m_axi_DATA_PARAMETERS_WREADY : IN STD_LOGIC;
    m_axi_DATA_PARAMETERS_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_PARAMETERS_BVALID : IN STD_LOGIC;
    m_axi_DATA_PARAMETERS_BREADY : OUT STD_LOGIC;
    m_axi_DATA_PARAMETERS_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_PARAMETERS_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_PARAMETERS_ARREADY : IN STD_LOGIC;
    m_axi_DATA_PARAMETERS_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_PARAMETERS_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_PARAMETERS_RLAST : IN STD_LOGIC;
    m_axi_DATA_PARAMETERS_RVALID : IN STD_LOGIC;
    m_axi_DATA_PARAMETERS_RREADY : OUT STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_AWREADY : IN STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_WLAST : OUT STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_WVALID : OUT STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_WREADY : IN STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_BVALID : IN STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_BREADY : OUT STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_ARREADY : IN STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_FC6_OUTPUT_RLAST : IN STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_RVALID : IN STD_LOGIC;
    m_axi_DATA_FC6_OUTPUT_RREADY : OUT STD_LOGIC
  );
END mnist_bd_lenet_cnn_0_0;

ARCHITECTURE mnist_bd_lenet_cnn_0_0_arch OF mnist_bd_lenet_cnn_0_0 IS
  ATTRIBUTE DowngradeIPIdentifiedWarnings : STRING;
  ATTRIBUTE DowngradeIPIdentifiedWarnings OF mnist_bd_lenet_cnn_0_0_arch: ARCHITECTURE IS "yes";
  COMPONENT lenet_cnn IS
    GENERIC (
      C_S_AXI_CTL_ADDR_WIDTH : INTEGER;
      C_S_AXI_CTL_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_IMAGE_USER_VALUE : INTEGER;
      C_M_AXI_DATA_IMAGE_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_IMAGE_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_PARAMETERS_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_PARAMETERS_USER_VALUE : INTEGER;
      C_M_AXI_DATA_PARAMETERS_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_PARAMETERS_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_USER_VALUE : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_FC6_OUTPUT_CACHE_VALUE : INTEGER
    );
    PORT (
      s_axi_CTL_AWADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
      s_axi_CTL_AWVALID : IN STD_LOGIC;
      s_axi_CTL_AWREADY : OUT STD_LOGIC;
      s_axi_CTL_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_axi_CTL_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_axi_CTL_WVALID : IN STD_LOGIC;
      s_axi_CTL_WREADY : OUT STD_LOGIC;
      s_axi_CTL_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      s_axi_CTL_BVALID : OUT STD_LOGIC;
      s_axi_CTL_BREADY : IN STD_LOGIC;
      s_axi_CTL_ARADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
      s_axi_CTL_ARVALID : IN STD_LOGIC;
      s_axi_CTL_ARREADY : OUT STD_LOGIC;
      s_axi_CTL_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_axi_CTL_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      s_axi_CTL_RVALID : OUT STD_LOGIC;
      s_axi_CTL_RREADY : IN STD_LOGIC;
      ap_clk : IN STD_LOGIC;
      ap_rst_n : IN STD_LOGIC;
      interrupt : OUT STD_LOGIC;
      m_axi_DATA_IMAGE_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_IMAGE_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_IMAGE_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_IMAGE_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_IMAGE_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_IMAGE_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_IMAGE_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_IMAGE_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_IMAGE_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_IMAGE_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_IMAGE_AWREADY : IN STD_LOGIC;
      m_axi_DATA_IMAGE_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_IMAGE_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_IMAGE_WLAST : OUT STD_LOGIC;
      m_axi_DATA_IMAGE_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_WVALID : OUT STD_LOGIC;
      m_axi_DATA_IMAGE_WREADY : IN STD_LOGIC;
      m_axi_DATA_IMAGE_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_IMAGE_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_BVALID : IN STD_LOGIC;
      m_axi_DATA_IMAGE_BREADY : OUT STD_LOGIC;
      m_axi_DATA_IMAGE_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_IMAGE_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_IMAGE_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_IMAGE_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_IMAGE_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_IMAGE_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_IMAGE_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_IMAGE_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_IMAGE_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_IMAGE_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_IMAGE_ARREADY : IN STD_LOGIC;
      m_axi_DATA_IMAGE_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_IMAGE_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_IMAGE_RLAST : IN STD_LOGIC;
      m_axi_DATA_IMAGE_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_IMAGE_RVALID : IN STD_LOGIC;
      m_axi_DATA_IMAGE_RREADY : OUT STD_LOGIC;
      m_axi_DATA_PARAMETERS_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_PARAMETERS_AWREADY : IN STD_LOGIC;
      m_axi_DATA_PARAMETERS_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_PARAMETERS_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_PARAMETERS_WLAST : OUT STD_LOGIC;
      m_axi_DATA_PARAMETERS_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_WVALID : OUT STD_LOGIC;
      m_axi_DATA_PARAMETERS_WREADY : IN STD_LOGIC;
      m_axi_DATA_PARAMETERS_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_PARAMETERS_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_BVALID : IN STD_LOGIC;
      m_axi_DATA_PARAMETERS_BREADY : OUT STD_LOGIC;
      m_axi_DATA_PARAMETERS_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_PARAMETERS_ARREADY : IN STD_LOGIC;
      m_axi_DATA_PARAMETERS_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_PARAMETERS_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_PARAMETERS_RLAST : IN STD_LOGIC;
      m_axi_DATA_PARAMETERS_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_PARAMETERS_RVALID : IN STD_LOGIC;
      m_axi_DATA_PARAMETERS_RREADY : OUT STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_AWREADY : IN STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_WLAST : OUT STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_WVALID : OUT STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_WREADY : IN STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_BVALID : IN STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_BREADY : OUT STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_ARREADY : IN STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_RLAST : IN STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_FC6_OUTPUT_RVALID : IN STD_LOGIC;
      m_axi_DATA_FC6_OUTPUT_RREADY : OUT STD_LOGIC
    );
  END COMPONENT lenet_cnn;
  ATTRIBUTE IP_DEFINITION_SOURCE : STRING;
  ATTRIBUTE IP_DEFINITION_SOURCE OF mnist_bd_lenet_cnn_0_0_arch: ARCHITECTURE IS "HLS";
  ATTRIBUTE X_INTERFACE_INFO : STRING;
  ATTRIBUTE X_INTERFACE_PARAMETER : STRING;
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_FC6_OUTPUT_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_FC6_OUTPUT, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.000, " & 
"CLK_DOMAIN mnist_bd_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_FC6_OUTPUT_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_FC6_OUTPUT AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_PARAMETERS_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_PARAMETERS, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.000, " & 
"CLK_DOMAIN mnist_bd_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_PARAMETERS_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_PARAMETERS AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_IMAGE_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_IMAGE, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.000, CLK_D" & 
"OMAIN mnist_bd_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_IMAGE_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_IMAGE AWADDR";
  ATTRIBUTE X_INTERFACE_PARAMETER OF interrupt: SIGNAL IS "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  ATTRIBUTE X_INTERFACE_INFO OF interrupt: SIGNAL IS "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  ATTRIBUTE X_INTERFACE_PARAMETER OF ap_rst_n: SIGNAL IS "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF ap_rst_n: SIGNAL IS "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  ATTRIBUTE X_INTERFACE_PARAMETER OF ap_clk: SIGNAL IS "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_CTL:m_axi_DATA_IMAGE:m_axi_DATA_PARAMETERS:m_axi_DATA_FC6_OUTPUT, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000, PHASE 0.000, CLK_DOMAIN mnist_bd_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF ap_clk: SIGNAL IS "xilinx.com:signal:clock:1.0 ap_clk CLK";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL AWVALID";
  ATTRIBUTE X_INTERFACE_PARAMETER OF s_axi_CTL_AWADDR: SIGNAL IS "XIL_INTERFACENAME s_axi_CTL, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.000, CLK_DOMAIN mnist_bd_processing_system7_0_0_FCLK_CLK0, NUM_READ_THR" & 
"EADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL AWADDR";
BEGIN
  U0 : lenet_cnn
    GENERIC MAP (
      C_S_AXI_CTL_ADDR_WIDTH => 6,
      C_S_AXI_CTL_DATA_WIDTH => 32,
      C_M_AXI_DATA_IMAGE_ID_WIDTH => 1,
      C_M_AXI_DATA_IMAGE_ADDR_WIDTH => 32,
      C_M_AXI_DATA_IMAGE_DATA_WIDTH => 32,
      C_M_AXI_DATA_IMAGE_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_IMAGE_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_IMAGE_WUSER_WIDTH => 1,
      C_M_AXI_DATA_IMAGE_RUSER_WIDTH => 1,
      C_M_AXI_DATA_IMAGE_BUSER_WIDTH => 1,
      C_M_AXI_DATA_IMAGE_USER_VALUE => 0,
      C_M_AXI_DATA_IMAGE_PROT_VALUE => 0,
      C_M_AXI_DATA_IMAGE_CACHE_VALUE => 3,
      C_M_AXI_DATA_PARAMETERS_ID_WIDTH => 1,
      C_M_AXI_DATA_PARAMETERS_ADDR_WIDTH => 32,
      C_M_AXI_DATA_PARAMETERS_DATA_WIDTH => 32,
      C_M_AXI_DATA_PARAMETERS_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_PARAMETERS_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_PARAMETERS_WUSER_WIDTH => 1,
      C_M_AXI_DATA_PARAMETERS_RUSER_WIDTH => 1,
      C_M_AXI_DATA_PARAMETERS_BUSER_WIDTH => 1,
      C_M_AXI_DATA_PARAMETERS_USER_VALUE => 0,
      C_M_AXI_DATA_PARAMETERS_PROT_VALUE => 0,
      C_M_AXI_DATA_PARAMETERS_CACHE_VALUE => 3,
      C_M_AXI_DATA_FC6_OUTPUT_ID_WIDTH => 1,
      C_M_AXI_DATA_FC6_OUTPUT_ADDR_WIDTH => 32,
      C_M_AXI_DATA_FC6_OUTPUT_DATA_WIDTH => 32,
      C_M_AXI_DATA_FC6_OUTPUT_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_FC6_OUTPUT_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_FC6_OUTPUT_WUSER_WIDTH => 1,
      C_M_AXI_DATA_FC6_OUTPUT_RUSER_WIDTH => 1,
      C_M_AXI_DATA_FC6_OUTPUT_BUSER_WIDTH => 1,
      C_M_AXI_DATA_FC6_OUTPUT_USER_VALUE => 0,
      C_M_AXI_DATA_FC6_OUTPUT_PROT_VALUE => 0,
      C_M_AXI_DATA_FC6_OUTPUT_CACHE_VALUE => 3
    )
    PORT MAP (
      s_axi_CTL_AWADDR => s_axi_CTL_AWADDR,
      s_axi_CTL_AWVALID => s_axi_CTL_AWVALID,
      s_axi_CTL_AWREADY => s_axi_CTL_AWREADY,
      s_axi_CTL_WDATA => s_axi_CTL_WDATA,
      s_axi_CTL_WSTRB => s_axi_CTL_WSTRB,
      s_axi_CTL_WVALID => s_axi_CTL_WVALID,
      s_axi_CTL_WREADY => s_axi_CTL_WREADY,
      s_axi_CTL_BRESP => s_axi_CTL_BRESP,
      s_axi_CTL_BVALID => s_axi_CTL_BVALID,
      s_axi_CTL_BREADY => s_axi_CTL_BREADY,
      s_axi_CTL_ARADDR => s_axi_CTL_ARADDR,
      s_axi_CTL_ARVALID => s_axi_CTL_ARVALID,
      s_axi_CTL_ARREADY => s_axi_CTL_ARREADY,
      s_axi_CTL_RDATA => s_axi_CTL_RDATA,
      s_axi_CTL_RRESP => s_axi_CTL_RRESP,
      s_axi_CTL_RVALID => s_axi_CTL_RVALID,
      s_axi_CTL_RREADY => s_axi_CTL_RREADY,
      ap_clk => ap_clk,
      ap_rst_n => ap_rst_n,
      interrupt => interrupt,
      m_axi_DATA_IMAGE_AWADDR => m_axi_DATA_IMAGE_AWADDR,
      m_axi_DATA_IMAGE_AWLEN => m_axi_DATA_IMAGE_AWLEN,
      m_axi_DATA_IMAGE_AWSIZE => m_axi_DATA_IMAGE_AWSIZE,
      m_axi_DATA_IMAGE_AWBURST => m_axi_DATA_IMAGE_AWBURST,
      m_axi_DATA_IMAGE_AWLOCK => m_axi_DATA_IMAGE_AWLOCK,
      m_axi_DATA_IMAGE_AWREGION => m_axi_DATA_IMAGE_AWREGION,
      m_axi_DATA_IMAGE_AWCACHE => m_axi_DATA_IMAGE_AWCACHE,
      m_axi_DATA_IMAGE_AWPROT => m_axi_DATA_IMAGE_AWPROT,
      m_axi_DATA_IMAGE_AWQOS => m_axi_DATA_IMAGE_AWQOS,
      m_axi_DATA_IMAGE_AWVALID => m_axi_DATA_IMAGE_AWVALID,
      m_axi_DATA_IMAGE_AWREADY => m_axi_DATA_IMAGE_AWREADY,
      m_axi_DATA_IMAGE_WDATA => m_axi_DATA_IMAGE_WDATA,
      m_axi_DATA_IMAGE_WSTRB => m_axi_DATA_IMAGE_WSTRB,
      m_axi_DATA_IMAGE_WLAST => m_axi_DATA_IMAGE_WLAST,
      m_axi_DATA_IMAGE_WVALID => m_axi_DATA_IMAGE_WVALID,
      m_axi_DATA_IMAGE_WREADY => m_axi_DATA_IMAGE_WREADY,
      m_axi_DATA_IMAGE_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_IMAGE_BRESP => m_axi_DATA_IMAGE_BRESP,
      m_axi_DATA_IMAGE_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_IMAGE_BVALID => m_axi_DATA_IMAGE_BVALID,
      m_axi_DATA_IMAGE_BREADY => m_axi_DATA_IMAGE_BREADY,
      m_axi_DATA_IMAGE_ARADDR => m_axi_DATA_IMAGE_ARADDR,
      m_axi_DATA_IMAGE_ARLEN => m_axi_DATA_IMAGE_ARLEN,
      m_axi_DATA_IMAGE_ARSIZE => m_axi_DATA_IMAGE_ARSIZE,
      m_axi_DATA_IMAGE_ARBURST => m_axi_DATA_IMAGE_ARBURST,
      m_axi_DATA_IMAGE_ARLOCK => m_axi_DATA_IMAGE_ARLOCK,
      m_axi_DATA_IMAGE_ARREGION => m_axi_DATA_IMAGE_ARREGION,
      m_axi_DATA_IMAGE_ARCACHE => m_axi_DATA_IMAGE_ARCACHE,
      m_axi_DATA_IMAGE_ARPROT => m_axi_DATA_IMAGE_ARPROT,
      m_axi_DATA_IMAGE_ARQOS => m_axi_DATA_IMAGE_ARQOS,
      m_axi_DATA_IMAGE_ARVALID => m_axi_DATA_IMAGE_ARVALID,
      m_axi_DATA_IMAGE_ARREADY => m_axi_DATA_IMAGE_ARREADY,
      m_axi_DATA_IMAGE_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_IMAGE_RDATA => m_axi_DATA_IMAGE_RDATA,
      m_axi_DATA_IMAGE_RRESP => m_axi_DATA_IMAGE_RRESP,
      m_axi_DATA_IMAGE_RLAST => m_axi_DATA_IMAGE_RLAST,
      m_axi_DATA_IMAGE_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_IMAGE_RVALID => m_axi_DATA_IMAGE_RVALID,
      m_axi_DATA_IMAGE_RREADY => m_axi_DATA_IMAGE_RREADY,
      m_axi_DATA_PARAMETERS_AWADDR => m_axi_DATA_PARAMETERS_AWADDR,
      m_axi_DATA_PARAMETERS_AWLEN => m_axi_DATA_PARAMETERS_AWLEN,
      m_axi_DATA_PARAMETERS_AWSIZE => m_axi_DATA_PARAMETERS_AWSIZE,
      m_axi_DATA_PARAMETERS_AWBURST => m_axi_DATA_PARAMETERS_AWBURST,
      m_axi_DATA_PARAMETERS_AWLOCK => m_axi_DATA_PARAMETERS_AWLOCK,
      m_axi_DATA_PARAMETERS_AWREGION => m_axi_DATA_PARAMETERS_AWREGION,
      m_axi_DATA_PARAMETERS_AWCACHE => m_axi_DATA_PARAMETERS_AWCACHE,
      m_axi_DATA_PARAMETERS_AWPROT => m_axi_DATA_PARAMETERS_AWPROT,
      m_axi_DATA_PARAMETERS_AWQOS => m_axi_DATA_PARAMETERS_AWQOS,
      m_axi_DATA_PARAMETERS_AWVALID => m_axi_DATA_PARAMETERS_AWVALID,
      m_axi_DATA_PARAMETERS_AWREADY => m_axi_DATA_PARAMETERS_AWREADY,
      m_axi_DATA_PARAMETERS_WDATA => m_axi_DATA_PARAMETERS_WDATA,
      m_axi_DATA_PARAMETERS_WSTRB => m_axi_DATA_PARAMETERS_WSTRB,
      m_axi_DATA_PARAMETERS_WLAST => m_axi_DATA_PARAMETERS_WLAST,
      m_axi_DATA_PARAMETERS_WVALID => m_axi_DATA_PARAMETERS_WVALID,
      m_axi_DATA_PARAMETERS_WREADY => m_axi_DATA_PARAMETERS_WREADY,
      m_axi_DATA_PARAMETERS_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_PARAMETERS_BRESP => m_axi_DATA_PARAMETERS_BRESP,
      m_axi_DATA_PARAMETERS_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_PARAMETERS_BVALID => m_axi_DATA_PARAMETERS_BVALID,
      m_axi_DATA_PARAMETERS_BREADY => m_axi_DATA_PARAMETERS_BREADY,
      m_axi_DATA_PARAMETERS_ARADDR => m_axi_DATA_PARAMETERS_ARADDR,
      m_axi_DATA_PARAMETERS_ARLEN => m_axi_DATA_PARAMETERS_ARLEN,
      m_axi_DATA_PARAMETERS_ARSIZE => m_axi_DATA_PARAMETERS_ARSIZE,
      m_axi_DATA_PARAMETERS_ARBURST => m_axi_DATA_PARAMETERS_ARBURST,
      m_axi_DATA_PARAMETERS_ARLOCK => m_axi_DATA_PARAMETERS_ARLOCK,
      m_axi_DATA_PARAMETERS_ARREGION => m_axi_DATA_PARAMETERS_ARREGION,
      m_axi_DATA_PARAMETERS_ARCACHE => m_axi_DATA_PARAMETERS_ARCACHE,
      m_axi_DATA_PARAMETERS_ARPROT => m_axi_DATA_PARAMETERS_ARPROT,
      m_axi_DATA_PARAMETERS_ARQOS => m_axi_DATA_PARAMETERS_ARQOS,
      m_axi_DATA_PARAMETERS_ARVALID => m_axi_DATA_PARAMETERS_ARVALID,
      m_axi_DATA_PARAMETERS_ARREADY => m_axi_DATA_PARAMETERS_ARREADY,
      m_axi_DATA_PARAMETERS_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_PARAMETERS_RDATA => m_axi_DATA_PARAMETERS_RDATA,
      m_axi_DATA_PARAMETERS_RRESP => m_axi_DATA_PARAMETERS_RRESP,
      m_axi_DATA_PARAMETERS_RLAST => m_axi_DATA_PARAMETERS_RLAST,
      m_axi_DATA_PARAMETERS_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_PARAMETERS_RVALID => m_axi_DATA_PARAMETERS_RVALID,
      m_axi_DATA_PARAMETERS_RREADY => m_axi_DATA_PARAMETERS_RREADY,
      m_axi_DATA_FC6_OUTPUT_AWADDR => m_axi_DATA_FC6_OUTPUT_AWADDR,
      m_axi_DATA_FC6_OUTPUT_AWLEN => m_axi_DATA_FC6_OUTPUT_AWLEN,
      m_axi_DATA_FC6_OUTPUT_AWSIZE => m_axi_DATA_FC6_OUTPUT_AWSIZE,
      m_axi_DATA_FC6_OUTPUT_AWBURST => m_axi_DATA_FC6_OUTPUT_AWBURST,
      m_axi_DATA_FC6_OUTPUT_AWLOCK => m_axi_DATA_FC6_OUTPUT_AWLOCK,
      m_axi_DATA_FC6_OUTPUT_AWREGION => m_axi_DATA_FC6_OUTPUT_AWREGION,
      m_axi_DATA_FC6_OUTPUT_AWCACHE => m_axi_DATA_FC6_OUTPUT_AWCACHE,
      m_axi_DATA_FC6_OUTPUT_AWPROT => m_axi_DATA_FC6_OUTPUT_AWPROT,
      m_axi_DATA_FC6_OUTPUT_AWQOS => m_axi_DATA_FC6_OUTPUT_AWQOS,
      m_axi_DATA_FC6_OUTPUT_AWVALID => m_axi_DATA_FC6_OUTPUT_AWVALID,
      m_axi_DATA_FC6_OUTPUT_AWREADY => m_axi_DATA_FC6_OUTPUT_AWREADY,
      m_axi_DATA_FC6_OUTPUT_WDATA => m_axi_DATA_FC6_OUTPUT_WDATA,
      m_axi_DATA_FC6_OUTPUT_WSTRB => m_axi_DATA_FC6_OUTPUT_WSTRB,
      m_axi_DATA_FC6_OUTPUT_WLAST => m_axi_DATA_FC6_OUTPUT_WLAST,
      m_axi_DATA_FC6_OUTPUT_WVALID => m_axi_DATA_FC6_OUTPUT_WVALID,
      m_axi_DATA_FC6_OUTPUT_WREADY => m_axi_DATA_FC6_OUTPUT_WREADY,
      m_axi_DATA_FC6_OUTPUT_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_FC6_OUTPUT_BRESP => m_axi_DATA_FC6_OUTPUT_BRESP,
      m_axi_DATA_FC6_OUTPUT_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_FC6_OUTPUT_BVALID => m_axi_DATA_FC6_OUTPUT_BVALID,
      m_axi_DATA_FC6_OUTPUT_BREADY => m_axi_DATA_FC6_OUTPUT_BREADY,
      m_axi_DATA_FC6_OUTPUT_ARADDR => m_axi_DATA_FC6_OUTPUT_ARADDR,
      m_axi_DATA_FC6_OUTPUT_ARLEN => m_axi_DATA_FC6_OUTPUT_ARLEN,
      m_axi_DATA_FC6_OUTPUT_ARSIZE => m_axi_DATA_FC6_OUTPUT_ARSIZE,
      m_axi_DATA_FC6_OUTPUT_ARBURST => m_axi_DATA_FC6_OUTPUT_ARBURST,
      m_axi_DATA_FC6_OUTPUT_ARLOCK => m_axi_DATA_FC6_OUTPUT_ARLOCK,
      m_axi_DATA_FC6_OUTPUT_ARREGION => m_axi_DATA_FC6_OUTPUT_ARREGION,
      m_axi_DATA_FC6_OUTPUT_ARCACHE => m_axi_DATA_FC6_OUTPUT_ARCACHE,
      m_axi_DATA_FC6_OUTPUT_ARPROT => m_axi_DATA_FC6_OUTPUT_ARPROT,
      m_axi_DATA_FC6_OUTPUT_ARQOS => m_axi_DATA_FC6_OUTPUT_ARQOS,
      m_axi_DATA_FC6_OUTPUT_ARVALID => m_axi_DATA_FC6_OUTPUT_ARVALID,
      m_axi_DATA_FC6_OUTPUT_ARREADY => m_axi_DATA_FC6_OUTPUT_ARREADY,
      m_axi_DATA_FC6_OUTPUT_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_FC6_OUTPUT_RDATA => m_axi_DATA_FC6_OUTPUT_RDATA,
      m_axi_DATA_FC6_OUTPUT_RRESP => m_axi_DATA_FC6_OUTPUT_RRESP,
      m_axi_DATA_FC6_OUTPUT_RLAST => m_axi_DATA_FC6_OUTPUT_RLAST,
      m_axi_DATA_FC6_OUTPUT_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_FC6_OUTPUT_RVALID => m_axi_DATA_FC6_OUTPUT_RVALID,
      m_axi_DATA_FC6_OUTPUT_RREADY => m_axi_DATA_FC6_OUTPUT_RREADY
    );
END mnist_bd_lenet_cnn_0_0_arch;
