# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_xbar_0/mnist_bd_xbar_0.xci
# IP: The module: 'mnist_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_xbar_0/mnist_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_xbar_0/mnist_bd_xbar_0.xci
# IP: The module: 'mnist_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_xbar_0/mnist_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
