#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : mnist_bd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Apr 04 12:48:40 -0500 2024
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: mnist_bd.sh [-help]
# usage: mnist_bd.sh [-lib_map_path]
# usage: mnist_bd.sh [-noclean_files]
# usage: mnist_bd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'mnist_bd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_5 processing_system7_vip_v1_0_7 xlconstant_v1_1_6 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_lite_ipif_v3_0_4 lib_pkg_v1_0_2 axi_timer_v2_0_21 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_19 fifo_generator_v13_2_4 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_15 floating_point_v7_1_8 axi_protocol_converter_v2_1_19)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "mnist_bd.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_processing_system7_0_0/sim/mnist_bd_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/sim/bd_bd60.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_bd60_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_bd60_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_bd60_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_bd60_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/7de4/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_bd60_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_bd60_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_bd60_sarn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_bd60_srn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_bd60_sawn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_bd60_swn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_bd60_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_bd60_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_bd60_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_0/sim/mnist_bd_smartconnect_0_0.v" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/sim/bd_7da1.v" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_0/sim/bd_7da1_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_1/sim/bd_7da1_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_2/sim/bd_7da1_s00mmu_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_3/sim/bd_7da1_s00tr_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_4/sim/bd_7da1_s00sic_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_5/sim/bd_7da1_s00a2s_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_6/sim/bd_7da1_sarn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_7/sim/bd_7da1_srn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_8/sim/bd_7da1_sawn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_9/sim/bd_7da1_swn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_10/sim/bd_7da1_sbn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_11/sim/bd_7da1_m00s2a_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_12/sim/bd_7da1_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/sim/mnist_bd_smartconnect_0_1.v" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/sim/bd_7d31.v" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_0/sim/bd_7d31_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_1/sim/bd_7d31_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_2/sim/bd_7d31_s00mmu_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_3/sim/bd_7d31_s00tr_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_4/sim/bd_7d31_s00sic_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_5/sim/bd_7d31_s00a2s_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_6/sim/bd_7d31_sarn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_7/sim/bd_7d31_srn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_8/sim/bd_7d31_sawn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_9/sim/bd_7d31_swn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_10/sim/bd_7d31_sbn_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_11/sim/bd_7d31_m00s2a_0.sv" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/bd_0/ip/ip_12/sim/bd_7d31_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_smartconnect_1_0/sim/mnist_bd_smartconnect_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/a788/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_axi_timer_0_0/sim/mnist_bd_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_xbar_0/sim/mnist_bd_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_proc_sys_reset_0_0/sim/mnist_bd_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1123/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_15 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/d4d2/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_8 $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/83a3/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/convolution1.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/convolution3.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/convolution5.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv1_bg8j.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv1_oncg.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv1_wfYi.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv3_bibs.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv3_opcA.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv3_whbi.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv5_bkbM.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_conv5_wjbC.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_CTL_s_axi.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_DATA_FC6_OUTPUT_m_axi.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_DATA_IMAGE_m_axi.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_DATA_PARAMETERS_m_axi.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_fadd_32bkb.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_fc6_bias.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_fc6_weilbW.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_fcmp_32dEe.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_fmul_32cud.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_mul_muleOg.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_output_mb6.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_pool2_oocq.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_pool4_oqcK.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn_urem_5nsc4.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/max_pooling2.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/max_pooling4.v" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/verilog/lenet_cnn.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/ip/lenet_cnn_ap_fadd_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/ip/lenet_cnn_ap_fcmp_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b513/hdl/ip/lenet_cnn_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_lenet_cnn_0_0/sim/mnist_bd_lenet_cnn_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_processing_system7_0_0" +incdir+"C:/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/mnist_bd/ip/mnist_bd_auto_pc_0/sim/mnist_bd_auto_pc_0.v" \
    "$ref_dir/../../../bd/mnist_bd/sim/mnist_bd.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.mnist_bd xil_defaultlib.glbl -o mnist_bd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./mnist_bd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./mnist_bd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key mnist_bd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc mnist_bd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./mnist_bd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: mnist_bd.sh [-help]\n\
Usage: mnist_bd.sh [-lib_map_path]\n\
Usage: mnist_bd.sh [-reset_run]\n\
Usage: mnist_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
