# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/mnist_bd_smartconnect_0_1.xci
# IP: The module: 'mnist_bd_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/bd_7da1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_0/bd_7da1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_7da1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_2/bd_7da1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_3/bd_7da1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_4/bd_7da1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_7da1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_7da1_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_7/bd_7da1_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_8/bd_7da1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_9/bd_7da1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_7da1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_7da1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_12/bd_7da1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_7da1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_7da1_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_7da1_s00a2s_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_7da1_sarn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_7/bd_7da1_srn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_8/bd_7da1_sawn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_9/bd_7da1_swn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_7da1_sbn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_7da1_m00s2a_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_bd_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/mnist_bd_smartconnect_0_1.xci
# IP: The module: 'mnist_bd_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/bd_7da1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_0/bd_7da1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_7da1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_2/bd_7da1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_3/bd_7da1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_4/bd_7da1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_7da1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_7da1_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_7/bd_7da1_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_8/bd_7da1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_9/bd_7da1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_7da1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_7da1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_12/bd_7da1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_7da1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_7da1_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_7da1_s00a2s_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_7da1_sarn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_7/bd_7da1_srn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_8/bd_7da1_sawn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_9/bd_7da1_swn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_7da1_sbn_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_7da1_m00s2a_0_ooc.xdc

# XDC: c:/cs543/mnist_hw_acc/mnist_soc/mnist_soc.srcs/sources_1/bd/mnist_bd/ip/mnist_bd_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mnist_bd_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
